<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>22&nbsp; Large Language Models – deep_learning_notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/nlp/20-text-embeddings-evaluation.html" rel="next">
<link href="../../chapters/nlp/18-sequence-models.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-fd0503e23dce65854c81c5baaade3bdf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/nlp/19-large-language-models.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Large Language Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">deep_learning_notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/_intro_foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-neural-networks-and-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Neural Networks and Optimization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-generalization-and-learning-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Generalization and Learning Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/_intro_computer_vision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computer Vision</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Visual Understanding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/03-cnns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Convolutional Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/04-object-detection-and-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Detection and Segmentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/05-vision-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vision Transformers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/06-foundation-models-for-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Foundation Models for Segmentation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Self-Supervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/06-self-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Self-Supervised Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV: Generative Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/_intro-generative-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generative Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/07-vaes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variational Autoencoders (VAEs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/08-gans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generative Adversarial Networks (GANs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/09-diffusion-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diffusion Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/_conclusion-generative-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusion</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/_intro_video.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Video</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/10-video.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Video Fundamentals: Motion and Spatiotemporal Architectures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/11-video-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Video Understanding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/12-video-temporal-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Video Temporal Segmentation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/13-video-understanding-benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Video Understanding Benchmarks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/14-video-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Video Generation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/_intro_3d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3D Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/11-3d-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">3D Data Understanding</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">3D Reconstruction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/12-3d-reconstruction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">3D Reconstruction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/13-gaussian-splatting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">3D Gaussian Splatting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Human Pose Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/human_pose_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Human Pose Estimation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/_intro_nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Natural Language Processing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/17-text-representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Text Representation &amp; Word Embeddings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/18-sequence-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Sequence Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/19-large-language-models.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Large Language Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/20-text-embeddings-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Text Embedding Models &amp; Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision_language/_intro_vision_language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vision-Language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision_language/16-vision-language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Vision-Language Multimodal Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/_intro_time_series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time Series</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/14-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Time Series Fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/15-deep-learning-for-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Deep Learning for Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/_intro_audio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Audio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/21-speech-representation-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Speech Representation Learning and Foundation Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/22-automatic-speech-recognition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Automatic Speech Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/23-speaker-diarization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Speaker Diarization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/24-neural-audio-codecs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Neural Audio Codecs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/25-speech-synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Speech Synthesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/26-speech-language-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Speech and Audio Language Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/27-audio-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Audio Understanding Beyond Words</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#decoder-architecture-improvements" id="toc-decoder-architecture-improvements" class="nav-link active" data-scroll-target="#decoder-architecture-improvements"><span class="header-section-number">22.1</span> Decoder Architecture Improvements</a>
  <ul class="collapse">
  <li><a href="#rotary-position-embeddings-rope" id="toc-rotary-position-embeddings-rope" class="nav-link" data-scroll-target="#rotary-position-embeddings-rope"><span class="header-section-number">22.1.1</span> Rotary Position Embeddings (RoPE)</a></li>
  <li><a href="#pre-norm-and-rmsnorm" id="toc-pre-norm-and-rmsnorm" class="nav-link" data-scroll-target="#pre-norm-and-rmsnorm"><span class="header-section-number">22.1.2</span> Pre-Norm and RMSNorm</a></li>
  <li><a href="#grouped-query-attention-gqa-and-kv-caching" id="toc-grouped-query-attention-gqa-and-kv-caching" class="nav-link" data-scroll-target="#grouped-query-attention-gqa-and-kv-caching"><span class="header-section-number">22.1.3</span> Grouped-Query Attention (GQA) and KV-Caching</a></li>
  <li><a href="#swiglu-and-gated-activations" id="toc-swiglu-and-gated-activations" class="nav-link" data-scroll-target="#swiglu-and-gated-activations"><span class="header-section-number">22.1.4</span> SwiGLU and Gated Activations</a></li>
  <li><a href="#flashattention" id="toc-flashattention" class="nav-link" data-scroll-target="#flashattention"><span class="header-section-number">22.1.5</span> FlashAttention</a></li>
  <li><a href="#mixture-of-experts-moe" id="toc-mixture-of-experts-moe" class="nav-link" data-scroll-target="#mixture-of-experts-moe"><span class="header-section-number">22.1.6</span> Mixture of Experts (MoE)</a></li>
  </ul></li>
  <li><a href="#the-llm-project-lifecycle" id="toc-the-llm-project-lifecycle" class="nav-link" data-scroll-target="#the-llm-project-lifecycle"><span class="header-section-number">22.2</span> The LLM Project Lifecycle</a></li>
  <li><a href="#pre-training" id="toc-pre-training" class="nav-link" data-scroll-target="#pre-training"><span class="header-section-number">22.3</span> Pre-Training</a>
  <ul class="collapse">
  <li><a href="#architectures-and-objectives" id="toc-architectures-and-objectives" class="nav-link" data-scroll-target="#architectures-and-objectives"><span class="header-section-number">22.3.1</span> Architectures and Objectives</a></li>
  <li><a href="#tokenization-byte-pair-encoding-bpe" id="toc-tokenization-byte-pair-encoding-bpe" class="nav-link" data-scroll-target="#tokenization-byte-pair-encoding-bpe"><span class="header-section-number">22.3.2</span> Tokenization: Byte-Pair Encoding (BPE)</a></li>
  <li><a href="#sec-scaling-laws" id="toc-sec-scaling-laws" class="nav-link" data-scroll-target="#sec-scaling-laws"><span class="header-section-number">22.3.3</span> Scaling Laws</a></li>
  </ul></li>
  <li><a href="#prompt-engineering-in-context-learning" id="toc-prompt-engineering-in-context-learning" class="nav-link" data-scroll-target="#prompt-engineering-in-context-learning"><span class="header-section-number">22.4</span> Prompt Engineering (In-Context Learning)</a></li>
  <li><a href="#fine-tuning" id="toc-fine-tuning" class="nav-link" data-scroll-target="#fine-tuning"><span class="header-section-number">22.5</span> Fine-Tuning</a>
  <ul class="collapse">
  <li><a href="#full-fine-tuning-and-instruction-tuning-flan" id="toc-full-fine-tuning-and-instruction-tuning-flan" class="nav-link" data-scroll-target="#full-fine-tuning-and-instruction-tuning-flan"><span class="header-section-number">22.5.1</span> Full Fine-Tuning and Instruction Tuning (FLAN)</a></li>
  <li><a href="#parameter-efficient-fine-tuning-peft" id="toc-parameter-efficient-fine-tuning-peft" class="nav-link" data-scroll-target="#parameter-efficient-fine-tuning-peft"><span class="header-section-number">22.5.2</span> Parameter-Efficient Fine-Tuning (PEFT)</a></li>
  </ul></li>
  <li><a href="#alignment" id="toc-alignment" class="nav-link" data-scroll-target="#alignment"><span class="header-section-number">22.6</span> Alignment</a>
  <ul class="collapse">
  <li><a href="#rlhf-reinforcement-learning-from-human-feedback" id="toc-rlhf-reinforcement-learning-from-human-feedback" class="nav-link" data-scroll-target="#rlhf-reinforcement-learning-from-human-feedback"><span class="header-section-number">22.6.1</span> RLHF (Reinforcement Learning from Human Feedback)</a></li>
  <li><a href="#dpo-direct-preference-optimization" id="toc-dpo-direct-preference-optimization" class="nav-link" data-scroll-target="#dpo-direct-preference-optimization"><span class="header-section-number">22.6.2</span> DPO (Direct Preference Optimization)</a></li>
  <li><a href="#rlaif-and-constitutional-ai" id="toc-rlaif-and-constitutional-ai" class="nav-link" data-scroll-target="#rlaif-and-constitutional-ai"><span class="header-section-number">22.6.3</span> RLAIF and Constitutional AI</a></li>
  </ul></li>
  <li><a href="#sec-memory-compute" id="toc-sec-memory-compute" class="nav-link" data-scroll-target="#sec-memory-compute"><span class="header-section-number">22.7</span> Memory and Compute</a>
  <ul class="collapse">
  <li><a href="#why-training-is-memory-bound" id="toc-why-training-is-memory-bound" class="nav-link" data-scroll-target="#why-training-is-memory-bound"><span class="header-section-number">22.7.1</span> Why Training Is Memory-Bound</a></li>
  <li><a href="#strategies-for-balancing-memory-and-compute" id="toc-strategies-for-balancing-memory-and-compute" class="nav-link" data-scroll-target="#strategies-for-balancing-memory-and-compute"><span class="header-section-number">22.7.2</span> Strategies for Balancing Memory and Compute</a></li>
  </ul></li>
  <li><a href="#model-compression" id="toc-model-compression" class="nav-link" data-scroll-target="#model-compression"><span class="header-section-number">22.8</span> Model Compression</a>
  <ul class="collapse">
  <li><a href="#qlora-quantized-low-rank-adaptation" id="toc-qlora-quantized-low-rank-adaptation" class="nav-link" data-scroll-target="#qlora-quantized-low-rank-adaptation"><span class="header-section-number">22.8.1</span> QLoRA: Quantized Low-Rank Adaptation</a></li>
  </ul></li>
  <li><a href="#tool-use-and-applications" id="toc-tool-use-and-applications" class="nav-link" data-scroll-target="#tool-use-and-applications"><span class="header-section-number">22.9</span> Tool Use and Applications</a></li>
  <li><a href="#ethical-concerns" id="toc-ethical-concerns" class="nav-link" data-scroll-target="#ethical-concerns"><span class="header-section-number">22.10</span> Ethical Concerns</a></li>
  <li><a href="#interview-questions" id="toc-interview-questions" class="nav-link" data-scroll-target="#interview-questions"><span class="header-section-number">22.11</span> Interview Questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Large Language Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Large Language Models (LLMs)</strong> are decoder-heavy Transformers (<a href="18-sequence-models.html#fig-transformer" class="quarto-xref">Figure&nbsp;<span>21.8</span></a>) trained on massive text corpora. The architecture’s three properties make it uniquely suited to scaling:</p>
<ul>
<li><strong>Attention to the whole input (long-range dependencies)</strong>: every self-attention layer lets each token attend to <em>all</em> other tokens, regardless of distance.</li>
<li><strong>Parallel processing</strong>: unlike RNNs, all positions in both the attention and feed-forward layers are processed simultaneously — across heads, layers, and sequence positions — fully exploiting GPU/TPU matrix-multiplication throughput.</li>
<li><strong>Scale efficiently</strong>: empirical <strong>power laws</strong> relate test loss to model size, dataset size, and compute (<a href="#sec-scaling-laws" class="quarto-xref"><span>Section 22.3.3</span></a>). Capacity scales by adding layers, heads, or widening matrices (handled across devices via <strong>model sharding</strong>); dataset size scales via larger batches over a fixed context window, processed with <strong>distributed data parallelism</strong>.</li>
</ul>
<p>This chapter covers the architectural refinements that turn the 2017 Transformer into a modern LLM, the end-to-end training/deployment lifecycle, and the major techniques for fine-tuning, alignment, and compression.</p>
<hr>
<section id="decoder-architecture-improvements" class="level2" data-number="22.1">
<h2 data-number="22.1" class="anchored" data-anchor-id="decoder-architecture-improvements"><span class="header-section-number">22.1</span> Decoder Architecture Improvements</h2>
<p>Modern decoder-only LLMs (GPT, LLaMA, Mistral, …) modify the original Transformer decoder in several ways, each targeting a specific bottleneck in training stability, context length, or inference cost.</p>
<section id="rotary-position-embeddings-rope" class="level3" data-number="22.1.1">
<h3 data-number="22.1.1" class="anchored" data-anchor-id="rotary-position-embeddings-rope"><span class="header-section-number">22.1.1</span> Rotary Position Embeddings (RoPE)</h3>
<p>Absolute positional embeddings (learned or sinusoidal, <a href="18-sequence-models.html#sec-input-representation" class="quarto-xref"><span>Section 21.2.1</span></a>) are added once at the input and generalize poorly to sequences longer than those seen in training. <strong>RoPE</strong> instead encodes position by <em>rotating</em> each pair of query/key dimensions by an angle proportional to the token’s absolute position, applied at every attention layer (not just the input):</p>
<p><span class="math display">\[f(x_m, m)_{(2i,2i+1)} = \begin{pmatrix}\cos m\theta_i &amp; -\sin m\theta_i \\ \sin m\theta_i &amp; \cos m\theta_i\end{pmatrix}\begin{pmatrix}x_m^{(2i)}\\x_m^{(2i+1)}\end{pmatrix}, \qquad \theta_i = 10000^{-2i/d}\]</span></p>
<p>i.e., a block-diagonal rotation matrix <span class="math inline">\(R_{\Theta,m}^d\)</span> applied to the query/key vector at position <span class="math inline">\(m\)</span>. The key property: <span class="math inline">\(\langle R_{\Theta,m}^d q,\ R_{\Theta,n}^d k\rangle\)</span> depends only on the <strong>relative position</strong> <span class="math inline">\(m-n\)</span>, not on <span class="math inline">\(m\)</span> and <span class="math inline">\(n\)</span> individually — the dot product naturally encodes relative distance, and the same rotation formula extrapolates (to varying degrees) beyond the training context length.</p>
</section>
<section id="pre-norm-and-rmsnorm" class="level3" data-number="22.1.2">
<h3 data-number="22.1.2" class="anchored" data-anchor-id="pre-norm-and-rmsnorm"><span class="header-section-number">22.1.2</span> Pre-Norm and RMSNorm</h3>
<p>The original Transformer applies layer normalization <em>after</em> each sub-layer’s residual sum (<strong>post-norm</strong>): <span class="math inline">\(x_{l+1} = \text{LN}\big(x_l + \text{Sublayer}(x_l)\big)\)</span>. Deep stacks trained this way are unstable, because gradients must pass through the normalization on the residual path itself. Modern LLMs use <strong>pre-norm</strong>: <span class="math inline">\(x_{l+1} = x_l + \text{Sublayer}\big(\text{LN}(x_l)\big)\)</span> — the residual stream itself is never normalized, giving an unobstructed identity path for gradients and allowing much deeper networks to train stably.</p>
<p><strong>Why LayerNorm rather than BatchNorm?</strong> Three reasons compound: (1) sequences in a batch have variable length, making per-feature statistics across the batch dimension ill-defined without heavy padding-aware masking; (2) memory constraints often force small per-device batch sizes, making batch statistics noisy; (3) in a causal language model, batch statistics computed over a batch that <em>includes future tokens</em> would leak information about the sequence the model is trying to predict.</p>
<p><strong>RMSNorm</strong> is a cheaper variant used in most modern LLMs (LLaMA, etc.) that drops the mean-centering step, only rescaling by the root-mean-square:</p>
<p><span class="math display">\[\text{RMSNorm}(x)_i = \frac{x_i}{\sqrt{\frac{1}{d}\sum_{j=1}^d x_j^2 + \epsilon}}\, \gamma_i\]</span></p>
<p>Removing mean-centering (and the corresponding learned bias/shift parameters) saves compute with negligible loss in quality.</p>
</section>
<section id="grouped-query-attention-gqa-and-kv-caching" class="level3" data-number="22.1.3">
<h3 data-number="22.1.3" class="anchored" data-anchor-id="grouped-query-attention-gqa-and-kv-caching"><span class="header-section-number">22.1.3</span> Grouped-Query Attention (GQA) and KV-Caching</h3>
<p><strong>Grouped-Query Attention</strong> reduces the memory and bandwidth cost of multi-head attention by sharing key/value projections across heads. With <span class="math inline">\(h\)</span> query heads and <span class="math inline">\(g \le h\)</span> KV-head groups (<span class="math inline">\(g \mid h\)</span>), each group of <span class="math inline">\(h/g\)</span> query heads shares a single <span class="math inline">\((K, V)\)</span> pair:</p>
<ul>
<li><span class="math inline">\(g = h\)</span>: standard <strong>Multi-Head Attention (MHA)</strong>.</li>
<li><span class="math inline">\(g = 1\)</span>: <strong>Multi-Query Attention (MQA)</strong> — all query heads share one <span class="math inline">\((K,V)\)</span> pair (maximal savings, some quality loss).</li>
<li><span class="math inline">\(1 &lt; g &lt; h\)</span>: <strong>GQA</strong> — a tunable middle ground, used in LLaMA 2/3, Mistral, etc.</li>
</ul>
<p><strong>KV-caching</strong> exploits the fact that, during autoregressive generation, the keys and values for all <em>previous</em> tokens never change. Instead of recomputing <span class="math inline">\(K, V\)</span> for the whole sequence at every generation step, each attention layer caches the <span class="math inline">\((K,V)\)</span> pairs from prior steps and only computes them for the newly generated token, concatenating with the cache:</p>
<p><span class="math display">\[\boxed{\text{KV-cache size} = 2 \times L \times g \times d_h \times T \times B \times (\text{bytes/value})}\]</span></p>
<p>for <span class="math inline">\(L\)</span> layers, <span class="math inline">\(g\)</span> KV-head groups, head dimension <span class="math inline">\(d_h\)</span>, sequence length <span class="math inline">\(T\)</span>, batch size <span class="math inline">\(B\)</span>, and the factor <span class="math inline">\(2\)</span> for storing both <span class="math inline">\(K\)</span> and <span class="math inline">\(V\)</span>. This cache — not the model weights — is often the dominant memory cost at long context lengths and large batch sizes, which is precisely why GQA/MQA (reducing <span class="math inline">\(g\)</span>) are so impactful for inference serving.</p>
</section>
<section id="swiglu-and-gated-activations" class="level3" data-number="22.1.4">
<h3 data-number="22.1.4" class="anchored" data-anchor-id="swiglu-and-gated-activations"><span class="header-section-number">22.1.4</span> SwiGLU and Gated Activations</h3>
<p>The original Transformer’s FFN uses ReLU: <span class="math inline">\(\text{FFN}(x) = \max(0, xW_1 + b_1)W_2 + b_2\)</span>. Modern LLMs instead use <strong>Gated Linear Unit (GLU)</strong> variants, which compute two linear projections of the input and use one (passed through a nonlinearity) to <em>gate</em> the other element-wise:</p>
<p><span class="math display">\[\text{GLU}(x,W,V,b,c) = \sigma(xW+b) \otimes (xV+c)\]</span> <span class="math display">\[\text{ReGLU} = \max(0,xW+b)\otimes(xV+c), \quad \text{GEGLU} = \text{GELU}(xW+b)\otimes(xV+c)\]</span> <span class="math display">\[\boxed{\text{SwiGLU}(x,W,V,b,c,\beta) = \text{Swish}_\beta(xW+b)\otimes(xV+c)}\]</span></p>
<p>where <span class="math inline">\(\text{Swish}_\beta(x) = x \cdot \sigma(\beta x)\)</span>. SwiGLU (used in LLaMA, PaLM) replaces the single up-projection with two projections (one gating the other), then down-projects as usual — strictly speaking these are not “activation functions” in the classical sense since they mix two linear streams, but they consistently improve quality at the same parameter budget at the cost of one extra weight matrix in the FFN.</p>
</section>
<section id="flashattention" class="level3" data-number="22.1.5">
<h3 data-number="22.1.5" class="anchored" data-anchor-id="flashattention"><span class="header-section-number">22.1.5</span> FlashAttention</h3>
<p>Profiling attention on a GPU reveals that most of the wall-clock time is spent not on the matrix multiplications (<code>MatMul</code>, compute-bound) but on <strong>memory-bound</strong> elementwise/reduction operations — masking, softmax, dropout — each of which reads and writes the full <span class="math inline">\(n \times n\)</span> attention matrix to/from slow GPU global memory (HBM).</p>
<div id="fig-flash-attention" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-flash-attention-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/flash_attention_latency.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:45.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-flash-attention-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.1: Latency breakdown of standard PyTorch attention vs.&nbsp;FlashAttention on GPT-2: most time is spent on memory-bound operations (mask, softmax, dropout) rather than the matrix multiplications; FlashAttention fuses all of these into a single kernel.
</figcaption>
</figure>
</div>
<p><strong>FlashAttention</strong> restructures the computation to avoid ever materializing the full <span class="math inline">\(n\times n\)</span> attention matrix in HBM. It processes <span class="math inline">\(Q, K, V\)</span> in <strong>blocks</strong> that fit in fast on-chip SRAM, using the fact that softmax can be computed incrementally via a running renormalization across blocks (online softmax). The result is mathematically identical attention output, computed in a single fused kernel with <span class="math inline">\(O(n)\)</span> rather than <span class="math inline">\(O(n^2)\)</span> memory traffic — turning a memory-bound operation into a compute-bound one.</p>
</section>
<section id="mixture-of-experts-moe" class="level3" data-number="22.1.6">
<h3 data-number="22.1.6" class="anchored" data-anchor-id="mixture-of-experts-moe"><span class="header-section-number">22.1.6</span> Mixture of Experts (MoE)</h3>
<p>MoE trades <strong>more parameters (memory)</strong> for <strong>less compute (FLOPs)</strong> per token: the dense FFN in each Transformer block is replaced by many parallel FFN “experts,” of which only a small subset is activated per token.</p>
<div id="fig-moe" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-moe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/mixture_of_experts.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.2: A Mixture-of-Experts layer: each token’s representation is routed (via a learned router) to a small subset of FFN “experts,” whose outputs are combined and added back to the residual stream.
</figcaption>
</figure>
</div>
<p>An MoE layer consists of a <strong>router</strong> and <span class="math inline">\(N\)</span> expert FFNs <span class="math inline">\(E_1, \dots, E_N\)</span>. The router computes an (unnormalized) importance score per expert via a linear projection <span class="math inline">\(H(x) = W_r x\)</span>, then a softmax:</p>
<p><span class="math display">\[p_i(x) = \frac{e^{H(x)_i}}{\sum_{j=1}^N e^{H(x)_j}}\]</span></p>
<p>The layer’s output is a weighted sum of the <strong>top-<span class="math inline">\(K\)</span></strong> experts’ outputs (sparse routing — Mixtral uses <span class="math inline">\(K=2\)</span>; the Switch Transformer uses <span class="math inline">\(K=1\)</span> over the full set <span class="math inline">\(\mathcal{T}\)</span>):</p>
<p><span class="math display">\[\boxed{y = \sum_{i \in \mathcal{T}} p_i(x) \cdot E_i(x)}\]</span></p>
<p><strong>Load balancing</strong>: the compute speedup from sparsity only materializes if tokens are spread roughly evenly across experts. The Switch Transformer’s <strong>load-balancing loss</strong> penalizes uneven routing:</p>
<p><span class="math display">\[\mathcal{L}_B = N \sum_{i=1}^N f_i \cdot P_i\]</span></p>
<p>where <span class="math inline">\(f_i\)</span> is the fraction of tokens in the batch routed to expert <span class="math inline">\(i\)</span>, and <span class="math inline">\(P_i\)</span> is the router’s average probability mass on expert <span class="math inline">\(i\)</span> — minimized (at value 1) when both are uniform over experts.</p>
<p><strong>Router stability</strong>: large router logits are sensitive to low-precision (e.g., bfloat16) rounding errors because of the softmax’s exponential — small perturbations to large logits cause large probability swings, and hence training instability. The <strong>router z-loss</strong> penalizes large logit magnitudes directly:</p>
<p><span class="math display">\[\mathcal{L}_Z(x) = \frac{1}{B}\sum_{i=1}^B \left(\log\sum_{j=1}^N e^{x_j^{(i)}}\right)^2\]</span></p>
<p>The total Switch Transformer loss combines the language-modeling cross-entropy with both auxiliary losses:</p>
<p><span class="math display">\[\mathcal{L}_{\text{tot}} = \mathcal{L}_{\text{CE}} + c_B \mathcal{L}_B + c_Z \mathcal{L}_Z\]</span></p>
<p><strong>Interview Insight</strong>: MoE decouples <em>parameter count</em> from <em>FLOPs per token</em> — a model can have, say, 8x the parameters of a dense model while only activating 2 experts per token (roughly 2x the FFN FLOPs). This is why MoE models report both a “total” and an “active” parameter count, and why they are primarily a win when <strong>memory/bandwidth is cheaper than compute</strong> (e.g., serving at scale with enough VRAM to hold all experts).</p>
<hr>
</section>
</section>
<section id="the-llm-project-lifecycle" class="level2" data-number="22.2">
<h2 data-number="22.2" class="anchored" data-anchor-id="the-llm-project-lifecycle"><span class="header-section-number">22.2</span> The LLM Project Lifecycle</h2>
<div id="fig-lifecycle" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lifecycle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/project_lifecycle.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lifecycle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.3: The LLM project lifecycle: scope the use case, select a base model (or pretrain one), adapt and align it (prompt engineering, fine-tuning, alignment with human feedback), evaluate, then optimize, deploy, and integrate into applications.
</figcaption>
</figure>
</div>
<p>The remaining sections of this chapter follow this lifecycle: pre-training (architecture choices, tokenization, scaling laws), prompt engineering, fine-tuning (full and parameter-efficient), alignment (RLHF/RLAIF/DPO), and finally the systems concerns — memory/compute requirements, compression, and tool-augmented deployment.</p>
<hr>
</section>
<section id="pre-training" class="level2" data-number="22.3">
<h2 data-number="22.3" class="anchored" data-anchor-id="pre-training"><span class="header-section-number">22.3</span> Pre-Training</h2>
<section id="architectures-and-objectives" class="level3" data-number="22.3.1">
<h3 data-number="22.3.1" class="anchored" data-anchor-id="architectures-and-objectives"><span class="header-section-number">22.3.1</span> Architectures and Objectives</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Encoder-Only</strong></th>
<th><strong>Encoder-Decoder</strong></th>
<th><strong>Decoder-Only</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Task examples</strong></td>
<td>Sentence/token classification</td>
<td>Summarization, translation, QA</td>
<td>Open-ended generation, chat</td>
</tr>
<tr class="even">
<td><strong>Model examples</strong></td>
<td>BERT, RoBERTa</td>
<td>BART, T5</td>
<td>GPT, LLaMA, Mistral</td>
</tr>
<tr class="odd">
<td><strong>Input/output size</strong></td>
<td>Same</td>
<td>Different</td>
<td>Different</td>
</tr>
<tr class="even">
<td><strong>Pre-training objective</strong></td>
<td>Masked Language Modeling (MLM)</td>
<td>Span corruption (T5)</td>
<td>Causal Language Modeling (next-token prediction)</td>
</tr>
</tbody>
</table>
<p>Pre-training jointly learns the <strong>token embedding table</strong>, the <strong>positional embeddings</strong> (learned, or fixed sinusoidal/RoPE), and all Transformer weights, by maximizing likelihood under the chosen objective over a massive unlabeled text corpus.</p>
</section>
<section id="tokenization-byte-pair-encoding-bpe" class="level3" data-number="22.3.2">
<h3 data-number="22.3.2" class="anchored" data-anchor-id="tokenization-byte-pair-encoding-bpe"><span class="header-section-number">22.3.2</span> Tokenization: Byte-Pair Encoding (BPE)</h3>
<p>LLMs operate on <strong>subword tokens</strong> — a middle ground between characters (small vocabulary, very long sequences) and whole words (huge vocabulary, no way to handle unseen words). <strong>BPE</strong> constructs a subword vocabulary by:</p>
<ol type="1">
<li>Start with a base vocabulary of individual characters (plus an end-of-word marker).</li>
<li>Count the frequency of every adjacent symbol pair across the corpus.</li>
<li>Merge the most frequent pair into a new symbol, add it to the vocabulary.</li>
<li>Repeat steps 2–3 until the target vocabulary size is reached.</li>
</ol>
<p>The result is a vocabulary where common words are single tokens, while rare words decompose into frequent subword pieces — guaranteeing any input string can be tokenized (down to individual bytes/characters in the worst case).</p>
</section>
<section id="sec-scaling-laws" class="level3" data-number="22.3.3">
<h3 data-number="22.3.3" class="anchored" data-anchor-id="sec-scaling-laws"><span class="header-section-number">22.3.3</span> Scaling Laws</h3>
<p><strong>Kaplan et al.&nbsp;(2020), “Scaling Laws for Neural Language Models”</strong> showed that test loss follows a <strong>power law</strong> with respect to model size <span class="math inline">\(N\)</span>, dataset size <span class="math inline">\(D\)</span>, and compute <span class="math inline">\(C\)</span> — each fit independently while holding the others sufficiently large:</p>
<p><span class="math display">\[L(N) \propto N^{-\alpha_N}, \qquad L(D) \propto D^{-\alpha_D}, \qquad L(C) \propto C^{-\alpha_C}\]</span></p>
<div id="fig-scaling-laws" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scaling-laws-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/scaling_laws.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scaling-laws-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.4: Test loss vs.&nbsp;compute budget follows a power law (straight line on a log-log plot) across many orders of magnitude — the trade-off between dataset size and model size, for a fixed compute budget, is the central question scaling laws address.
</figcaption>
</figure>
</div>
<p><strong>Hoffmann et al.&nbsp;(2022), “Training Compute-Optimal Large Language Models” (Chinchilla)</strong> refined this into a practical prescription: for a <em>fixed compute budget</em>, the loss-minimizing allocation between model size and data size is roughly</p>
<p><span class="math display">\[\boxed{\#\text{tokens} \approx 20 \times \#\text{parameters}}\]</span></p>
<p>Many earlier large models (e.g., GPT-3) were significantly <strong>under-trained on data</strong> relative to their parameter count — a smaller model trained on proportionally more tokens (Chinchilla, 70B params / 1.4T tokens) matched or exceeded their performance at the same compute cost.</p>
<hr>
</section>
</section>
<section id="prompt-engineering-in-context-learning" class="level2" data-number="22.4">
<h2 data-number="22.4" class="anchored" data-anchor-id="prompt-engineering-in-context-learning"><span class="header-section-number">22.4</span> Prompt Engineering (In-Context Learning)</h2>
<p>Prompt engineering adapts model behavior <strong>at inference time</strong>, without updating any weights, by modifying the input prompt:</p>
<ul>
<li><strong>Zero-shot inference</strong>: the prompt contains only an instruction/question, relying entirely on knowledge acquired during pre-training.</li>
<li><strong>Few-shot inference</strong>: the prompt is prefixed with a small number of input-output example pairs demonstrating the task, before the actual query.</li>
</ul>
<p>Few-shot prompting has limits: smaller models often fail to generalize from in-context examples the way larger models do, and every example consumes context-window tokens that could otherwise be used for the actual task input (or KV-cache budget at inference).</p>
<hr>
</section>
<section id="fine-tuning" class="level2" data-number="22.5">
<h2 data-number="22.5" class="anchored" data-anchor-id="fine-tuning"><span class="header-section-number">22.5</span> Fine-Tuning</h2>
<section id="full-fine-tuning-and-instruction-tuning-flan" class="level3" data-number="22.5.1">
<h3 data-number="22.5.1" class="anchored" data-anchor-id="full-fine-tuning-and-instruction-tuning-flan"><span class="header-section-number">22.5.1</span> Full Fine-Tuning and Instruction Tuning (FLAN)</h3>
<p><strong>Full fine-tuning (FFT)</strong> updates <em>all</em> model parameters on a downstream dataset — effective, but expensive (requires storing optimizer states for every parameter, <a href="#sec-memory-compute" class="quarto-xref"><span>Section 22.7</span></a>) and prone to <strong>catastrophic forgetting</strong> of capabilities not represented in the fine-tuning data.</p>
<p><strong>FLAN (Fine-tuned LAnguage Net)</strong> mitigates this with <strong>instruction fine-tuning</strong>: rather than fine-tuning on a single task, the model is fine-tuned on a large mixture of tasks, each reformatted as natural-language instructions, optionally with:</p>
<ul>
<li>worked <strong>exemplars</strong> (few-shot examples within the fine-tuning example itself), and</li>
<li><strong>chain-of-thought</strong> rationales.</li>
</ul>
<div id="fig-flan" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-flan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/finetuning_tasks.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-flan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.5: FLAN-style instruction fine-tuning aggregates hundreds of datasets across many task clusters (commonsense reasoning, QA, translation, sentiment, NLI, chain-of-thought reasoning, …), reformatted as natural-language instructions, with a disjoint set of held-out tasks (MMLU, BBH, TyDiQA, MGSM) used for evaluation.
</figcaption>
</figure>
</div>
<p>Training across this broad task mixture, rather than a single narrow task, is what prevents the catastrophic forgetting that plagues single-task FFT — the model retains general instruction-following ability while gaining task-specific competence.</p>
</section>
<section id="parameter-efficient-fine-tuning-peft" class="level3" data-number="22.5.2">
<h3 data-number="22.5.2" class="anchored" data-anchor-id="parameter-efficient-fine-tuning-peft"><span class="header-section-number">22.5.2</span> Parameter-Efficient Fine-Tuning (PEFT)</h3>
<p>PEFT methods freeze most (or all) of the pre-trained weights and train a small number of additional/selected parameters — drastically reducing the optimizer-state memory of fine-tuning (<a href="#sec-memory-compute" class="quarto-xref"><span>Section 22.7</span></a>) while approaching FFT quality.</p>
<p><strong>Selective methods</strong>: fine-tune only a chosen subset of existing parameters (e.g., only bias terms, or only the last few layers), leaving the rest frozen.</p>
<p><strong>Reparametrization — LoRA (Low-Rank Adaptation)</strong>: freeze the pre-trained weight matrix <span class="math inline">\(W_0 \in \mathbb{R}^{d\times k}\)</span> and add a low-rank update <span class="math inline">\(\Delta W = BA\)</span>, where <span class="math inline">\(B \in \mathbb{R}^{d\times r}\)</span>, <span class="math inline">\(A \in \mathbb{R}^{r\times k}\)</span>, and <span class="math inline">\(r \ll \min(d,k)\)</span>:</p>
<p><span class="math display">\[\boxed{h = W_0 x + \Delta W x = W_0 x + BA x}\]</span></p>
<p>Only <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are trained (typically applied to the attention <span class="math inline">\(W_Q\)</span> and <span class="math inline">\(W_V\)</span> matrices); <span class="math inline">\(B\)</span> is initialized to zero so <span class="math inline">\(\Delta W = 0\)</span> at the start of training. The number of trainable parameters drops from <span class="math inline">\(d\times k\)</span> to <span class="math inline">\(r(d+k)\)</span> — for <span class="math inline">\(r \ll d,k\)</span>, a reduction of orders of magnitude.</p>
<div id="fig-lora" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lora-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/lora_adaptation.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lora-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.6: LoRA: a small rank-<span class="math inline">\(r\)</span> decomposition <span class="math inline">\(BA\)</span> is added to a frozen weight matrix; different tasks can train different <span class="math inline">\((A,B)\)</span> pairs against the same frozen base model.
</figcaption>
</figure>
</div>
<p><strong>Interview Insight</strong>: Because <span class="math inline">\(\Delta W\)</span> is just an additive matrix, LoRA adapters for different tasks can be <strong>swapped at inference time</strong> without reloading the (much larger) base model — train one adapter per task/customer and merge or hot-swap <span class="math inline">\(BA\)</span> as needed. This is the basis for multi-tenant LLM serving with per-customer fine-tuning.</p>
<p><strong>Additive methods — soft prompts</strong>: instead of modifying any weights, prepend a small number (typically 20–100) of <strong>learnable continuous vectors</strong> — the same dimensionality as token embeddings — to the input sequence. Only these vectors are trained; the entire model is frozen.</p>
<div id="fig-soft-prompts" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-soft-prompts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/soft_prompts.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-soft-prompts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.7: Prompt tuning prepends a “soft prompt” — a sequence of learnable embedding vectors (yellow) — to the input token embeddings; gradients flow only into these vectors, with the entire model frozen.
</figcaption>
</figure>
</div>
<p>As with LoRA adapters, different soft prompts can be swapped per task at inference time against a single shared frozen model.</p>
<hr>
</section>
</section>
<section id="alignment" class="level2" data-number="22.6">
<h2 data-number="22.6" class="anchored" data-anchor-id="alignment"><span class="header-section-number">22.6</span> Alignment</h2>
<p>Pre-training (next-token prediction on web text) and instruction fine-tuning produce a model that can <em>follow</em> instructions, but not necessarily one whose outputs reflect human preferences for <strong>Helpfulness, Honesty, and Harmlessness (HHH)</strong>. <strong>Alignment</strong> further optimizes the model’s outputs toward these values using human (or AI) preference signals.</p>
<section id="rlhf-reinforcement-learning-from-human-feedback" class="level3" data-number="22.6.1">
<h3 data-number="22.6.1" class="anchored" data-anchor-id="rlhf-reinforcement-learning-from-human-feedback"><span class="header-section-number">22.6.1</span> RLHF (Reinforcement Learning from Human Feedback)</h3>
<p>The standard RLHF pipeline has three phases:</p>
<ol type="1">
<li><strong>Supervised fine-tuning (SFT)</strong>: instruction-tune a pre-trained model on high-quality demonstrations (this is the starting policy).</li>
<li><strong>Reward modeling</strong>: humans rank multiple completions for the same prompt; a <strong>reward model</strong> <span class="math inline">\(r_\theta\)</span> is trained to predict a scalar score consistent with these rankings.</li>
</ol>
<div id="fig-reward-model" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reward-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/reward_model_training.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reward-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.8: Reward model training: an SFT model generates multiple completions per prompt, humans rank them, and a reward model is trained on (completion, reward) pairs derived from these rankings.
</figcaption>
</figure>
</div>
<ol start="3" type="1">
<li><strong>RL optimization (PPO)</strong>: a copy of the SFT model — the <strong>tuned policy</strong> <span class="math inline">\(\pi_{\text{PPO}}\)</span> — is fine-tuned with <strong>Proximal Policy Optimization</strong> to maximize the reward model’s score, while a <strong>KL-divergence penalty</strong> keeps <span class="math inline">\(\pi_{\text{PPO}}\)</span> close to the frozen reference policy <span class="math inline">\(\pi_{\text{base}}\)</span> (preventing reward over-optimization / “reward hacking” and degenerate outputs):</li>
</ol>
<p><span class="math display">\[\text{objective} = r_\theta(x,y) - \lambda_{\text{KL}}\, D_{\text{KL}}\big(\pi_{\text{PPO}}(y\mid x)\,\|\,\pi_{\text{base}}(y\mid x)\big)\]</span></p>
<div id="fig-rlhf" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rlhf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/rlhf_pipeline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rlhf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.9: The RLHF/PPO loop: the tuned policy generates completions, the reward model scores them, and a PPO update increases the policy’s parameters in the direction of higher reward while a KL term penalizes drift from the frozen base policy.
</figcaption>
</figure>
</div>
</section>
<section id="dpo-direct-preference-optimization" class="level3" data-number="22.6.2">
<h3 data-number="22.6.2" class="anchored" data-anchor-id="dpo-direct-preference-optimization"><span class="header-section-number">22.6.2</span> DPO (Direct Preference Optimization)</h3>
<p>PPO requires training and serving a separate reward model and is notoriously fiddly (RL training instability, extra forward passes). <strong>DPO</strong> shows that the RLHF objective has a closed-form optimal policy in terms of the reward function, allowing the reward model to be eliminated entirely — preference data is used to directly optimize the policy via a classification-style loss:</p>
<p><span class="math display">\[\boxed{\mathcal{L}_{\text{DPO}}(\pi_\theta;\pi_{\text{ref}}) = -\mathbb{E}_{(x,y_w,y_l)\sim\mathcal{D}}\left[\log\sigma\left(\beta\log\frac{\pi_\theta(y_w\mid x)}{\pi_{\text{ref}}(y_w\mid x)} - \beta\log\frac{\pi_\theta(y_l\mid x)}{\pi_{\text{ref}}(y_l\mid x)}\right)\right]}\]</span></p>
<div id="fig-dpo" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dpo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/loss_dpo.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dpo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.10: The DPO loss: a logistic loss over the difference in log-probability ratios (policy vs.&nbsp;reference) between the preferred (<span class="math inline">\(y_w\)</span>, “winning”) and dispreferred (<span class="math inline">\(y_l\)</span>, “losing”) completions, scaled by <span class="math inline">\(\beta\)</span>.
</figcaption>
</figure>
</div>
<p>DPO pipeline: (1) obtain a reference policy <span class="math inline">\(\pi_{\text{ref}}\)</span> by SFT on high-quality data for the target domain; (2) sample completion pairs <span class="math inline">\(y_1, y_2 \sim \pi_{\text{ref}}(\cdot\mid x)\)</span> and collect human preference labels <span class="math inline">\((y_w, y_l)\)</span>; (3) directly minimize <span class="math inline">\(\mathcal{L}_{\text{DPO}}\)</span> — increasing the policy’s relative log-probability of <span class="math inline">\(y_w\)</span> over <span class="math inline">\(y_l\)</span>, compared to the reference, modulated by <span class="math inline">\(\beta\)</span> (which plays the role of the RLHF KL coefficient).</p>
<p><strong>Interview Insight</strong>: DPO is mathematically equivalent to RLHF’s PPO objective under a Bradley-Terry preference model, but reformulated so the reward model and the policy are <em>the same object</em> — the policy’s implicit reward is <span class="math inline">\(\beta\log\frac{\pi_\theta(y\mid x)}{\pi_{\text{ref}}(y\mid x)}\)</span>. This avoids RL training entirely (it’s a supervised classification loss), at the cost of requiring the preference dataset to be collected upfront from <span class="math inline">\(\pi_{\text{ref}}\)</span> rather than online from the policy being trained.</p>
</section>
<section id="rlaif-and-constitutional-ai" class="level3" data-number="22.6.3">
<h3 data-number="22.6.3" class="anchored" data-anchor-id="rlaif-and-constitutional-ai"><span class="header-section-number">22.6.3</span> RLAIF and Constitutional AI</h3>
<p>Human preference labeling is expensive and slow to scale. <strong>RLAIF (RL from AI Feedback)</strong> replaces human labels with AI-generated ones. <strong>Constitutional AI</strong> is the canonical RLAIF method, using a small written “constitution” (a set of principles, e.g., ~16 sentences) instead of per-example human labels:</p>
<ol type="1">
<li><strong>Generate a “helpful” model’s revisions</strong>: prompt the model with harmful prompts to elicit a (potentially harmful) response, then have the <em>same model</em> critique its own response by referencing the constitution, and produce a revision. Repeat for <span class="math inline">\(N\)</span> iterations.</li>
</ol>
<div id="fig-constitutional-ai" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-constitutional-ai-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/constitutional_ai_helpful_model.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-constitutional-ai-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.11: Constitutional AI’s helpfulness-revision loop: a harmful prompt elicits a harmful output, the model critiques it against the constitution, and produces a revised, less-harmful output — repeated <span class="math inline">\(N\)</span> times.
</figcaption>
</figure>
</div>
<ol start="2" type="1">
<li><strong>Train a preference/reward model on AI-generated comparisons</strong>: a separate “feedback model,” given the constitution, scores pairs of (harmful, harmless) responses to build a harmlessness preference dataset, on which a preference/reward model is trained.</li>
</ol>
<div id="fig-rlaif" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rlaif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/nlp/rlaif_pipeline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rlaif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.12: The RLAIF pipeline: a response model generates candidate responses, a feedback model (guided by the constitution) labels preferences over them to build a harmlessness dataset, a preference model is trained on this dataset, and RL training produces the final RLAIF assistant.
</figcaption>
</figure>
</div>
<ol start="3" type="1">
<li><strong>RL optimization</strong>: PPO uses this AI-trained reward model exactly as in RLHF, producing the final aligned model.</li>
</ol>
<hr>
</section>
</section>
<section id="sec-memory-compute" class="level2" data-number="22.7">
<h2 data-number="22.7" class="anchored" data-anchor-id="sec-memory-compute"><span class="header-section-number">22.7</span> Memory and Compute</h2>
<section id="why-training-is-memory-bound" class="level3" data-number="22.7.1">
<h3 data-number="22.7.1" class="anchored" data-anchor-id="why-training-is-memory-bound"><span class="header-section-number">22.7.1</span> Why Training Is Memory-Bound</h3>
<p>GPU <strong>computation</strong> (matmuls via tensor/CUDA cores) and <strong>memory</strong> (VRAM holding weights, activations, gradients, optimizer states) are distinct resources, and LLM training is dominated by the latter. To train with the (full-precision, Adam) setup, each parameter requires:</p>
<p><span class="math display">\[\underbrace{4\text{ bytes}}_{\text{weights (fp32)}} + \underbrace{4\text{ bytes}}_{\text{gradients (fp32)}} + \underbrace{8\text{ bytes}}_{\text{Adam } m} + \underbrace{8\text{ bytes}}_{\text{Adam } v}\]</span></p>
<p><span class="math display">\[\boxed{\text{Memory} \approx 24 \times \#\text{params (bytes)}}\]</span></p>
<p>plus activation memory (up to roughly <span class="math inline">\(2\times\)</span> the parameter count, depending on batch size, sequence length, and whether gradient checkpointing is used). Meanwhile, the <strong>compute</strong> for training scales as <span class="math inline">\(\#\text{operations} \approx \#\text{params}\)</span> per token (assuming context length <span class="math inline">\(L \ll d_{\text{model}}\)</span>, since linear layers scale as <span class="math inline">\(O(L\cdot d^2 \cdot B)\)</span> and attention as <span class="math inline">\(O(L^2\cdot d\cdot B)\)</span> — the linear term dominates for typical <span class="math inline">\(L, d\)</span>). Memory scales with a much larger constant (~24x) than compute (~1x) per parameter — hence LLM training is <strong>memory-bound</strong>, not compute-bound.</p>
</section>
<section id="strategies-for-balancing-memory-and-compute" class="level3" data-number="22.7.2">
<h3 data-number="22.7.2" class="anchored" data-anchor-id="strategies-for-balancing-memory-and-compute"><span class="header-section-number">22.7.2</span> Strategies for Balancing Memory and Compute</h3>
<ul>
<li><strong>Mixed-precision training</strong>: most operations run in fp16/bfloat16 (halving memory for weights and activations, and exploiting tensor cores for faster matmuls), while gradient updates and loss scaling remain in fp32 for numerical stability.</li>
<li><strong>Gradient checkpointing</strong>: only a subset of activations is stored during the forward pass; the rest are recomputed during the backward pass. Trades increased backward-pass compute for substantially reduced activation memory.</li>
<li><strong>Model parallelism (distributed training)</strong>: shard the model itself across multiple GPUs, each holding and computing only part of the network — necessary once a model no longer fits on a single device regardless of batch size.</li>
<li><strong>Speculative decoding</strong> (inference): a small, fast “draft” model proposes several tokens at once; the large “main” model verifies (or corrects) them in a single forward pass over all proposed tokens. Shifts work from many sequential large-model steps to one large-model step plus several small-model steps.</li>
<li><strong>Knowledge distillation</strong>: train a smaller model to match a larger one’s output distribution — a model-compression technique covered next.</li>
</ul>
<p><strong>Key hyperparameters driving memory/compute</strong>: batch size, embedding dimension, FFN hidden size, and number of attention heads/layers — all of which scale both the parameter count and the activation memory.</p>
<hr>
</section>
</section>
<section id="model-compression" class="level2" data-number="22.8">
<h2 data-number="22.8" class="anchored" data-anchor-id="model-compression"><span class="header-section-number">22.8</span> Model Compression</h2>
<ul>
<li><strong>Knowledge distillation</strong>: freeze a large <strong>teacher</strong> model; train a smaller <strong>student</strong> model to match the teacher’s <em>output distribution</em> (not just its hard labels) using a softened softmax (temperature <span class="math inline">\(T&gt;1\)</span>) — these “soft labels” carry more information per example than one-hot targets.</li>
<li><strong>Quantization</strong>: store weights/activations in lower-precision formats (fp16, bfloat16, int8, or 4-bit) instead of fp32, directly reducing memory footprint (and, with appropriate kernels, increasing throughput).</li>
<li><strong>Pruning</strong>: zero out weights with magnitude near zero, then recover quality via full re-training or PEFT (e.g., LoRA) on the pruned model.</li>
</ul>
<section id="qlora-quantized-low-rank-adaptation" class="level3" data-number="22.8.1">
<h3 data-number="22.8.1" class="anchored" data-anchor-id="qlora-quantized-low-rank-adaptation"><span class="header-section-number">22.8.1</span> QLoRA: Quantized Low-Rank Adaptation</h3>
<p>LoRA reduces <em>trainable</em> parameters but still requires the full-precision base model resident in VRAM — prohibitive for multi-billion-parameter models on a single GPU. <strong>QLoRA</strong> combines LoRA with <strong>4-bit quantization of the frozen base model</strong>: gradients are backpropagated through a frozen 4-bit (NF4) base model into full-precision LoRA adapters, preserving near-16-bit fine-tuning quality. Two effects drive the memory savings: (1) the base weights — ~99.9% of parameters — are stored in 4-bit NF4, a ~4x reduction vs.&nbsp;16-bit; (2) since the base model is frozen, gradients and Adam states (the most memory-hungry components) are only needed for the tiny LoRA adapter matrices.</p>
<p><strong>Illustrative VRAM comparison for fine-tuning a 65B-parameter model:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Full 16-bit FT</th>
<th>LoRA</th>
<th>QLoRA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Base weights</td>
<td>130 GB (16-bit)</td>
<td>130 GB (16-bit)</td>
<td>~33 GB (4-bit NF4)</td>
</tr>
<tr class="even">
<td>Gradients (full model, 16-bit)</td>
<td>130 GB</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Adam states (full model, 32-bit)</td>
<td>520 GB</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>LoRA adapter weights + grads + Adam (~0.1% of params)</td>
<td>—</td>
<td>~1–2 GB</td>
<td>~1–2 GB</td>
</tr>
<tr class="odd">
<td>Activations &amp; misc. buffers</td>
<td>included above</td>
<td>~8–10 GB</td>
<td>~3–5 GB</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>≈ 780 GB</strong></td>
<td><strong>≈ 140 GB</strong></td>
<td><strong>≈ 35–40 GB</strong></td>
</tr>
</tbody>
</table>
<p>(Figures are approximate and illustrative.) Going from full fine-tuning to LoRA removes the gradient and optimizer-state memory for the base model (~650 GB saved) by training only the small adapters; going from LoRA to QLoRA further shrinks the dominant remaining cost — the frozen base weights — via 4-bit quantization. The net effect: a 65B model becomes fine-tunable on a <strong>single consumer/prosumer GPU</strong> (e.g., a 48 GB card) rather than requiring a multi-node cluster — a major driver of open-source LLM fine-tuning accessibility.</p>
<hr>
</section>
</section>
<section id="tool-use-and-applications" class="level2" data-number="22.9">
<h2 data-number="22.9" class="anchored" data-anchor-id="tool-use-and-applications"><span class="header-section-number">22.9</span> Tool Use and Applications</h2>
<p>Several frameworks extend an LLM’s capabilities by interleaving generation with external tool calls:</p>
<ul>
<li><strong>Retrieval-Augmented Generation (RAG)</strong>: given a prompt, retrieve relevant documents from an external database (e.g., via embedding similarity search, <a href="20-text-embeddings-evaluation.html#sec-text-embeddings" class="quarto-xref"><span>Section 23.1</span></a>) and prepend them to the prompt before the LLM generates its answer — grounding generation in up-to-date or proprietary information without retraining.</li>
<li><strong>Program-Aided Language Models (PAL)</strong>: the model generates code (e.g., Python) representing the reasoning/computation needed to answer the prompt; the code is executed by an interpreter, and the result is fed back to the model to produce the final answer — offloading arithmetic/logical steps the model itself performs unreliably.</li>
<li><strong>ReAct (Reasoning and Acting)</strong>: the model interleaves free-text <em>reasoning traces</em> with discrete <em>actions</em> (e.g., <code>Search[entity]</code>, <code>Lookup[string]</code>, <code>Finish[answer]</code>), observing the result of each action before deciding the next reasoning step or action — repeating until a final answer is produced.</li>
</ul>
<hr>
</section>
<section id="ethical-concerns" class="level2" data-number="22.10">
<h2 data-number="22.10" class="anchored" data-anchor-id="ethical-concerns"><span class="header-section-number">22.10</span> Ethical Concerns</h2>
<ul>
<li><strong>Toxicity</strong>: mitigated through careful training-data curation, dedicated guardrail/classifier models that filter generated text, and diverse human annotator pools (to avoid encoding a narrow set of cultural norms as “safe”).</li>
<li><strong>Hallucination</strong>: mitigated by grounding generation in independent, verifiable sources (e.g., RAG) rather than relying solely on parametric knowledge.</li>
<li><strong>Intellectual property / privacy</strong>: addressed via <strong>machine unlearning</strong> (removing the influence of specific training examples post-hoc) and filtering/blocking approaches at both training-data and generation time.</li>
</ul>
<hr>
</section>
<section id="interview-questions" class="level2" data-number="22.11">
<h2 data-number="22.11" class="anchored" data-anchor-id="interview-questions"><span class="header-section-number">22.11</span> Interview Questions</h2>
<p><strong>Q: Why does RoPE generalize better to longer sequences than learned absolute positional embeddings?</strong></p>
<p>Absolute positional embeddings assign a distinct, independently-learned vector to each position index — positions beyond the maximum seen in training have no learned embedding at all. RoPE instead encodes position as a rotation applied to query/key vectors, and the attention dot product <span class="math inline">\(\langle R_m q, R_n k\rangle\)</span> depends only on the <em>relative</em> offset <span class="math inline">\(m-n\)</span> via the rotation’s algebraic structure — a property that holds for any <span class="math inline">\(m,n\)</span>, including offsets larger than those seen during training, giving at least some degree of length extrapolation “for free.”</p>
<hr>
<p><strong>Q: What’s the difference between MHA, MQA, and GQA, and why does it matter for serving?</strong></p>
<p>All three differ only in how many distinct <span class="math inline">\((K,V)\)</span> projection pairs exist relative to the number of query heads <span class="math inline">\(h\)</span>: MHA uses <span class="math inline">\(h\)</span> (one per head), MQA uses <span class="math inline">\(1\)</span> (all heads share), and GQA uses <span class="math inline">\(g\)</span> with <span class="math inline">\(1 &lt; g &lt; h\)</span> (groups of heads share). This directly scales the <strong>KV-cache size</strong> (the dominant inference memory cost at long contexts/large batches) by a factor of <span class="math inline">\(h/g\)</span>. MQA/GQA trade a small amount of quality for a large reduction in memory bandwidth and footprint during generation — critical for serving long-context models at scale.</p>
<hr>
<p><strong>Q: Walk through the LoRA forward pass and explain why <span class="math inline">\(B\)</span> is initialized to zero.</strong></p>
<p>LoRA replaces <span class="math inline">\(h = W_0 x\)</span> with <span class="math inline">\(h = W_0 x + BA x\)</span>, where <span class="math inline">\(W_0\)</span> is frozen and only <span class="math inline">\(A \in \mathbb{R}^{r\times k}\)</span>, <span class="math inline">\(B \in \mathbb{R}^{d\times r}\)</span> are trained, with <span class="math inline">\(r \ll d,k\)</span>. Initializing <span class="math inline">\(B = 0\)</span> (with <span class="math inline">\(A\)</span> initialized randomly, e.g., Gaussian) ensures <span class="math inline">\(\Delta W = BA = 0\)</span> at the start of training, so the adapted model is <em>identical</em> to the pre-trained model before any fine-tuning steps — training starts from a known-good point and gradually learns a low-rank perturbation, rather than starting from a randomly perturbed (and likely worse) model.</p>
<hr>
<p><strong>Q: How does DPO avoid training a separate reward model, and what does it give up compared to PPO-based RLHF?</strong></p>
<p>DPO derives a closed-form expression for the optimal RLHF policy as a function of the reward, then substitutes this back into the Bradley-Terry preference model — the reward terms cancel into log-probability ratios between the policy and a frozen reference model. The result is a simple binary classification loss directly on the policy’s log-probabilities of preferred vs.&nbsp;dispreferred completions, with <span class="math inline">\(\beta\)</span> playing the role of the RLHF KL-penalty coefficient. What’s given up: DPO is trained on a <em>fixed, offline</em> preference dataset sampled from <span class="math inline">\(\pi_{\text{ref}}\)</span>, whereas PPO-based RLHF can sample new completions from the <em>current</em> policy during training (online), potentially exploring regions of output space the offline dataset doesn’t cover.</p>
<hr>
<p><strong>Q: Why is QLoRA able to fine-tune a 65B model on a single GPU when full fine-tuning needs ~780 GB?</strong></p>
<p>Full fine-tuning’s memory is dominated by gradients and Adam optimizer states for <em>all</em> 65B parameters (24 bytes/param total). LoRA already removes most of this by freezing the base model and training only ~0.1% of parameters as low-rank adapters — but the frozen 16-bit base weights (130 GB) still dominate. QLoRA additionally stores those frozen weights in 4-bit NF4 (~33 GB), since they’re never updated and don’t need gradient/optimizer storage — only the small adapter matrices need full-precision gradients and Adam states. The combination removes both major cost drivers: optimizer states (via freezing) and base-weight precision (via quantization), leaving a total in the tens of GB.</p>


</section>

</main> <!-- /main -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const callouts = document.querySelectorAll('.callout-tip');
    callouts.forEach(function(callout) {
      callout.style.borderLeftColor = '#2196f3'; //#616161; //'#4caf50';
      callout.style.color = 'ffffff'; // Dark purple-gray text
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/nlp/18-sequence-models.html" class="pagination-link" aria-label="Sequence Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Sequence Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/nlp/20-text-embeddings-evaluation.html" class="pagination-link" aria-label="Text Embedding Models &amp; Evaluation">
        <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Text Embedding Models &amp; Evaluation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>