<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>30&nbsp; Neural Audio Codecs – deep_learning_notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/audio/25-speech-synthesis.html" rel="next">
<link href="../../chapters/audio/23-speaker-diarization.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-fd0503e23dce65854c81c5baaade3bdf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/audio/24-neural-audio-codecs.html"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Neural Audio Codecs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">deep_learning_notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/_intro_foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-neural-networks-and-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Neural Networks and Optimization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-generalization-and-learning-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Generalization and Learning Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/_intro_computer_vision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computer Vision</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Visual Understanding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/03-cnns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Convolutional Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/04-object-detection-and-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Detection and Segmentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/05-vision-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vision Transformers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/06-foundation-models-for-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Foundation Models for Segmentation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Self-Supervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/06-self-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Self-Supervised Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV: Generative Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/_intro-generative-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generative Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/07-vaes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variational Autoencoders (VAEs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/08-gans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generative Adversarial Networks (GANs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/09-diffusion-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diffusion Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/_conclusion-generative-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusion</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/_intro_video.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Video</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/10-video.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Video Fundamentals: Motion and Spatiotemporal Architectures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/11-video-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Video Understanding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/12-video-temporal-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Video Temporal Segmentation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/13-video-understanding-benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Video Understanding Benchmarks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/14-video-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Video Generation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/_intro_3d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3D Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/11-3d-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">3D Data Understanding</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">3D Reconstruction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/12-3d-reconstruction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">3D Reconstruction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/13-gaussian-splatting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">3D Gaussian Splatting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Human Pose Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/human_pose_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Human Pose Estimation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/_intro_nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Natural Language Processing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/17-text-representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Text Representation &amp; Word Embeddings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/18-sequence-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Sequence Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/19-large-language-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Large Language Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/20-text-embeddings-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Text Embedding Models &amp; Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision_language/_intro_vision_language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vision-Language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision_language/16-vision-language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Vision-Language Multimodal Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/_intro_time_series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time Series</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/14-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Time Series Fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/15-deep-learning-for-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Deep Learning for Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/_intro_audio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Audio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/21-speech-representation-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Speech Representation Learning and Foundation Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/22-automatic-speech-recognition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Automatic Speech Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/23-speaker-diarization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Speaker Diarization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/24-neural-audio-codecs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Neural Audio Codecs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/25-speech-synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Speech Synthesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/26-speech-language-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Speech and Audio Language Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/27-audio-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Audio Understanding Beyond Words</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-codec-why" id="toc-sec-codec-why" class="nav-link active" data-scroll-target="#sec-codec-why"><span class="header-section-number">30.1</span> Why Audio Needs a Tokeniser</a></li>
  <li><a href="#sec-vqvae" id="toc-sec-vqvae" class="nav-link" data-scroll-target="#sec-vqvae"><span class="header-section-number">30.2</span> From Autoencoders to VQ-VAE</a>
  <ul class="collapse">
  <li><a href="#sec-ste" id="toc-sec-ste" class="nav-link" data-scroll-target="#sec-ste"><span class="header-section-number">30.2.1</span> The Straight-Through Estimator</a></li>
  <li><a href="#sec-vq-loss" id="toc-sec-vq-loss" class="nav-link" data-scroll-target="#sec-vq-loss"><span class="header-section-number">30.2.2</span> Commitment, Codebook Updates, and Dead Codes</a></li>
  </ul></li>
  <li><a href="#sec-rvq" id="toc-sec-rvq" class="nav-link" data-scroll-target="#sec-rvq"><span class="header-section-number">30.3</span> Residual Vector Quantisation</a></li>
  <li><a href="#sec-collapse" id="toc-sec-collapse" class="nav-link" data-scroll-target="#sec-collapse"><span class="header-section-number">30.4</span> Codebook Collapse and How to Avoid It</a>
  <ul class="collapse">
  <li><a href="#sec-entropy" id="toc-sec-entropy" class="nav-link" data-scroll-target="#sec-entropy"><span class="header-section-number">30.4.1</span> Per-Layer Entropy as a Diagnostic</a></li>
  </ul></li>
  <li><a href="#sec-codec-losses" id="toc-sec-codec-losses" class="nav-link" data-scroll-target="#sec-codec-losses"><span class="header-section-number">30.5</span> Training Objectives</a></li>
  <li><a href="#sec-codec-zoo" id="toc-sec-codec-zoo" class="nav-link" data-scroll-target="#sec-codec-zoo"><span class="header-section-number">30.6</span> The Codec Landscape</a></li>
  <li><a href="#sec-semantic-acoustic" id="toc-sec-semantic-acoustic" class="nav-link" data-scroll-target="#sec-semantic-acoustic"><span class="header-section-number">30.7</span> Semantic and Acoustic Tokens</a></li>
  <li><a href="#sec-serialisation" id="toc-sec-serialisation" class="nav-link" data-scroll-target="#sec-serialisation"><span class="header-section-number">30.8</span> Serialising the Token Grid</a></li>
  <li><a href="#sec-codec-inside" id="toc-sec-codec-inside" class="nav-link" data-scroll-target="#sec-codec-inside"><span class="header-section-number">30.9</span> What Is Actually Inside the Tokens?</a></li>
  <li><a href="#sec-codec-eval" id="toc-sec-codec-eval" class="nav-link" data-scroll-target="#sec-codec-eval"><span class="header-section-number">30.10</span> Evaluation</a></li>
  <li><a href="#sec-continuous-alt" id="toc-sec-continuous-alt" class="nav-link" data-scroll-target="#sec-continuous-alt"><span class="header-section-number">30.11</span> Do We Need Discrete Tokens at All?</a></li>
  <li><a href="#sec-codec-open" id="toc-sec-codec-open" class="nav-link" data-scroll-target="#sec-codec-open"><span class="header-section-number">30.12</span> Open Problems</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">30.13</span> Summary</a></li>
  <li><a href="#sec-codec-sources" id="toc-sec-codec-sources" class="nav-link" data-scroll-target="#sec-codec-sources"><span class="header-section-number">30.14</span> Sources and Further Reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-codecs" class="quarto-section-identifier"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Neural Audio Codecs</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="25-speech-synthesis.html#sec-codec-lm" class="quarto-xref"><span>Section 31.9</span></a> treated the token grid <span class="math inline">\(\mathbf{C} \in \{1..V\}^{T_c \times N_q}\)</span> as given. This chapter opens the box.</p>
<p>A <strong>neural audio codec</strong> is a learned compressor: an encoder that maps a waveform to a low-rate latent sequence, a quantiser that maps each latent frame to one or more discrete indices, and a decoder that reconstructs the waveform from those indices. It is trained end-to-end, usually with adversarial supervision, and it plays two quite different roles depending on who is using it. To a communications engineer it is a codec in the classical sense — a way to transmit speech at 1.5 kbps instead of 256 kbps. To someone building a speech language model it is a <strong>tokeniser</strong>: the thing that turns a continuous signal into a sequence of integers so that the machinery of language modelling applies.</p>
<p>Those two roles pull in different directions, and much of what follows is about that tension. A codec optimised purely for reconstruction produces tokens that are hard to model; a codec optimised for modelling gives up fidelity. Nearly every design decision in this chapter — frame rate, codebook count, semantic distillation, quantiser structure — is a position on that trade-off.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading order
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter assumes <a href="25-speech-synthesis.html" class="quarto-xref"><span>Chapter 31</span></a> (which motivates codecs) and <a href="21-speech-representation-learning.html#sec-discrete-units" class="quarto-xref"><span>Section 27.8.2</span></a> (which supplies the semantic-token half of the story). It is a prerequisite for the speech language models of <a href="26-speech-language-models.html" class="quarto-xref"><span>Chapter 32</span></a>. Readers who want the image-domain background will find VQ-VAE and VQGAN familiar <span class="citation" data-cites="vandenoord2017vqvae esser2021vqgan">(<a href="../../references.html#ref-vandenoord2017vqvae" role="doc-biblioref">Oord et al. 2017</a>; <a href="../../references.html#ref-esser2021vqgan" role="doc-biblioref">Esser et al. 2021</a>)</span>; this chapter re-derives what it needs.</p>
</div>
</div>
<section id="sec-codec-why" class="level2" data-number="30.1">
<h2 data-number="30.1" class="anchored" data-anchor-id="sec-codec-why"><span class="header-section-number">30.1</span> Why Audio Needs a Tokeniser</h2>
<p>The motivating problem is a rate mismatch, and it is worth quantifying because the numbers are what force the design.</p>
<p>One second of English speech is roughly three to four <em>text</em> tokens. The same second at 24 kHz is 24,000 <em>samples</em>. If you tokenise audio at the sample level — <span class="math inline">\(\mu\)</span>-law companding to 256 levels, as WaveNet did (<a href="25-speech-synthesis.html#sec-wavenet" class="quarto-xref"><span>Section 31.5.1</span></a>) — a language model with a 2,048-token context window sees <strong>128 milliseconds</strong> of audio at 16 kHz, which is less than one word. No amount of training fixes a context window that cannot hold a single word.</p>
<p>This is not a thought experiment. Volhejn’s Kyutai explainer runs it directly: a 151M-parameter GPT-2-scale Transformer trained on 1,000 hours of Libri-Light with sample-level <span class="math inline">\(\mu\)</span>-law tokens produces speech-like babbling in which no word is intelligible, the voice drifts, and generation of ten seconds takes about thirty minutes on an H100. The failure is not acoustic — locally the audio sounds like speech — it is a failure of <em>coherence over time</em>, exactly as predicted by the context-window arithmetic.</p>
<p>So we compress. If the encoder downsamples by a factor of <span class="math inline">\(D\)</span> and emits <span class="math inline">\(N_q\)</span> tokens per frame, the token rate is</p>
<p><span id="eq-bitrate"><span class="math display">\[
\text{tokens/s} = \underbrace{\frac{f_s}{D}}_{\text{frame rate } f_r} \times N_q,
\qquad
\text{bitrate } R = f_r \cdot N_q \cdot \log_2 V \; \text{bits/s}
\tag{30.1}\]</span></span></p>
<p>where <span class="math inline">\(V\)</span> is the codebook size. <a href="#eq-bitrate" class="quarto-xref">Equation&nbsp;<span>30.1</span></a> is the budget every architecture in this chapter negotiates with, so it is worth grounding in real numbers:</p>
<div id="tbl-codec-rates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-codec-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;30.1: Frame rate, codebook depth, and bitrate for representative codecs.
</figcaption>
<div aria-describedby="tbl-codec-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Codec</th>
<th style="text-align: right;"><span class="math inline">\(f_r\)</span></th>
<th style="text-align: right;"><span class="math inline">\(N_q\)</span></th>
<th style="text-align: right;"><span class="math inline">\(V\)</span></th>
<th style="text-align: right;">Bitrate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EnCodec 24 kHz</td>
<td style="text-align: right;">75 Hz</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">1024</td>
<td style="text-align: right;">24 kbps</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAC 44.1 kHz</td>
<td style="text-align: right;">86 Hz</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1024</td>
<td style="text-align: right;">7.75 kbps</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mimi</td>
<td style="text-align: right;">12.5 Hz</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2048</td>
<td style="text-align: right;">1.1 kbps</td>
</tr>
<tr class="even">
<td style="text-align: left;">WavTokenizer</td>
<td style="text-align: right;">40–75 Hz</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4096</td>
<td style="text-align: right;">0.48–0.9 kbps</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Two observations follow immediately, and they organise the rest of the chapter. <strong>Frame rate is the most valuable axis</strong> for a language model, because it reduces sequence length linearly — Mimi’s 12.5 Hz is a sixfold advantage over EnCodec’s 75 Hz before any other consideration. And <strong><span class="math inline">\(N_q\)</span> is a liability rather than an asset</strong> for a language model, because a model emits one token at a time and <span class="math inline">\(N_q\)</span> tokens per frame must be serialised somehow (<a href="#sec-serialisation" class="quarto-xref"><span>Section 30.8</span></a>). Compression research wants high <span class="math inline">\(N_q\)</span>; modelling research wants <span class="math inline">\(N_q = 1\)</span>.</p>
</section>
<section id="sec-vqvae" class="level2" data-number="30.2">
<h2 data-number="30.2" class="anchored" data-anchor-id="sec-vqvae"><span class="header-section-number">30.2</span> From Autoencoders to VQ-VAE</h2>
<p>The cleanest way into vector quantisation is to leave audio entirely, which is the route the Kyutai explainer takes and which I follow here because the intuition transfers exactly.</p>
<p>Train an ordinary autoencoder on images — say Fashion-MNIST — compressing each image to a two-dimensional latent. Plotting the latent space shows it clusters naturally by class without ever being told the classes. Now quantise: maintain a list of cluster centres (a <strong>codebook</strong>) <span class="math inline">\(\mathcal{E} = \{\mathbf{e}_1, \ldots, \mathbf{e}_V\}\)</span>, assign each latent to its nearest centre,</p>
<p><span id="eq-vq-lookup"><span class="math display">\[
k = \arg\min_{v \in \{1..V\}} \big\| \mathbf{z} - \mathbf{e}_v \big\|_2,
\qquad
\mathbf{z}_q = \mathbf{e}_k
\tag{30.2}\]</span></span></p>
<p>and hand <span class="math inline">\(\mathbf{z}_q\)</span> rather than <span class="math inline">\(\mathbf{z}\)</span> to the decoder. The consequence is immediately visible in the reconstructions: two images whose latents land in the same cell decode to <em>exactly</em> the same output. Quantisation is lossy in a very concrete, inspectable way.</p>
<section id="sec-ste" class="level3" data-number="30.2.1">
<h3 data-number="30.2.1" class="anchored" data-anchor-id="sec-ste"><span class="header-section-number">30.2.1</span> The Straight-Through Estimator</h3>
<p><a href="#eq-vq-lookup" class="quarto-xref">Equation&nbsp;<span>30.2</span></a> contains an <span class="math inline">\(\arg\min\)</span>, which has zero gradient almost everywhere. Training would stop at the quantiser.</p>
<p>The fix, in Volhejn’s memorable phrasing, is to <em>pretend the problem does not exist</em>. Treat <span class="math inline">\(\mathbf{z}_q\)</span> as <span class="math inline">\(\mathbf{z}\)</span> displaced by a constant, and copy the decoder’s gradient past the quantiser unchanged:</p>
<p><span id="eq-ste"><span class="math display">\[
\mathbf{z}_q = \mathbf{z} + \operatorname{sg}\!\big[\mathbf{e}_k - \mathbf{z}\big],
\qquad
\frac{\partial \mathbf{z}_q}{\partial \mathbf{z}} := \mathbf{I}
\tag{30.3}\]</span></span></p>
<p>where <span class="math inline">\(\operatorname{sg}[\cdot]\)</span> is the stop-gradient operator. The forward pass is unchanged; the backward pass behaves as though quantisation never happened. This is the <strong>straight-through estimator</strong>.</p>
<p>There is a price, and it is worth stating because it explains the next ingredient. The encoder is updated as if its output went to the decoder unquantised, so the gradient direction is wrong by roughly the quantisation error. The approximation is good only when latents sit close to their assigned centres — which gives us a reason to <em>make</em> them sit close.</p>
</section>
<section id="sec-vq-loss" class="level3" data-number="30.2.2">
<h3 data-number="30.2.2" class="anchored" data-anchor-id="sec-vq-loss"><span class="header-section-number">30.2.2</span> Commitment, Codebook Updates, and Dead Codes</h3>
<p>The full VQ-VAE objective <span class="citation" data-cites="vandenoord2017vqvae">(<a href="../../references.html#ref-vandenoord2017vqvae" role="doc-biblioref">Oord et al. 2017</a>)</span> has three terms:</p>
<p><span id="eq-vqvae-loss"><span class="math display">\[
\mathcal{L}_{\text{VQ}} =
\underbrace{\mathcal{L}_{\text{rec}}(\mathbf{x}, \hat{\mathbf{x}})}_{\text{reconstruction}}
+ \underbrace{\big\| \operatorname{sg}[\mathbf{z}] - \mathbf{e}_k \big\|_2^2}_{\text{codebook}}
+ \beta \underbrace{\big\| \mathbf{z} - \operatorname{sg}[\mathbf{e}_k] \big\|_2^2}_{\text{commitment}}
\tag{30.4}\]</span></span></p>
<p>The <strong>codebook</strong> term pulls each code toward the mean of the latents assigned to it — gradient-descent <span class="math inline">\(k\)</span>-means. The <strong>commitment</strong> term pulls the <em>encoder</em> toward the codes, penalising latents that stray far from their centre; this is precisely what keeps the straight-through approximation honest. The two terms are mirror images distinguished only by where the stop-gradient sits.</p>
<p>The codebook term is often replaced by an <strong>exponential moving average</strong> update <span class="citation" data-cites="razavi2019vqvae2">(<a href="../../references.html#ref-razavi2019vqvae2" role="doc-biblioref">Razavi et al. 2019</a>)</span>, which is more stable and is what DAC, Mimi, and most modern codecs use. With <span class="math inline">\(n_v\)</span> the count of latents assigned to code <span class="math inline">\(v\)</span> in a batch and <span class="math inline">\(\mathbf{m}_v\)</span> their sum,</p>
<p><span id="eq-ema"><span class="math display">\[
N_v \leftarrow \mu N_v + (1-\mu) n_v,
\qquad
\mathbf{M}_v \leftarrow \mu \mathbf{M}_v + (1-\mu)\mathbf{m}_v,
\qquad
\mathbf{e}_v \leftarrow \frac{\mathbf{M}_v}{N_v}
\tag{30.5}\]</span></span></p>
<p>with <span class="math inline">\(\mu \approx 0.99\)</span>–<span class="math inline">\(0.999\)</span>. Under an EMA update the codebook is no longer trained by the loss at all, so only the commitment term in <a href="#eq-vqvae-loss" class="quarto-xref">Equation&nbsp;<span>30.4</span></a> contributes to the generator gradient.</p>
<p><strong>Dead codes</strong> are the characteristic pathology. A code that is never selected receives no update — under gradient descent or EMA alike — and therefore can never move to where the data is. It is stranded permanently. The standard remedy is blunt and effective: if a code goes unused for some number of steps, <strong>reinitialise it</strong> to a randomly chosen latent from the current batch. Volhejn describes this as <em>teleporting</em> the centre, which is exactly right. Dead-code reinitialisation appears in almost every production codec, usually with a threshold of a few hundred to a few thousand steps of disuse.</p>
</section>
</section>
<section id="sec-rvq" class="level2" data-number="30.3">
<h2 data-number="30.3" class="anchored" data-anchor-id="sec-rvq"><span class="header-section-number">30.3</span> Residual Vector Quantisation</h2>
<p>A single codebook of size <span class="math inline">\(V\)</span> contributes <span class="math inline">\(\log_2 V\)</span> bits per frame. To get 20 bits you would need <span class="math inline">\(2^{20} \approx 10^6\)</span> entries, which is prohibitive in memory and in nearest-neighbour search cost, and hopeless statistically since most entries would rarely be selected.</p>
<p><strong>Residual vector quantisation</strong> obtains the same expressiveness from a cascade of small codebooks by quantising what the previous stage got wrong. Recall from <a href="#sec-ste" class="quarto-xref"><span>Section 30.2.1</span></a> that the quantisation error <span class="math inline">\(\mathbf{z} - \mathbf{e}_k\)</span> is already sitting there in the straight-through computation. Quantise <em>it</em>, with a second codebook, and repeat:</p>
<p><span id="eq-rvq"><span class="math display">\[
\mathbf{r}_0 = \mathbf{z}, \qquad
\mathbf{q}_n = Q_n(\mathbf{r}_{n-1}), \qquad
\mathbf{r}_n = \mathbf{r}_{n-1} - \mathbf{q}_n, \qquad
\hat{\mathbf{z}} = \sum_{n=1}^{N_q} \mathbf{q}_n
\tag{30.6}\]</span></span></p>
<p>where <span class="math inline">\(Q_n\)</span> is nearest-neighbour lookup in the <span class="math inline">\(n\)</span>-th codebook. Two codebooks of 1,024 entries give <span class="math inline">\(2^{20}\)</span> effective combinations from 2,048 stored vectors.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rvq_quantize(z, codebooks):</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    residual, codes <span class="op">=</span> z, []</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cb <span class="kw">in</span> codebooks:</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        quantized, index <span class="op">=</span> nearest_code(cb, residual)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>        residual <span class="op">=</span> residual <span class="op">-</span> quantized</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        codes.append(index)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> codes            <span class="co"># one integer per level</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Three properties matter downstream.</p>
<p><strong>The levels are ordered by importance.</strong> Codebook 1 quantises the signal itself and therefore carries the coarse structure; each subsequent codebook encodes a progressively smaller correction. This is not a designed hierarchy but a consequence of <a href="#eq-rvq" class="quarto-xref">Equation&nbsp;<span>30.6</span></a>, and it is what makes the semantic/acoustic split of <a href="#sec-semantic-acoustic" class="quarto-xref"><span>Section 30.7</span></a> possible.</p>
<p><strong>Bitrate is truncatable at inference.</strong> Decoding with the first <span class="math inline">\(n &lt; N_q\)</span> codebooks yields a valid, lower-quality reconstruction at a lower bitrate, with no retraining. This only works well if training prepared for it, which is what <strong>RVQ dropout</strong> does: randomly truncate the number of levels used during training so the decoder never learns to depend on all of them. SoundStream introduced this as “quantizer dropout” and Mimi uses it; a codec trained without it must be retrained for each operating point.</p>
<p><strong>The output is a two-dimensional grid</strong>, <span class="math inline">\(T_c \times N_q\)</span>, which is the problem of <a href="#sec-serialisation" class="quarto-xref"><span>Section 30.8</span></a>.</p>
<p>RVQ predates neural codecs by decades — it is standard in classical vector quantisation — and reached audio through SoundStream <span class="citation" data-cites="zeghidour2022soundstream">(<a href="../../references.html#ref-zeghidour2022soundstream" role="doc-biblioref">Zeghidour et al. 2022</a>)</span>. The same idea reached image generation independently <span class="citation" data-cites="lee2022rqvae">(<a href="../../references.html#ref-lee2022rqvae" role="doc-biblioref">Lee et al. 2022</a>)</span>.</p>
</section>
<section id="sec-collapse" class="level2" data-number="30.4">
<h2 data-number="30.4" class="anchored" data-anchor-id="sec-collapse"><span class="header-section-number">30.4</span> Codebook Collapse and How to Avoid It</h2>
<p>Codebook collapse is the recurring failure of this chapter, and the reader has met it twice already: <a href="21-speech-representation-learning.html#eq-diversity" class="quarto-xref">Equation&nbsp;<span>27.4</span></a> was wav2vec 2.0’s answer to it, and CosyVoice 2’s move to scalar quantisation (<a href="25-speech-synthesis.html#sec-cosyvoice" class="quarto-xref"><span>Section 31.9.4</span></a>) was another. It deserves a proper treatment here because codecs are where it bites hardest.</p>
<p>The failure is that a small fraction of codes absorb most of the probability mass while the rest go unused. Effective bitrate then falls below the nominal <span class="math inline">\(\log_2 V\)</span> bits per level: you are paying for a 1,024-entry codebook and using 200 of them. Four families of fix are in current use.</p>
<p><strong>EMA plus dead-code reinitialisation</strong> (<a href="#sec-vq-loss" class="quarto-xref"><span>Section 30.2.2</span></a>) is the baseline and is nearly universal.</p>
<p><strong>Factorised and <span class="math inline">\(L_2\)</span>-normalised codes</strong>, introduced by DAC <span class="citation" data-cites="kumar2023dac">(<a href="../../references.html#ref-kumar2023dac" role="doc-biblioref">Kumar et al. 2023</a>)</span>, are the most cited fix. The idea is to perform the codebook lookup in a <em>low-dimensional</em> projected space (DAC uses 8 or 32 dimensions against a 1,024-dimensional latent) and to <span class="math inline">\(L_2\)</span>-normalise both latents and codes so that lookup becomes cosine similarity on a hypersphere. Both changes make the nearest-neighbour geometry better conditioned and dramatically improve utilisation. This is the single most transferable trick in codec engineering.</p>
<p><strong>Finite scalar quantisation</strong> <span class="citation" data-cites="mentzer2024fsq">(<a href="../../references.html#ref-mentzer2024fsq" role="doc-biblioref">Mentzer et al. 2024</a>)</span> eliminates the problem structurally rather than treating it. Project the latent to a low dimension <span class="math inline">\(d\)</span> (typically 3–8), then round each dimension independently to one of <span class="math inline">\(L\)</span> levels after a bounding nonlinearity:</p>
<p><span id="eq-fsq"><span class="math display">\[
\hat{z}_i = \operatorname{round}\!\big( \lfloor L/2 \rfloor \tanh(z_i) \big),
\qquad
\text{index} = \sum_{i=1}^{d} \hat{z}_i' \, L^{\,i-1},
\qquad V = L^d
\tag{30.7}\]</span></span></p>
<p>There is <strong>no codebook</strong> — the “codes” are the vertices of a fixed integer lattice, every one of which is reachable by construction. No commitment loss, no EMA, no dead-code reinitialisation, no auxiliary entropy term. Gradients use a straight-through round. FSQ matches learned VQ at comparable vocabulary sizes while removing an entire category of failure, which is why it has spread quickly into speech systems.</p>
<p><strong>Single large codebook with careful engineering</strong> is the fourth route. BigCodec <span class="citation" data-cites="xin2024bigcodec">(<a href="../../references.html#ref-xin2024bigcodec" role="doc-biblioref">Xin et al. 2024</a>)</span> and WavTokenizer <span class="citation" data-cites="ji2025wavtokenizer">(<a href="../../references.html#ref-ji2025wavtokenizer" role="doc-biblioref">Ji et al. 2025</a>)</span> abandon RVQ for one high-cardinality codebook, betting that the modelling simplification is worth the engineering difficulty. X-Codec2, the tokeniser behind Llasa <span class="citation" data-cites="ye2025llasa">(<a href="../../references.html#ref-ye2025llasa" role="doc-biblioref">Ye et al. 2025</a>)</span>, reports roughly 99% utilisation of a 65,536-entry codebook at 50 Hz — evidence that the collapse problem is tractable even at extreme vocabulary sizes given the right lookup geometry.</p>
<section id="sec-entropy" class="level3" data-number="30.4.1">
<h3 data-number="30.4.1" class="anchored" data-anchor-id="sec-entropy"><span class="header-section-number">30.4.1</span> Per-Layer Entropy as a Diagnostic</h3>
<p>Collapse is usually reported as a single utilisation percentage, which hides where it happens. A more informative diagnostic is the <strong>entropy of the code distribution at each RVQ level</strong>, <span class="math inline">\(H_n = -\sum_v p_{n,v}\log_2 p_{n,v}\)</span>, compared against the ceiling <span class="math inline">\(\log_2 V\)</span>.</p>
<p>A recent study of tonal content in codecs <span class="citation" data-cites="mondal2026tonal">(<a href="../../references.html#ref-mondal2026tonal" role="doc-biblioref">Mondal and Gupta 2026</a>)</span> reports such profiles and finds the deficit concentrated in the <strong>upper</strong> layers: DAC at 32 kbps falls below 7.0 bits (of a possible 10) for codebook indices above 24, and EnCodec at 24 kbps is worse. The proposed explanation is a data argument rather than an optimisation one — upper layers encode fine residual detail, and the signals that generate rich fine residuals (sustained harmonic material: bells, glockenspiel, piano) are under-represented in ordinary training corpora, so the upper codebooks are starved of the very data that would populate them. Rebalancing training toward such content raised reported active-entry usage from about 74% to about 95%.</p>
<p>The same work gives a usefully crisp definition of a <em>content-dependent</em> codec failure — one that aggregate metrics hide. <strong>Tonal weakness</strong> decomposes into harmonic artefacts (spurious components near harmonics), decay truncation (premature clipping of long amplitude envelopes, giving an unnatural staccato), and pitch instability (wobble on nominally steady tones). The DAC and EnCodec papers both acknowledge degradation on this material without offering a remedy.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>How much weight to put on this
</div>
</div>
<div class="callout-body-container callout-body">
<p>The tonal study is a limited-scale result and says so: 720 hours of training audio on four GPUs, compared against public DAC checkpoints the authors estimate used 10–50<span class="math inline">\(\times\)</span> more data, with a 22-listener panel and large-scale replication left as future work. Take the <em>diagnostic</em> — per-layer entropy, and the observation that content under-represented in training starves the upper codebooks — rather than the specific model or its benchmark numbers.</p>
</div>
</div>
</section>
</section>
<section id="sec-codec-losses" class="level2" data-number="30.5">
<h2 data-number="30.5" class="anchored" data-anchor-id="sec-codec-losses"><span class="header-section-number">30.5</span> Training Objectives</h2>
<p>A codec is trained with a composite objective that inherits almost entirely from the GAN vocoders of <a href="25-speech-synthesis.html#sec-hifigan" class="quarto-xref"><span>Section 31.5.2</span></a>. Nothing here is conceptually new; what is new is the quantiser sitting in the middle.</p>
<p><strong>Multi-scale spectral reconstruction.</strong> An <span class="math inline">\(L_1\)</span> distance between log-mel spectrograms of reference and reconstruction, summed over several STFT window sizes:</p>
<p><span id="eq-mel-loss"><span class="math display">\[
\mathcal{L}_{\text{spec}} = \sum_{i \in S}
\big\| \log \operatorname{Mel}_i(\mathbf{x}) - \log \operatorname{Mel}_i(\hat{\mathbf{x}}) \big\|_1,
\qquad S = \{32, 64, \ldots, 2048\}
\tag{30.8}\]</span></span></p>
<p>Multiple resolutions are used because a single STFT window fixes one point on the time-frequency resolution trade-off, and a model optimised against it can exploit the blind spot. Short windows see transients; long windows see harmonic structure and long decays.</p>
<p><strong>Adversarial and feature-matching terms.</strong> A bank of sub-discriminators <span class="math inline">\(\{D_k\}\)</span> — multi-period on the raw waveform (<a href="25-speech-synthesis.html#sec-hifigan" class="quarto-xref"><span>Section 31.5.2</span></a>) plus multi-scale or multi-band STFT discriminators — trained with a hinge objective, alongside an <span class="math inline">\(L_1\)</span> match between the discriminators’ intermediate activations on real and reconstructed audio:</p>
<p><span id="eq-codec-adv"><span class="math display">\[
\mathcal{L}_{\text{adv}} = \sum_{k} \mathbb{E}\big[\max(0,\, 1 - D_k(\hat{\mathbf{x}}))\big],
\qquad
\mathcal{L}_{\text{fm}} = \sum_{k}\sum_{l} \frac{1}{N_{k,l}}
\big\| D_k^{(l)}(\mathbf{x}) - D_k^{(l)}(\hat{\mathbf{x}}) \big\|_1
\tag{30.9}\]</span></span></p>
<p><strong>Quantisation terms.</strong> The commitment loss of <a href="#eq-vqvae-loss" class="quarto-xref">Equation&nbsp;<span>30.4</span></a>, summed over RVQ levels.</p>
<p>The total is a weighted sum, and the weights are lopsided in a way worth noticing:</p>
<p><span id="eq-codec-total"><span class="math display">\[
\mathcal{L} = \lambda_{\text{spec}} \mathcal{L}_{\text{spec}}
+ \lambda_{\text{fm}} \mathcal{L}_{\text{fm}}
+ \lambda_{\text{adv}} \mathcal{L}_{\text{adv}}
+ \lambda_{\text{commit}} \mathcal{L}_{\text{commit}}
\tag{30.10}\]</span></span></p>
<p>with typical values <span class="math inline">\(\lambda_{\text{spec}} = 15\)</span>, <span class="math inline">\(\lambda_{\text{fm}} = 2\)</span>, <span class="math inline">\(\lambda_{\text{adv}} = 1\)</span>, <span class="math inline">\(\lambda_{\text{commit}} = 0.25\)</span>. A common practical detail is a warm-up of tens of thousands of steps on reconstruction losses alone before the discriminators are switched on.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A consequence worth remembering
</div>
</div>
<div class="callout-body-container callout-body">
<p>Because <a href="#eq-codec-total" class="quarto-xref">Equation&nbsp;<span>30.10</span></a> optimises perceptual and adversarial criteria rather than waveform distance, adversarially-trained codecs can post <strong>negative SI-SDR</strong> while sounding excellent — DAC reports around <span class="math inline">\(-1\)</span> to <span class="math inline">\(-2\)</span> dB. This is not a defect; it means the model reproduces perceptual structure without aligning sample-by-sample. It also means SI-SDR is invalid for comparing codecs with different optimisation objectives, and that mel distance and perceptual scores such as ViSQOL should carry the comparison instead.</p>
</div>
</div>
</section>
<section id="sec-codec-zoo" class="level2" data-number="30.6">
<h2 data-number="30.6" class="anchored" data-anchor-id="sec-codec-zoo"><span class="header-section-number">30.6</span> The Codec Landscape</h2>
<div id="tbl-codec-zoo" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-codec-zoo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;30.2: Representative neural audio codecs.
</figcaption>
<div aria-describedby="tbl-codec-zoo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Codec</th>
<th style="text-align: left;">Year</th>
<th style="text-align: left;">Rate</th>
<th style="text-align: right;"><span class="math inline">\(N_q\)</span></th>
<th style="text-align: left;">Distinguishing idea</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>SoundStream</strong> <span class="citation" data-cites="zeghidour2022soundstream">(<a href="../../references.html#ref-zeghidour2022soundstream" role="doc-biblioref">Zeghidour et al. 2022</a>)</span></td>
<td style="text-align: left;">2021</td>
<td style="text-align: left;">24 kHz, 75 Hz</td>
<td style="text-align: right;">≤24</td>
<td style="text-align: left;">First RVQ audio codec; quantiser dropout for scalable bitrate</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>EnCodec</strong> <span class="citation" data-cites="defossez2023encodec">(<a href="../../references.html#ref-defossez2023encodec" role="doc-biblioref">Défossez et al. 2023</a>)</span></td>
<td style="text-align: left;">2022</td>
<td style="text-align: left;">24/48 kHz, 75 Hz</td>
<td style="text-align: right;">≤32</td>
<td style="text-align: left;">Open, widely adopted; multi-scale STFT discriminator; optional entropy coding</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>DAC</strong> <span class="citation" data-cites="kumar2023dac">(<a href="../../references.html#ref-kumar2023dac" role="doc-biblioref">Kumar et al. 2023</a>)</span></td>
<td style="text-align: left;">2023</td>
<td style="text-align: left;">44.1 kHz, 86 Hz</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Factorised + <span class="math inline">\(L_2\)</span>-normalised codes fix utilisation; Snake activation; the quality baseline</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SpeechTokenizer</strong> <span class="citation" data-cites="zhang2024speechtokenizer">(<a href="../../references.html#ref-zhang2024speechtokenizer" role="doc-biblioref">Zhang et al. 2024</a>)</span></td>
<td style="text-align: left;">2023</td>
<td style="text-align: left;">16 kHz, 50 Hz</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Distils HuBERT into RVQ level 1: semantic first, acoustic after</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Mimi</strong> <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span></td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;">24 kHz, <strong>12.5 Hz</strong></td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Split RVQ, WavLM distillation, causal/streaming, Transformer in encoder and decoder</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SNAC</strong> <span class="citation" data-cites="siuzdak2024snac">(<a href="../../references.html#ref-siuzdak2024snac" role="doc-biblioref">Siuzdak et al. 2024</a>)</span></td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;">24–44 kHz, multi</td>
<td style="text-align: right;">3–4</td>
<td style="text-align: left;">Quantisers at <em>different temporal resolutions</em> rather than all at one rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>BigCodec</strong> <span class="citation" data-cites="xin2024bigcodec">(<a href="../../references.html#ref-xin2024bigcodec" role="doc-biblioref">Xin et al. 2024</a>)</span></td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;">16 kHz, 80 Hz</td>
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: left;">Single high-cardinality VQ at Mimi-comparable bitrate</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>WavTokenizer</strong> <span class="citation" data-cites="ji2025wavtokenizer">(<a href="../../references.html#ref-ji2025wavtokenizer" role="doc-biblioref">Ji et al. 2025</a>)</span></td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;">24 kHz, 40–75 Hz</td>
<td style="text-align: right;"><strong>1</strong></td>
<td style="text-align: left;">Extreme compression, 40–75 tokens/s, one codebook</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Reading the table chronologically shows two trends running in opposite directions. Fidelity-oriented work (SoundStream → EnCodec → DAC) pushes sample rate and <span class="math inline">\(N_q\)</span> <em>up</em>. Modelling-oriented work (SpeechTokenizer → Mimi → BigCodec/WavTokenizer) pushes frame rate and <span class="math inline">\(N_q\)</span> <em>down</em>, accepting fidelity loss in exchange for shorter sequences and a simpler prediction target. These are different objectives, not competing answers to one objective, and papers that benchmark across the two groups on reconstruction metrics alone are comparing things that were not trying to do the same job.</p>
<p>SNAC deserves a note because it breaks an assumption everything else shares. Standard RVQ applies every codebook at the same frame rate; SNAC applies quantisers at <em>different</em> temporal resolutions, so coarse structure is coded sparsely in time and fine structure densely. This is a hierarchy along time as well as depth, and it is the codec behind Orpheus among others.</p>
</section>
<section id="sec-semantic-acoustic" class="level2" data-number="30.7">
<h2 data-number="30.7" class="anchored" data-anchor-id="sec-semantic-acoustic"><span class="header-section-number">30.7</span> Semantic and Acoustic Tokens</h2>
<p><a href="25-speech-synthesis.html#sec-audiolm" class="quarto-xref"><span>Section 31.9.2</span></a> introduced the semantic/acoustic split as a modelling decision made <em>outside</em> the codec, using two separate tokenisers. The dominant modern approach folds it <em>inside</em>.</p>
<p><strong>Semantic distillation</strong> adds a loss encouraging the first RVQ level’s output to predict the representations of a frozen self-supervised model (<a href="21-speech-representation-learning.html" class="quarto-xref"><span>Chapter 27</span></a>) — HuBERT for SpeechTokenizer, WavLM for Mimi. The effect is to make codebook 1 carry phonetic content while leaving speaker identity, prosody, and channel to levels 2 and up. Mimi refines this with <strong>split RVQ</strong>: rather than distilling into the first level of a single residual chain, it runs a separate single-codebook semantic quantiser <em>in parallel</em> with an acoustic RVQ, so that the semantic objective cannot degrade the acoustic reconstruction path.</p>
<p>The clearest demonstration of what semantic tokens contain is an experiment in the Kyutai explainer, and it is worth reproducing conceptually because it makes an abstract claim concrete. Take a language model trained over full Mimi tokens. Now generate with the <strong>semantic tokens held fixed</strong> from a reference recording (teacher-forced) while letting the model freely sample all acoustic tokens. Sampling twice yields two outputs that <strong>say the same words in completely different voices</strong>. The semantic stream determines <em>what</em> is said; the acoustic stream determines <em>how</em>.</p>
<p>That separation is what makes the split useful, for three reasons developed earlier: linguistic coherence over long spans (<a href="25-speech-synthesis.html#sec-audiolm" class="quarto-xref"><span>Section 31.9.2</span></a>), decoupled data requirements (<a href="25-speech-synthesis.html#sec-audiolm" class="quarto-xref"><span>Section 31.9.2</span></a>, via SPEAR-TTS), and a natural place to inject speaker identity. A fourth is practical — because the semantic token is <span class="math inline">\(1/N_q\)</span> of the token budget, its share of the loss falls as <span class="math inline">\(N_q\)</span> grows, so systems weight it heavily. Moshi uses a semantic loss factor of 100.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The trade-off in one sentence
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lowering <span class="math inline">\(N_q\)</span> raises the semantic token’s share of the loss and makes the model <em>more linguistic</em>, at the cost of acoustic fidelity — which is why 8-level and 12.5 Hz codecs became the norm for speech LLMs even though 32-level codecs reconstruct better.</p>
</div>
</div>
</section>
<section id="sec-serialisation" class="level2" data-number="30.8">
<h2 data-number="30.8" class="anchored" data-anchor-id="sec-serialisation"><span class="header-section-number">30.8</span> Serialising the Token Grid</h2>
<p>Here is the problem this chapter has been deferring. RVQ emits <span class="math inline">\(N_q\)</span> tokens per frame. A language model emits one token per step. Something has to flatten a two-dimensional grid into a one-dimensional sequence, and the choice is consequential.</p>
<div id="tbl-serialisation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-serialisation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;30.3: Patterns for serialising an <span class="math inline">\(N_q\)</span>-level token grid.
</figcaption>
<div aria-describedby="tbl-serialisation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 42%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pattern</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Flattening</strong></td>
<td style="text-align: left;">Emit all <span class="math inline">\(N_q\)</span> levels of frame <span class="math inline">\(t\)</span>, then move to <span class="math inline">\(t+1\)</span>. One sequence, <span class="math inline">\(T_c \cdot N_q\)</span> long</td>
<td style="text-align: left;">Multiplies sequence length by <span class="math inline">\(N_q\)</span>, undoing much of the compression</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Parallel</strong></td>
<td style="text-align: left;">Predict all <span class="math inline">\(N_q\)</span> levels of a frame simultaneously from one hidden state</td>
<td style="text-align: left;">Sequence length <span class="math inline">\(T_c\)</span>, but assumes conditional independence across levels within a frame</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Delay / interleaving</strong></td>
<td style="text-align: left;">Emit level <span class="math inline">\(n\)</span> offset by <span class="math inline">\(n-1\)</span> frames, so each step predicts a diagonal of the grid</td>
<td style="text-align: left;">Sequence length <span class="math inline">\(T_c + N_q\)</span>; level <span class="math inline">\(n\)</span> can condition on level <span class="math inline">\(n-1\)</span> of the same frame</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Depth transformer</strong></td>
<td style="text-align: left;">Large temporal backbone per frame, small autoregressive transformer over the <span class="math inline">\(N_q\)</span> levels within it</td>
<td style="text-align: left;">Exact factorisation, no independence assumption; extra module and per-frame serial cost</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Multi-token prediction</strong></td>
<td style="text-align: left;">Separate output heads emit all levels at once, trained jointly</td>
<td style="text-align: left;">Fast; recovers some cross-level dependency through shared representation</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The tension is a factorisation question. The exact joint is <span class="math inline">\(p(\mathbf{c}_t) = \prod_{n} p(c_{t,n} \mid c_{t,&lt;n}, \mathbf{c}_{&lt;t})\)</span>. Flattening represents it exactly at maximum sequence-length cost; the parallel pattern drops the within-frame dependency entirely, which is cheap but wrong (the levels of an RVQ frame are strongly dependent by construction, since each codes the residual of the previous); delay patterns and depth transformers are the compromises.</p>
<p>The <strong>delay pattern</strong> was popularised by MusicGen <span class="citation" data-cites="copet2024musicgen">(<a href="../../references.html#ref-copet2024musicgen" role="doc-biblioref">Copet et al. 2023</a>)</span>, whose figure comparing flattening, parallel, and delayed interleaving is the standard reference diagram for this material. The <strong>depth transformer</strong> comes from the RQ-Transformer <span class="citation" data-cites="lee2022rqvae">(<a href="../../references.html#ref-lee2022rqvae" role="doc-biblioref">Lee et al. 2022</a>)</span> and reached speech through Moshi <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span>, where a 7B temporal backbone predicts one frame’s context and a small depth transformer autoregresses over that frame’s eight levels. Sesame’s CSM uses the same split with per-codebook linear heads, and VALL-E’s AR/NAR pair (<a href="25-speech-synthesis.html#eq-valle" class="quarto-xref">Equation&nbsp;<span>31.11</span></a>) is yet another point in this space — autoregressive over time for level 1, parallel over depth for the rest.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>No convention has emerged
</div>
</div>
<div class="callout-body-container callout-body">
<p>As of 2026 there is no standard. Every major system picks differently, and the schemes have grown more elaborate rather than converging. This is a reliable signal that the community has not found the right abstraction — and it is a strong argument for single-codebook codecs, which dissolve the problem instead of solving it.</p>
</div>
</div>
</section>
<section id="sec-codec-inside" class="level2" data-number="30.9">
<h2 data-number="30.9" class="anchored" data-anchor-id="sec-codec-inside"><span class="header-section-number">30.9</span> What Is Actually Inside the Tokens?</h2>
<p>The account above is tidy: level 1 is semantic, higher levels are acoustic, identity and prosody live somewhere in the middle. How much of that survives measurement?</p>
<p>A 2025 interpretability study <span class="citation" data-cites="sadok2025interpretability">(<a href="../../references.html#ref-sadok2025interpretability" role="doc-biblioref">Sadok et al. 2025</a>)</span> tests it directly across four codecs with contrasting designs — DAC (pure reconstruction), SpeechTokenizer (HuBERT-distilled RVQ), Mimi (split RVQ), and BigCodec (single large VQ) — by tokenising LibriSpeech <code>test-clean</code> and measuring co-occurrence between codec tokens and HuBERT’s 100 discrete units, plus <span class="math inline">\(t\)</span>-SNE structure and mutual information estimated by a contrastive log-ratio bound.</p>
<div id="tbl-codec-inside" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-codec-inside-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;30.4: Empirical findings on the content of codec tokens.
</figcaption>
<div aria-describedby="tbl-codec-inside-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Finding</th>
<th style="text-align: left;">Detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No deterministic token mapping</td>
<td style="text-align: left;">Codec tokens do not map one-to-one onto phonetic units; the best single-token association for BigCodec is about 8%. Codes take meaning from context, like words in translation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distillation works, as designed</td>
<td style="text-align: left;">SpeechTokenizer’s level 1 aligns strongly with HuBERT units and shows clean <span class="math inline">\(t\)</span>-SNE clusters by phonetic class; DAC’s level 1 aligns best among its levels, degrading with depth</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Leakage persists</strong></td>
<td style="text-align: left;">SpeechTokenizer’s <em>residual</em> levels also carry linguistic content; Mimi’s split RVQ, designed to prevent exactly this, still shows substantial content in higher levels — plausibly because 12.5 Hz frames each span several phonetic units</td>
</tr>
<tr class="even">
<td style="text-align: left;">Identity lives in the middle</td>
<td style="text-align: left;">Speaker identity is barely present in SpeechTokenizer level 1, strongly present at level 4, still present at level 8</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Pitch is the hardest</strong></td>
<td style="text-align: left;">Pitch shows essentially no interpretable structure in the embedding space, and the lowest mutual information of the three attributes</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The conclusion is that content, identity, and pitch are <strong>entangled in the quantised latent space even in codecs explicitly designed for disentanglement</strong>. The semantic/acoustic story is a real and useful tendency, not a clean factorisation.</p>
<p>This matters practically in both directions. It explains why speaker identity leaks into “semantic” tokens and why voice conversion by naive token surgery does not work cleanly. And it motivates the factorised codecs behind the fourth generation of voice cloning in <a href="25-speech-synthesis.html#sec-cloning" class="quarto-xref"><span>Section 31.10</span></a> — NaturalSpeech 3’s FACodec <span class="citation" data-cites="ju2024naturalspeech3">(<a href="../../references.html#ref-ju2024naturalspeech3" role="doc-biblioref">Ju et al. 2024</a>)</span> and Spark-TTS’s BiCodec <span class="citation" data-cites="wang2025sparktts">(<a href="../../references.html#ref-wang2025sparktts" role="doc-biblioref">Wang et al. 2025</a>)</span> — which impose disentanglement through explicit supervision, gradient reversal, and information bottlenecks rather than hoping it emerges from residual structure. Source-disentangled codecs <span class="citation" data-cites="bie2024sdcodec">(<a href="../../references.html#ref-bie2024sdcodec" role="doc-biblioref">Bie et al. 2024</a>)</span> pursue the same goal with domain-specific codebooks. The same paper offers a post-hoc route: train a masked encoder-decoder that maps bidirectionally between codec tokens and interpretable attributes (content, pitch, loudness, speaker), which both explains the tokens and enables controlled editing — swapping the speaker attribute performs voice conversion.</p>
<p>The pitch result is the one I would flag for a reader. Pitch is perceptually salient, prosodically essential, and is the attribute a reconstruction objective has least reason to represent explicitly, since it can be reproduced implicitly. If you want prosodic control, do not expect the codec to hand it to you.</p>
</section>
<section id="sec-codec-eval" class="level2" data-number="30.10">
<h2 data-number="30.10" class="anchored" data-anchor-id="sec-codec-eval"><span class="header-section-number">30.10</span> Evaluation</h2>
<p>Codecs suffer a version of the evaluation problem already seen in <a href="25-speech-synthesis.html#sec-tts-eval" class="quarto-xref"><span>Section 31.12</span></a>, with a specific twist: <strong>reconstruction quality and downstream modelling utility are different objectives, and they can be anti-correlated.</strong></p>
<p><strong>Reconstruction metrics</strong> are the mature half. Mel distance (<span class="math inline">\(L_1\)</span> on log-mel), ViSQOL <span class="citation" data-cites="chinen2020visqol">(<a href="../../references.html#ref-chinen2020visqol" role="doc-biblioref">Chinen et al. 2020</a>)</span> and PESQ for perceptual quality, STOI for intelligibility, SI-SDR for waveform alignment (with the caveat above that it is meaningless across differing objectives), and MUSHRA or P.808 listening tests. Codebook entropy and utilisation measure how much of the nominal bitrate is actually used.</p>
<p><strong>Downstream utility</strong> is what a speech LLM builder needs and is far less settled. Two benchmarks address it. <strong>Codec-SUPERB</strong> <span class="citation" data-cites="wu2024codecsuperb">(<a href="../../references.html#ref-wu2024codecsuperb" role="doc-biblioref">Wu et al. 2024</a>)</span> evaluates codecs by how well downstream models perform on resynthesised audio across recognition, speaker, and content tasks. <strong>DASB</strong> <span class="citation" data-cites="mousavi2024dasb">(<a href="../../references.html#ref-mousavi2024dasb" role="doc-biblioref">Mousavi et al. 2024</a>)</span> ranks discrete audio tokens across discriminative and generative tasks, and reports the result this section is built around: <strong>semantic tokens generally outperform compression-optimised acoustic tokens on downstream tasks, while continuous representations still outperform both.</strong></p>
<p>Two consequences worth stating plainly. A codec that wins on ViSQOL may lose as a tokeniser, so reconstruction leaderboards do not rank tokenisers. And the finding from the tonal study <span class="citation" data-cites="mondal2026tonal">(<a href="../../references.html#ref-mondal2026tonal" role="doc-biblioref">Mondal and Gupta 2026</a>)</span> that higher-fidelity codecs yield embeddings correlating somewhat better with human judgement — while both remain below purpose-built contrastive audio encoders — is a useful reminder that “the codec’s latent space” and “a good audio representation” are related but not the same object.</p>
<p>Toolkits: <strong>ESPnet-Codec</strong> <span class="citation" data-cites="shi2024espnetcodec">(<a href="../../references.html#ref-shi2024espnetcodec" role="doc-biblioref">Shi et al. 2024</a>)</span> provides training and evaluation across codecs with a unified metric suite, and <strong>FunCodec</strong> <span class="citation" data-cites="du2023funcodec">(<a href="../../references.html#ref-du2023funcodec" role="doc-biblioref">Du et al. 2023</a>)</span> offers reproducible multi-rate models.</p>
</section>
<section id="sec-continuous-alt" class="level2" data-number="30.11">
<h2 data-number="30.11" class="anchored" data-anchor-id="sec-continuous-alt"><span class="header-section-number">30.11</span> Do We Need Discrete Tokens at All?</h2>
<p>The entire chapter rests on a premise worth interrogating, especially since <a href="25-speech-synthesis.html#sec-continuous-ar" class="quarto-xref"><span>Section 31.9.5</span></a> already showed it is contestable in synthesis.</p>
<p>The case <em>for</em> discreteness is architectural rather than representational. Discrete tokens let you reuse the language-modelling stack unchanged: categorical cross-entropy, sampling with temperature and nucleus filtering, KV caching, pretrained text-LLM weights, and preference optimisation. That is a large amount of borrowed infrastructure, and it is the entire reason the paradigm exists.</p>
<p>The case <em>against</em> is that quantisation destroys information for no modelling reason. DASB’s finding that continuous representations beat discrete tokens on downstream tasks is direct evidence. MELLE (<a href="25-speech-synthesis.html#sec-continuous-ar" class="quarto-xref"><span>Section 31.9.5</span></a>) generates continuous mel frames autoregressively and is <em>more</em> robust than its discrete-token counterpart. And a growing line of work generates continuous audio latents with a small diffusion or flow-matching head per step, keeping autoregression over time while discarding quantisation.</p>
<p>The honest position is that discreteness is an engineering convenience whose representational cost is real and whose necessity is unproven. It is the same open question raised at the end of <a href="21-speech-representation-learning.html#sec-ssl-open" class="quarto-xref"><span>Section 27.9</span></a>, arriving from the generative side.</p>
</section>
<section id="sec-codec-open" class="level2" data-number="30.12">
<h2 data-number="30.12" class="anchored" data-anchor-id="sec-codec-open"><span class="header-section-number">30.12</span> Open Problems</h2>
<ol type="1">
<li><strong>The fidelity/modellability trade-off is unquantified.</strong> Everyone knows lower frame rates make sequences easier to model and reconstructions worse. Nobody can predict where the optimum sits for a given downstream model and compute budget, and there is no theory relating the two.</li>
<li><strong>Disentanglement remains aspirational.</strong> As <a href="#sec-codec-inside" class="quarto-xref"><span>Section 30.9</span></a> shows, even codecs built for it leak. Whether clean factorisation into content, speaker, prosody, and channel is achievable without heavy explicit supervision is open.</li>
<li><strong>Serialisation has no principled answer.</strong> <a href="#tbl-serialisation" class="quarto-xref">Table&nbsp;<span>30.3</span></a> is a list of engineering compromises, not a solution. Single-codebook codecs sidestep it, which may be the real lesson.</li>
<li><strong>Pitch and prosody are under-represented.</strong> A reconstruction objective has no reason to encode them explicitly, and measurement confirms it does not.</li>
<li><strong>Content-dependent failure is under-studied.</strong> Tonal material is one documented case <span class="citation" data-cites="mondal2026tonal">(<a href="../../references.html#ref-mondal2026tonal" role="doc-biblioref">Mondal and Gupta 2026</a>)</span>; the general question of which signal classes a codec systematically mishandles, and whether that is a data problem or a capacity problem, is largely unexplored. Aggregate metrics hide it by construction.</li>
<li><strong>Evaluation for tokenisers, not compressors.</strong> Codec-SUPERB and DASB are starts, but there is no accepted way to predict how a codec will behave inside a speech LLM without training one.</li>
<li><strong>Streaming and latency constraints.</strong> Causality, low algorithmic delay, and cheap decoding are required for duplex dialogue and constrain everything else; Mimi’s sub-10 ms CPU decode is the target to beat.</li>
<li><strong>Non-speech audio and general audio.</strong> Most speech codecs degrade on music and environmental sound. Whether one tokeniser should serve all audio, or whether domain-specific codecs are the right answer, is unsettled.</li>
</ol>
</section>
<section id="summary" class="level2" data-number="30.13">
<h2 data-number="30.13" class="anchored" data-anchor-id="summary"><span class="header-section-number">30.13</span> Summary</h2>
<p>A neural audio codec is an encoder, a quantiser, and a decoder, trained end-to-end with spectral, adversarial, feature-matching, and commitment losses. It exists because language models need discrete tokens at a manageable rate: sample-level modelling puts less than one word inside a typical context window, which is a failure of coherence no amount of training repairs.</p>
<p>The technical core is vector quantisation made trainable. The <span class="math inline">\(\arg\min\)</span> lookup has no gradient, so the straight-through estimator copies the gradient past it; the commitment loss keeps that approximation honest by pulling latents toward their codes; EMA updates and dead-code reinitialisation keep the codebook alive. Residual quantisation then buys exponential vocabulary from linear storage by quantising each stage’s error, which incidentally orders the levels by importance and makes bitrate truncatable — and which produces the two-dimensional token grid that every downstream language model must serialise, with no consensus on how.</p>
<p>Codebook collapse is the recurring adversary, and the progression of fixes — diversity losses, EMA and dead-code reinitialisation, factorised and normalised lookup, and finally finite scalar quantisation, which removes the codebook entirely — is the same movement toward structural rather than corrective solutions seen in <a href="21-speech-representation-learning.html#sec-ssl-compare" class="quarto-xref"><span>Section 27.4.1</span></a>.</p>
<p>Two ideas deserve to be carried forward. The <strong>semantic/acoustic split</strong>, now usually folded inside the codec by distilling a self-supervised model into the first level, is what makes speech language modelling a linguistic rather than an acoustic act; holding semantic tokens fixed while resampling the rest yields the same words in a different voice, which is the cleanest demonstration available of what these representations contain. And the <strong>empirical caveat</strong> to that story: measurement shows content, identity, and pitch remain entangled even in codecs designed to separate them, with pitch the least represented of all.</p>
<p><a href="26-speech-language-models.html" class="quarto-xref"><span>Chapter 32</span></a> takes the token grid as an interface and asks what happens when a language model is trained to read and write it — and why, so far, doing so makes the language model worse at thinking.</p>
</section>
<section id="sec-codec-sources" class="level2" data-number="30.14">
<h2 data-number="30.14" class="anchored" data-anchor-id="sec-codec-sources"><span class="header-section-number">30.14</span> Sources and Further Reading</h2>
<p>Where this chapter’s exposition, figures, and equations come from, section by section. Diagrams and audio examples are best consulted in the originals.</p>
<div id="tbl-codec-sources" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-codec-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;30.5: Source attribution by section.
</figcaption>
<div aria-describedby="tbl-codec-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Section</th>
<th style="text-align: left;">Primary sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="#sec-codec-why" class="quarto-xref"><span>Section 30.1</span></a></td>
<td style="text-align: left;">The sample-level failure experiment, token-rate arithmetic, and audio examples are from Volhejn’s Kyutai explainer, <a href="https://kyutai.org/codec-explainer/"><em>Neural audio codecs: how to get audio into LLMs</em></a> (2025). WaveNet’s sample-rate animation is in the <a href="https://deepmind.google/discover/blog/wavenet-a-generative-model-for-raw-audio/">DeepMind WaveNet post</a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="#sec-vqvae" class="quarto-xref"><span>Section 30.2</span></a>, <a href="#sec-ste" class="quarto-xref"><span>Section 30.2.1</span></a>, <a href="#sec-vq-loss" class="quarto-xref"><span>Section 30.2.2</span></a></td>
<td style="text-align: left;">Original formulation: VQ-VAE <span class="citation" data-cites="vandenoord2017vqvae">(<a href="../../references.html#ref-vandenoord2017vqvae" role="doc-biblioref">Oord et al. 2017</a>)</span>; EMA updates <span class="citation" data-cites="razavi2019vqvae2">(<a href="../../references.html#ref-razavi2019vqvae2" role="doc-biblioref">Razavi et al. 2019</a>)</span>. The Fashion-MNIST intuition, the animated latent-space visualisations, the straight-through code snippets, and the “teleporting” dead-code metaphor are all from the Kyutai explainer, which is the best pedagogical treatment I know of</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="#sec-rvq" class="quarto-xref"><span>Section 30.3</span></a></td>
<td style="text-align: left;">RVQ for audio: SoundStream <span class="citation" data-cites="zeghidour2022soundstream">(<a href="../../references.html#ref-zeghidour2022soundstream" role="doc-biblioref">Zeghidour et al. 2022</a>)</span>. The residual-quantisation animation and pseudocode are from the Kyutai explainer. Image-domain parallel: RQ-VAE <span class="citation" data-cites="lee2022rqvae">(<a href="../../references.html#ref-lee2022rqvae" role="doc-biblioref">Lee et al. 2022</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="#sec-collapse" class="quarto-xref"><span>Section 30.4</span></a></td>
<td style="text-align: left;">DAC’s factorised and <span class="math inline">\(L_2\)</span>-normalised lookup <span class="citation" data-cites="kumar2023dac">(<a href="../../references.html#ref-kumar2023dac" role="doc-biblioref">Kumar et al. 2023</a>)</span>; FSQ <span class="citation" data-cites="mentzer2024fsq">(<a href="../../references.html#ref-mentzer2024fsq" role="doc-biblioref">Mentzer et al. 2024</a>)</span>; single-codebook designs <span class="citation" data-cites="xin2024bigcodec ji2025wavtokenizer">(<a href="../../references.html#ref-xin2024bigcodec" role="doc-biblioref">Xin et al. 2024</a>; <a href="../../references.html#ref-ji2025wavtokenizer" role="doc-biblioref">Ji et al. 2025</a>)</span>. A compact mathematical survey of quantiser variants is <a href="https://www.emergentmind.com/topics/neural-audio-codecs-nacs">EmergentMind’s <em>Neural Audio Codecs</em> overview</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="#sec-entropy" class="quarto-xref"><span>Section 30.4.1</span></a></td>
<td style="text-align: left;">Per-layer entropy profiles, the tonal-weakness taxonomy, and the utilisation figures are from <span class="citation" data-cites="mondal2026tonal">(<a href="../../references.html#ref-mondal2026tonal" role="doc-biblioref">Mondal and Gupta 2026</a>)</span> (<em>Scientific Reports</em>, 2026), read with the scale caveat noted in the text</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="#sec-codec-losses" class="quarto-xref"><span>Section 30.5</span></a></td>
<td style="text-align: left;">Loss composition and weights follow DAC <span class="citation" data-cites="kumar2023dac">(<a href="../../references.html#ref-kumar2023dac" role="doc-biblioref">Kumar et al. 2023</a>)</span> and EnCodec <span class="citation" data-cites="defossez2023encodec">(<a href="../../references.html#ref-defossez2023encodec" role="doc-biblioref">Défossez et al. 2023</a>)</span>, inheriting discriminator design from HiFi-GAN <span class="citation" data-cites="kong2020hifigan">(<a href="../../references.html#ref-kong2020hifigan" role="doc-biblioref">Kong et al. 2020</a>)</span> and MelGAN <span class="citation" data-cites="kumar2019melgan">(<a href="../../references.html#ref-kumar2019melgan" role="doc-biblioref">Kumar et al. 2019</a>)</span>. On audio loss functions generally, the Kyutai explainer recommends Evan Radkoff’s <a href="https://radkoff.github.io/">blog post on audio ML losses</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="#sec-codec-zoo" class="quarto-xref"><span>Section 30.6</span></a></td>
<td style="text-align: left;">Individual papers as cited. The EmergentMind overview gives a broader survey including psychoacoustic-loss and source-disentangled codecs <span class="citation" data-cites="bie2024sdcodec">(<a href="../../references.html#ref-bie2024sdcodec" role="doc-biblioref">Bie et al. 2024</a>)</span> not covered here</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="#sec-semantic-acoustic" class="quarto-xref"><span>Section 30.7</span></a></td>
<td style="text-align: left;">Semantic distillation: SpeechTokenizer <span class="citation" data-cites="zhang2024speechtokenizer">(<a href="../../references.html#ref-zhang2024speechtokenizer" role="doc-biblioref">Zhang et al. 2024</a>)</span>, Mimi <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span>. The teacher-forced semantic-token experiment (“same words, different voice”), with listenable audio, is from the Kyutai explainer. Discrete units for language modelling originate in GSLM <span class="citation" data-cites="lakhotia2021gslm">(<a href="../../references.html#ref-lakhotia2021gslm" role="doc-biblioref">Lakhotia et al. 2021</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="#sec-serialisation" class="quarto-xref"><span>Section 30.8</span></a></td>
<td style="text-align: left;">The canonical comparison figure of flattening, parallel, and delay patterns is Figure 1 of MusicGen <span class="citation" data-cites="copet2024musicgen">(<a href="../../references.html#ref-copet2024musicgen" role="doc-biblioref">Copet et al. 2023</a>)</span>. Depth transformers: RQ-Transformer <span class="citation" data-cites="lee2022rqvae">(<a href="../../references.html#ref-lee2022rqvae" role="doc-biblioref">Lee et al. 2022</a>)</span> and Moshi <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span>. The Kyutai explainer reproduces the MusicGen figure and shows a more elaborate 2025 scheme</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="#sec-codec-inside" class="quarto-xref"><span>Section 30.9</span></a></td>
<td style="text-align: left;">Entirely from <span class="citation" data-cites="sadok2025interpretability">(<a href="../../references.html#ref-sadok2025interpretability" role="doc-biblioref">Sadok et al. 2025</a>)</span>, <a href="https://arxiv.org/abs/2506.04492"><em>Bringing Interpretability to Neural Audio Codecs</em></a>. Its Figures 2–6 (<span class="math inline">\(t\)</span>-SNE by phonetic class, speaker, and pitch; mutual-information histogram) are worth consulting directly — they are the visual argument for the entanglement claim</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="#sec-codec-eval" class="quarto-xref"><span>Section 30.10</span></a></td>
<td style="text-align: left;">Codec-SUPERB <span class="citation" data-cites="wu2024codecsuperb">(<a href="../../references.html#ref-wu2024codecsuperb" role="doc-biblioref">Wu et al. 2024</a>)</span>; DASB <span class="citation" data-cites="mousavi2024dasb">(<a href="../../references.html#ref-mousavi2024dasb" role="doc-biblioref">Mousavi et al. 2024</a>)</span>; ViSQOL <span class="citation" data-cites="chinen2020visqol">(<a href="../../references.html#ref-chinen2020visqol" role="doc-biblioref">Chinen et al. 2020</a>)</span>; toolkits <span class="citation" data-cites="shi2024espnetcodec du2023funcodec">(<a href="../../references.html#ref-shi2024espnetcodec" role="doc-biblioref">Shi et al. 2024</a>; <a href="../../references.html#ref-du2023funcodec" role="doc-biblioref">Du et al. 2023</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="#sec-continuous-alt" class="quarto-xref"><span>Section 30.11</span></a></td>
<td style="text-align: left;">DASB’s continuous-versus-discrete finding <span class="citation" data-cites="mousavi2024dasb">(<a href="../../references.html#ref-mousavi2024dasb" role="doc-biblioref">Mousavi et al. 2024</a>)</span>; MELLE <span class="citation" data-cites="meng2024melle">(<a href="../../references.html#ref-meng2024melle" role="doc-biblioref">Meng et al. 2024</a>)</span>. Sander Dieleman’s <a href="https://sander.ai/2025/04/15/latents.html"><em>Generative modelling in latent space</em></a> is the best high-level treatment of when to quantise</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bie2024sdcodec" class="csl-entry" role="listitem">
Bie, Xiaoyu, Xubo Liu, and Gaël Richard. 2024. <span>“Learning Source Disentanglement in Neural Audio Codec.”</span> <em>arXiv Preprint arXiv:2409.11228</em>. <a href="https://arxiv.org/abs/2409.11228">https://arxiv.org/abs/2409.11228</a>.
</div>
<div id="ref-chinen2020visqol" class="csl-entry" role="listitem">
Chinen, Michael, Felicia S. C. Lim, Jan Skoglund, Nikita Gureev, Feargus O’Gorman, and Andrew Hines. 2020. <span>“<span>ViSQOL</span> V3: An Open Source Production Ready Objective Speech and Audio Metric.”</span> <em>Proc. International Conference on Quality of Multimedia Experience (QoMEX)</em>, 1–6.
</div>
<div id="ref-copet2024musicgen" class="csl-entry" role="listitem">
Copet, Jade, Felix Kreuk, Itai Gat, et al. 2023. <span>“Simple and Controllable Music Generation.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em> 36. <a href="https://arxiv.org/abs/2306.05284">https://arxiv.org/abs/2306.05284</a>.
</div>
<div id="ref-defossez2023encodec" class="csl-entry" role="listitem">
Défossez, Alexandre, Jade Copet, Gabriel Synnaeve, and Yossi Adi. 2023. <span>“High Fidelity Neural Audio Compression.”</span> <em>Transactions on Machine Learning Research (TMLR)</em>.
</div>
<div id="ref-defossez2024moshi" class="csl-entry" role="listitem">
Défossez, Alexandre, Laurent Mazaré, Manu Orsini, et al. 2024. <span>“<span>Moshi</span>: A Speech-Text Foundation Model for Real-Time Dialogue.”</span> <em>arXiv Preprint arXiv:2410.00037</em>.
</div>
<div id="ref-du2023funcodec" class="csl-entry" role="listitem">
Du, Zhihao, Shiliang Zhang, Kai Hu, and Siqi Zheng. 2023. <span>“<span>FunCodec</span>: A Fundamental, Reproducible and Integrable Open-Source Toolkit for Neural Speech Codec.”</span> <em>arXiv Preprint arXiv:2309.07405</em>. <a href="https://arxiv.org/abs/2309.07405">https://arxiv.org/abs/2309.07405</a>.
</div>
<div id="ref-esser2021vqgan" class="csl-entry" role="listitem">
Esser, Patrick, Robin Rombach, and Björn Ommer. 2021. <span>“Taming Transformers for High-Resolution Image Synthesis.”</span> <em>Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)</em>.
</div>
<div id="ref-ji2025wavtokenizer" class="csl-entry" role="listitem">
Ji, Shengpeng, Ziyue Jiang, Wen Wang, et al. 2025. <span>“<span>WavTokenizer</span>: An Efficient Acoustic Discrete Codec Tokenizer for Audio Language Modeling.”</span> <em>Proc. International Conference on Learning Representations (ICLR)</em>. <a href="https://arxiv.org/abs/2408.16532">https://arxiv.org/abs/2408.16532</a>.
</div>
<div id="ref-ju2024naturalspeech3" class="csl-entry" role="listitem">
Ju, Zeqian, Yuancheng Wang, Kai Shen, et al. 2024. <span>“<span>NaturalSpeech 3</span>: Zero-Shot Speech Synthesis with Factorized Codec and Diffusion Models.”</span> <em>International Conference on Machine Learning (ICML)</em>.
</div>
<div id="ref-kong2020hifigan" class="csl-entry" role="listitem">
Kong, Jungil, Jaehyeon Kim, and Jaekyoung Bae. 2020. <span>“<span>HiFi-GAN</span>: Generative Adversarial Networks for Efficient and High Fidelity Speech Synthesis.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-kumar2019melgan" class="csl-entry" role="listitem">
Kumar, Kundan, Rithesh Kumar, Thibault de Boissiere, et al. 2019. <span>“<span>MelGAN</span>: Generative Adversarial Networks for Conditional Waveform Synthesis.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-kumar2023dac" class="csl-entry" role="listitem">
Kumar, Rithesh, Prem Seetharaman, Alejandro Luebs, Ishaan Kumar, and Kundan Kumar. 2023. <span>“High-Fidelity Audio Compression with Improved <span>RVQGAN</span>.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-lakhotia2021gslm" class="csl-entry" role="listitem">
Lakhotia, Kushal, Eugene Kharitonov, Wei-Ning Hsu, et al. 2021. <span>“On Generative Spoken Language Modeling from Raw Audio.”</span> <em>Transactions of the Association for Computational Linguistics (TACL)</em> 9: 1336–54. <a href="https://arxiv.org/abs/2102.01192">https://arxiv.org/abs/2102.01192</a>.
</div>
<div id="ref-lee2022rqvae" class="csl-entry" role="listitem">
Lee, Doyup, Chiheon Kim, Saehoon Kim, Minsu Cho, and Wook-Shin Han. 2022. <span>“Autoregressive Image Generation Using Residual Quantization.”</span> <em>Proc. IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)</em>. <a href="https://arxiv.org/abs/2203.01941">https://arxiv.org/abs/2203.01941</a>.
</div>
<div id="ref-meng2024melle" class="csl-entry" role="listitem">
Meng, Lingwei, Long Zhou, Shujie Liu, et al. 2024. <span>“Autoregressive Speech Synthesis Without Vector Quantization.”</span> <em>arXiv Preprint arXiv:2407.08551</em>.
</div>
<div id="ref-mentzer2024fsq" class="csl-entry" role="listitem">
Mentzer, Fabian, David Minnen, Eirikur Agustsson, and Michael Tschannen. 2024. <span>“Finite Scalar Quantization: <span>VQ-VAE</span> Made Simple.”</span> <em>Proc. International Conference on Learning Representations (ICLR)</em>. <a href="https://arxiv.org/abs/2309.15505">https://arxiv.org/abs/2309.15505</a>.
</div>
<div id="ref-mondal2026tonal" class="csl-entry" role="listitem">
Mondal, Abhinav, and Rishi Gupta. 2026. <span>“Addressing Tonal Weaknesses in Neural Audio Codecs Through Synthetic Data Augmentation and Balanced Training.”</span> <em>Scientific Reports</em>, ahead of print. <a href="https://doi.org/10.1038/s41598-026-66022-1">https://doi.org/10.1038/s41598-026-66022-1</a>.
</div>
<div id="ref-mousavi2024dasb" class="csl-entry" role="listitem">
Mousavi, Pooneh, Luca Della Libera, Jarod Duret, Artem Ploujnikov, Cem Subakan, and Mirco Ravanelli. 2024. <span>“<span>DASB</span> – Discrete Audio and Speech Benchmark.”</span> <em>arXiv Preprint arXiv:2406.14294</em>. <a href="https://arxiv.org/abs/2406.14294">https://arxiv.org/abs/2406.14294</a>.
</div>
<div id="ref-vandenoord2017vqvae" class="csl-entry" role="listitem">
Oord, Aaron van den, Oriol Vinyals, and Koray Kavukcuoglu. 2017. <span>“Neural Discrete Representation Learning.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-razavi2019vqvae2" class="csl-entry" role="listitem">
Razavi, Ali, Aäron van den Oord, and Oriol Vinyals. 2019. <span>“Generating Diverse High-Fidelity Images with <span>VQ-VAE-2</span>.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em> 32. <a href="https://arxiv.org/abs/1906.00446">https://arxiv.org/abs/1906.00446</a>.
</div>
<div id="ref-sadok2025interpretability" class="csl-entry" role="listitem">
Sadok, Samir, Julien Hauret, and Éric Bavu. 2025. <span>“Bringing Interpretability to Neural Audio Codecs.”</span> <em>Proc. Interspeech</em>. <a href="https://arxiv.org/abs/2506.04492">https://arxiv.org/abs/2506.04492</a>.
</div>
<div id="ref-shi2024espnetcodec" class="csl-entry" role="listitem">
Shi, Jiatong, Jinchuan Tian, Yihan Wu, et al. 2024. <span>“<span>ESPnet-Codec</span>: Comprehensive Training and Evaluation of Neural Codecs for Audio, Music, and Speech.”</span> <em>Proc. IEEE Spoken Language Technology Workshop (SLT)</em>. <a href="https://arxiv.org/abs/2409.15897">https://arxiv.org/abs/2409.15897</a>.
</div>
<div id="ref-siuzdak2024snac" class="csl-entry" role="listitem">
Siuzdak, Hubert, Florian Grötschla, and Luca A. Lanzendörfer. 2024. <span>“<span>SNAC</span>: Multi-Scale Neural Audio Codec.”</span> <em>arXiv Preprint arXiv:2410.14411</em>. <a href="https://arxiv.org/abs/2410.14411">https://arxiv.org/abs/2410.14411</a>.
</div>
<div id="ref-wang2025sparktts" class="csl-entry" role="listitem">
Wang, Xinsheng, Mingqi Jiang, Ziyang Ma, et al. 2025. <span>“<span>Spark-TTS</span>: An Efficient LLM-Based Text-to-Speech Model with Single-Stream Decoupled Speech Tokens.”</span> <em>arXiv Preprint arXiv:2503.01710</em>.
</div>
<div id="ref-wu2024codecsuperb" class="csl-entry" role="listitem">
Wu, Haibin, Ho-Lam Chung, Yi-Cheng Lin, et al. 2024. <span>“<span>Codec-SUPERB</span>: An in-Depth Analysis of Sound Codec Models.”</span> <em>arXiv Preprint arXiv:2402.13071</em>. <a href="https://arxiv.org/abs/2402.13071">https://arxiv.org/abs/2402.13071</a>.
</div>
<div id="ref-xin2024bigcodec" class="csl-entry" role="listitem">
Xin, Detai, Xu Tan, Shinnosuke Takamichi, and Hiroshi Saruwatari. 2024. <span>“<span>BigCodec</span>: Pushing the Limits of Low-Bitrate Neural Speech Codec.”</span> <em>arXiv Preprint arXiv:2409.05377</em>. <a href="https://arxiv.org/abs/2409.05377">https://arxiv.org/abs/2409.05377</a>.
</div>
<div id="ref-ye2025llasa" class="csl-entry" role="listitem">
Ye, Zhen, Xinfa Zhu, Chi-Min Chan, et al. 2025. <span>“<span>Llasa</span>: Scaling Train-Time and Inference-Time Compute for Llama-Based Speech Synthesis.”</span> <em>arXiv Preprint arXiv:2502.04128</em>.
</div>
<div id="ref-zeghidour2022soundstream" class="csl-entry" role="listitem">
Zeghidour, Neil, Alejandro Luebs, Ahmed Omran, Jan Skoglund, and Marco Tagliasacchi. 2022. <span>“<span>SoundStream</span>: An End-to-End Neural Audio Codec.”</span> <em>IEEE/ACM Transactions on Audio, Speech, and Language Processing</em> 30.
</div>
<div id="ref-zhang2024speechtokenizer" class="csl-entry" role="listitem">
Zhang, Xin, Dong Zhang, Shimin Li, Yaqian Zhou, and Xipeng Qiu. 2024. <span>“<span>SpeechTokenizer</span>: Unified Speech Tokenizer for Speech Large Language Models.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const callouts = document.querySelectorAll('.callout-tip');
    callouts.forEach(function(callout) {
      callout.style.borderLeftColor = '#2196f3'; //#616161; //'#4caf50';
      callout.style.color = 'ffffff'; // Dark purple-gray text
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/audio/23-speaker-diarization.html" class="pagination-link" aria-label="Speaker Diarization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Speaker Diarization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/audio/25-speech-synthesis.html" class="pagination-link" aria-label="Speech Synthesis">
        <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Speech Synthesis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>