<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>31&nbsp; Speech Synthesis – deep_learning_notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/audio/26-speech-language-models.html" rel="next">
<link href="../../chapters/audio/24-neural-audio-codecs.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-fd0503e23dce65854c81c5baaade3bdf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/audio/25-speech-synthesis.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Speech Synthesis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">deep_learning_notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/_intro_foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-neural-networks-and-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Neural Networks and Optimization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-generalization-and-learning-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Generalization and Learning Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/_intro_computer_vision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computer Vision</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Visual Understanding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/03-cnns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Convolutional Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/04-object-detection-and-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Detection and Segmentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/05-vision-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Vision Transformers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/06-foundation-models-for-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Foundation Models for Segmentation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Self-Supervised Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/06-self-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Self-Supervised Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV: Generative Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/_intro-generative-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generative Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/07-vaes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Variational Autoencoders (VAEs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/08-gans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generative Adversarial Networks (GANs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision/09-diffusion-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diffusion Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/_conclusion-generative-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusion</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/_intro_video.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Video</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/10-video.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Video Fundamentals: Motion and Spatiotemporal Architectures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/11-video-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Video Understanding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/12-video-temporal-segmentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Video Temporal Segmentation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/13-video-understanding-benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Video Understanding Benchmarks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/video/14-video-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Video Generation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/_intro_3d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3D Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/11-3d-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">3D Data Understanding</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">3D Reconstruction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/12-3d-reconstruction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">3D Reconstruction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/13-gaussian-splatting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">3D Gaussian Splatting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Human Pose Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/3d/human_pose_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Human Pose Estimation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/_intro_nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Natural Language Processing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/17-text-representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Text Representation &amp; Word Embeddings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/18-sequence-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Sequence Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/19-large-language-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Large Language Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/nlp/20-text-embeddings-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Text Embedding Models &amp; Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision_language/_intro_vision_language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vision-Language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/vision_language/16-vision-language.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Vision-Language Multimodal Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/_intro_time_series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time Series</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/14-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Time Series Fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/time_series/15-deep-learning-for-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Deep Learning for Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/_intro_audio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Audio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/21-speech-representation-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Speech Representation Learning and Foundation Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/22-automatic-speech-recognition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Automatic Speech Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/23-speaker-diarization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Speaker Diarization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/24-neural-audio-codecs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Neural Audio Codecs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/25-speech-synthesis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Speech Synthesis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/26-speech-language-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Speech and Audio Language Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/audio/27-audio-understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Audio Understanding Beyond Words</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-tts-notation" id="toc-sec-tts-notation" class="nav-link active" data-scroll-target="#sec-tts-notation"><span class="header-section-number">31.1</span> Notation and Key Concepts</a>
  <ul class="collapse">
  <li><a href="#sec-tts-pipeline" id="toc-sec-tts-pipeline" class="nav-link" data-scroll-target="#sec-tts-pipeline"><span class="header-section-number">31.1.1</span> The Classical Decomposition</a></li>
  <li><a href="#sec-tts-mel" id="toc-sec-tts-mel" class="nav-link" data-scroll-target="#sec-tts-mel"><span class="header-section-number">31.1.2</span> Why Mel Spectrograms</a></li>
  </ul></li>
  <li><a href="#sec-onetomany" id="toc-sec-onetomany" class="nav-link" data-scroll-target="#sec-onetomany"><span class="header-section-number">31.2</span> The One-to-Many Problem</a>
  <ul class="collapse">
  <li><a href="#sec-oversmoothing" id="toc-sec-oversmoothing" class="nav-link" data-scroll-target="#sec-oversmoothing"><span class="header-section-number">31.2.1</span> Why Regression Fails</a></li>
  <li><a href="#sec-tts-strategies" id="toc-sec-tts-strategies" class="nav-link" data-scroll-target="#sec-tts-strategies"><span class="header-section-number">31.2.2</span> Three Strategies</a></li>
  </ul></li>
  <li><a href="#sec-tts-history" id="toc-sec-tts-history" class="nav-link" data-scroll-target="#sec-tts-history"><span class="header-section-number">31.3</span> Historical Overview</a></li>
  <li><a href="#sec-tts-classical" id="toc-sec-tts-classical" class="nav-link" data-scroll-target="#sec-tts-classical"><span class="header-section-number">31.4</span> Before Deep Learning</a></li>
  <li><a href="#sec-vocoders" id="toc-sec-vocoders" class="nav-link" data-scroll-target="#sec-vocoders"><span class="header-section-number">31.5</span> Neural Vocoders</a>
  <ul class="collapse">
  <li><a href="#sec-wavenet" id="toc-sec-wavenet" class="nav-link" data-scroll-target="#sec-wavenet"><span class="header-section-number">31.5.1</span> WaveNet and the Sequential Bottleneck</a></li>
  <li><a href="#sec-hifigan" id="toc-sec-hifigan" class="nav-link" data-scroll-target="#sec-hifigan"><span class="header-section-number">31.5.2</span> HiFi-GAN</a></li>
  </ul></li>
  <li><a href="#sec-tts-ar" id="toc-sec-tts-ar" class="nav-link" data-scroll-target="#sec-tts-ar"><span class="header-section-number">31.6</span> Autoregressive Acoustic Models</a>
  <ul class="collapse">
  <li><a href="#sec-tacotron" id="toc-sec-tacotron" class="nav-link" data-scroll-target="#sec-tacotron"><span class="header-section-number">31.6.1</span> Tacotron and Tacotron 2</a></li>
  <li><a href="#sec-attention-failures" id="toc-sec-attention-failures" class="nav-link" data-scroll-target="#sec-attention-failures"><span class="header-section-number">31.6.2</span> The Attention Failure Modes</a></li>
  </ul></li>
  <li><a href="#sec-duration" id="toc-sec-duration" class="nav-link" data-scroll-target="#sec-duration"><span class="header-section-number">31.7</span> Explicit Duration and Non-Autoregressive TTS</a>
  <ul class="collapse">
  <li><a href="#sec-fastspeech" id="toc-sec-fastspeech" class="nav-link" data-scroll-target="#sec-fastspeech"><span class="header-section-number">31.7.1</span> FastSpeech: Robustness by Construction</a></li>
  <li><a href="#sec-variance-adaptor" id="toc-sec-variance-adaptor" class="nav-link" data-scroll-target="#sec-variance-adaptor"><span class="header-section-number">31.7.2</span> FastSpeech 2 and the Variance Adaptor</a></li>
  <li><a href="#sec-mas" id="toc-sec-mas" class="nav-link" data-scroll-target="#sec-mas"><span class="header-section-number">31.7.3</span> Monotonic Alignment Search</a></li>
  <li><a href="#sec-vits" id="toc-sec-vits" class="nav-link" data-scroll-target="#sec-vits"><span class="header-section-number">31.7.4</span> VITS: One Model, One Objective</a></li>
  </ul></li>
  <li><a href="#sec-flow" id="toc-sec-flow" class="nav-link" data-scroll-target="#sec-flow"><span class="header-section-number">31.8</span> Diffusion and Flow Matching</a>
  <ul class="collapse">
  <li><a href="#sec-diffusion-tts" id="toc-sec-diffusion-tts" class="nav-link" data-scroll-target="#sec-diffusion-tts"><span class="header-section-number">31.8.1</span> From Diffusion to Straight Paths</a></li>
  <li><a href="#sec-voicebox" id="toc-sec-voicebox" class="nav-link" data-scroll-target="#sec-voicebox"><span class="header-section-number">31.8.2</span> Voicebox: Synthesis as Infilling</a></li>
  <li><a href="#sec-implicit-align" id="toc-sec-implicit-align" class="nav-link" data-scroll-target="#sec-implicit-align"><span class="header-section-number">31.8.3</span> Implicit Alignment: E2 TTS and F5-TTS</a></li>
  </ul></li>
  <li><a href="#sec-codec-lm" id="toc-sec-codec-lm" class="nav-link" data-scroll-target="#sec-codec-lm"><span class="header-section-number">31.9</span> Codec Tokens and Speech Language Models</a>
  <ul class="collapse">
  <li><a href="#sec-tokens" id="toc-sec-tokens" class="nav-link" data-scroll-target="#sec-tokens"><span class="header-section-number">31.9.1</span> Speech as a Sequence of Integers</a></li>
  <li><a href="#sec-audiolm" id="toc-sec-audiolm" class="nav-link" data-scroll-target="#sec-audiolm"><span class="header-section-number">31.9.2</span> AudioLM and the Semantic/Acoustic Split</a></li>
  <li><a href="#sec-valle" id="toc-sec-valle" class="nav-link" data-scroll-target="#sec-valle"><span class="header-section-number">31.9.3</span> VALL-E and In-Context Voice Cloning</a></li>
  <li><a href="#sec-cosyvoice" id="toc-sec-cosyvoice" class="nav-link" data-scroll-target="#sec-cosyvoice"><span class="header-section-number">31.9.4</span> The CosyVoice Template</a></li>
  <li><a href="#sec-continuous-ar" id="toc-sec-continuous-ar" class="nav-link" data-scroll-target="#sec-continuous-ar"><span class="header-section-number">31.9.5</span> The Continuous Counter-Current</a></li>
  <li><a href="#sec-tts-streaming" id="toc-sec-tts-streaming" class="nav-link" data-scroll-target="#sec-tts-streaming"><span class="header-section-number">31.9.6</span> Streaming and Duplex Speech</a></li>
  </ul></li>
  <li><a href="#sec-cloning" id="toc-sec-cloning" class="nav-link" data-scroll-target="#sec-cloning"><span class="header-section-number">31.10</span> Zero-Shot Voice Cloning</a></li>
  <li><a href="#sec-tts-opensource" id="toc-sec-tts-opensource" class="nav-link" data-scroll-target="#sec-tts-opensource"><span class="header-section-number">31.11</span> The Open-Source Landscape</a></li>
  <li><a href="#sec-tts-eval" id="toc-sec-tts-eval" class="nav-link" data-scroll-target="#sec-tts-eval"><span class="header-section-number">31.12</span> Evaluation</a>
  <ul class="collapse">
  <li><a href="#sec-mos" id="toc-sec-mos" class="nav-link" data-scroll-target="#sec-mos"><span class="header-section-number">31.12.1</span> Subjective Evaluation and the Limits of MOS</a></li>
  <li><a href="#sec-tts-objective" id="toc-sec-tts-objective" class="nav-link" data-scroll-target="#sec-tts-objective"><span class="header-section-number">31.12.2</span> Objective Metrics</a></li>
  <li><a href="#sec-tts-datasets" id="toc-sec-tts-datasets" class="nav-link" data-scroll-target="#sec-tts-datasets"><span class="header-section-number">31.12.3</span> Datasets and Protocols</a></li>
  <li><a href="#sec-tts-comparability" id="toc-sec-tts-comparability" class="nav-link" data-scroll-target="#sec-tts-comparability"><span class="header-section-number">31.12.4</span> The Comparability Problem</a></li>
  </ul></li>
  <li><a href="#sec-tts-open" id="toc-sec-tts-open" class="nav-link" data-scroll-target="#sec-tts-open"><span class="header-section-number">31.13</span> Open Problems</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">31.14</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-tts" class="quarto-section-identifier"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Speech Synthesis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Text-to-Speech (TTS) maps a written sentence to a spoken waveform. Given a token sequence <span class="math inline">\(\mathbf{y} = (y_1, \ldots, y_U)\)</span> the task is to produce <span class="math inline">\(\mathbf{x} = (x_1, \ldots, x_T) \in \mathbb{R}^{T}\)</span>, a waveform that a listener would accept as a natural rendering of <span class="math inline">\(\mathbf{y}\)</span>.</p>
<p>It is tempting to call this “ASR in reverse”, and the sequence-length arithmetic of <a href="22-automatic-speech-recognition.html" class="quarto-xref"><span>Chapter 28</span></a> does invert cleanly: a 25-token sentence becomes 160,000 samples rather than the other way round. But the inversion is not symmetric in the way that matters, and the asymmetry is the subject of this chapter.</p>
<p><strong>Recognition is many-to-one.</strong> Infinitely many waveforms — different speakers, accents, rooms, microphones, speaking rates — map to the same transcript. The target is essentially unique, so “correct” is well defined, an error rate can be computed by string edit distance, and supervised learning applies without philosophical difficulty.</p>
<p><strong>Synthesis is one-to-many.</strong> A single sentence admits infinitely many valid renderings, differing in prosody, timing, emphasis, breathing, voice quality, and recording channel. There is no unique correct output. The recorded audio that accompanies a sentence in a training corpus is <em>one sample</em> from <span class="math inline">\(p(\mathbf{x} \mid \mathbf{y})\)</span>, not the target.</p>
<p><span id="eq-tts-task"><span class="math display">\[
\mathbf{x} \sim p(\mathbf{x} \mid \mathbf{y}),
\qquad p(\mathbf{x} \mid \mathbf{y}) \text{ high-entropy and multi-modal}
\tag{31.1}\]</span></span></p>
<p>Almost everything peculiar about TTS follows from <a href="#eq-tts-task" class="quarto-xref">Equation&nbsp;<span>31.1</span></a>. It is why regression to the recorded waveform is the wrong objective; why the field needed generative models — adversarial, variational, diffusion, flow-matching, autoregressive — rather than discriminative ones; why controllability is a first-class research problem rather than a feature request; and why <strong>evaluation is itself a research problem</strong> in TTS to a degree that has no parallel in recognition. Where <a href="22-automatic-speech-recognition.html" class="quarto-xref"><span>Chapter 28</span></a> closed with a section on evaluation being more contested than the modelling, this chapter has to treat that contest as part of the science.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reading order
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter assumes the signal representations of <a href="22-automatic-speech-recognition.html#sec-asr-features" class="quarto-xref"><span>Section 28.1.1</span></a> and the self-supervised encoders of <a href="21-speech-representation-learning.html" class="quarto-xref"><span>Chapter 27</span></a>, particularly the semantic tokens of <a href="21-speech-representation-learning.html#sec-discrete-units" class="quarto-xref"><span>Section 27.8.2</span></a>. Neural audio codecs are introduced here only as far as <a href="#sec-codec-lm" class="quarto-xref"><span>Section 31.9</span></a> requires; their design is treated properly in the following chapter.</p>
</div>
</div>
<section id="sec-tts-notation" class="level2" data-number="31.1">
<h2 data-number="31.1" class="anchored" data-anchor-id="sec-tts-notation"><span class="header-section-number">31.1</span> Notation and Key Concepts</h2>
<section id="sec-tts-pipeline" class="level3" data-number="31.1.1">
<h3 data-number="31.1.1" class="anchored" data-anchor-id="sec-tts-pipeline"><span class="header-section-number">31.1.1</span> The Classical Decomposition</h3>
<p>Every TTS system, neural or not, performs three transformations. They may be separate modules, jointly trained stages, or collapsed into one network, but it is worth naming them because the vocabulary persists even where the module boundaries do not.</p>
<ol type="1">
<li><strong>Text front-end (analysis).</strong> Normalise the raw text — numbers, dates, currency, abbreviations, URLs — and convert it to a linguistic representation, classically phonemes via grapheme-to-phoneme (G2P) conversion with stress and phrase boundaries.</li>
<li><strong>Acoustic model.</strong> Map the linguistic sequence to an intermediate acoustic representation at a low frame rate, classically a mel spectrogram.</li>
<li><strong>Vocoder (synthesis).</strong> Convert the acoustic representation into a waveform.</li>
</ol>
<div id="tbl-tts-notation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tts-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.1: Speech synthesis terminology.
</figcaption>
<div aria-describedby="tbl-tts-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 32%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Concept</th>
<th style="text-align: left;">Notation</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Phoneme sequence</strong></td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{p} \in \mathcal{P}^{N}\)</span></td>
<td style="text-align: left;">Output of the text front-end. Many modern systems consume characters or subwords instead.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Acoustic features</strong></td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{M} \in \mathbb{R}^{F \times T_{\text{frames}}}\)</span></td>
<td style="text-align: left;">Conventionally an 80-band log-Mel spectrogram at $$86 frames/s (24 kHz, 256-sample hop).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Duration</strong></td>
<td style="text-align: left;"><span class="math inline">\(d_i \in \mathbb{N}\)</span></td>
<td style="text-align: left;">Number of acoustic frames generated by the <span class="math inline">\(i\)</span>-th input token. <span class="math inline">\(\sum_i d_i = T_{\text{frames}}\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Vocoder</strong></td>
<td style="text-align: left;"><span class="math inline">\(g: \mathbb{R}^{F \times T_{\text{frames}}} \to \mathbb{R}^{T}\)</span></td>
<td style="text-align: left;">Acoustic features to waveform.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Speech prompt</strong></td>
<td style="text-align: left;"><span class="math inline">\(\tilde{\mathbf{x}}\)</span></td>
<td style="text-align: left;">A short reference recording used to specify the target voice at inference.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Codec tokens</strong></td>
<td style="text-align: left;"><span class="math inline">\(\mathbf{C} \in \{1..V\}^{T_c \times N_q}\)</span></td>
<td style="text-align: left;">Discrete audio tokens: <span class="math inline">\(T_c\)</span> frames <span class="math inline">\(\times\)</span> <span class="math inline">\(N_q\)</span> quantiser levels (<a href="#sec-codec-lm" class="quarto-xref"><span>Section 31.9</span></a>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>NFE</strong></td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Number of Function Evaluations: forward passes needed to solve a diffusion or flow ODE. The latency currency of non-autoregressive models.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A word that changed meaning
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <em>vocoder</em> (voice coder) was originally a low-bitrate speech <strong>codec</strong>: analyse the signal into excitation and spectral envelope, transmit those, resynthesise. In neural TTS the word now means only “the module that turns acoustic features into a waveform” — a decoder, not a codec. Confusingly, <a href="#sec-codec-lm" class="quarto-xref"><span>Section 31.9</span></a> then reintroduces genuine codecs under their original meaning. Both usages are standard; context disambiguates.</p>
</div>
</div>
</section>
<section id="sec-tts-mel" class="level3" data-number="31.1.2">
<h3 data-number="31.1.2" class="anchored" data-anchor-id="sec-tts-mel"><span class="header-section-number">31.1.2</span> Why Mel Spectrograms</h3>
<p>The mel spectrogram became the interface between stages 2 and 3 for three reasons worth stating explicitly, because two of them later turned into problems.</p>
<p>It is <strong>compact</strong>: 80 dimensions at 86 Hz instead of 24,000 samples per second, a reduction of roughly <span class="math inline">\(350\times\)</span>, which puts the hard sequence-modelling problem at a tractable rate. It is <strong>perceptually motivated</strong>: mel-spaced filters and log compression approximate cochlear frequency resolution and loudness perception (<a href="22-automatic-speech-recognition.html#eq-mel" class="quarto-xref">Equation&nbsp;<span>28.2</span></a>), so squared error in this domain is at least loosely related to audibility. And it <strong>discards phase</strong>, which is a feature for the predictor — phase wraps, is perceptually strange, and is genuinely hard to regress — while being a liability for the reconstructor, which must hallucinate it back. Griffin-Lim phase estimation, used by the earliest neural systems, is the audible demonstration: its characteristic smeared, metallic artefact is precisely the cost of not having phase.</p>
<p>The deeper problem is that mel is <strong>lossy and not learned</strong>. It is fixed by hand rather than optimised jointly with either the model that predicts it or the model that consumes it, and the vocoder is trained on ground-truth mels but deployed on predicted ones. Much of the field’s recent movement — toward codec tokens, VAE latents, and waveform latents — is an attempt to replace this hand-designed interface with a learned one.</p>
</section>
</section>
<section id="sec-onetomany" class="level2" data-number="31.2">
<h2 data-number="31.2" class="anchored" data-anchor-id="sec-onetomany"><span class="header-section-number">31.2</span> The One-to-Many Problem</h2>
<p>This section plays the role that <a href="22-automatic-speech-recognition.html#sec-alignment" class="quarto-xref"><span>Section 28.2</span></a> plays in the ASR chapter: it states the difficulty from which the architectures follow.</p>
<section id="sec-oversmoothing" class="level3" data-number="31.2.1">
<h3 data-number="31.2.1" class="anchored" data-anchor-id="sec-oversmoothing"><span class="header-section-number">31.2.1</span> Why Regression Fails</h3>
<p>Suppose we train an acoustic model by minimising squared error against the recorded mel spectrogram. The minimiser of the expected loss is, pointwise, the conditional mean:</p>
<p><span id="eq-oversmooth"><span class="math display">\[
f^{\star} = \arg\min_{f} \; \mathbb{E}_{\mathbf{y}, \mathbf{M}}
\big\| \mathbf{M} - f(\mathbf{y}) \big\|_2^2
\qquad \Longrightarrow \qquad
f^{\star}(\mathbf{y}) = \mathbb{E}\big[\mathbf{M} \mid \mathbf{y}\big]
\tag{31.2}\]</span></span></p>
<p>and under an <span class="math inline">\(L_1\)</span> loss, the conditional median. Both are the correct answers to the question being asked, and both are useless. Squared error is the negative log-likelihood of an isotropic Gaussian and <span class="math inline">\(L_1\)</span> that of a Laplacian; both are <strong>unimodal</strong> and <strong>factorised across dimensions</strong>, so fitting them asserts that the mel bins are conditionally independent and that <span class="math inline">\(p(\mathbf{M} \mid \mathbf{y})\)</span> has a single mode. Neither assumption is close to true. Mel bins are strongly correlated in time and frequency, and the conditional is genuinely multi-modal: a syllable may plausibly be realised with rising or falling pitch, and the <em>mean</em> of those two contours is a third contour that no speaker would produce.</p>
<p>The perceptual signature is <strong>over-smoothing</strong>: blurred harmonic structure, attenuated high frequencies, washed-out formant transitions. Speech that sounds muffled, buzzy, and lifeless. The vocoder then compounds the damage, because it is asked to invert a smeared spectrogram unlike anything in its training set.</p>
<p>Over-smoothing is not a neural-network problem. It afflicted HMM-based synthesis for the same reason, in the same way, a decade earlier — and recognising the continuity is the fastest route into the field’s history.</p>
</section>
<section id="sec-tts-strategies" class="level3" data-number="31.2.2">
<h3 data-number="31.2.2" class="anchored" data-anchor-id="sec-tts-strategies"><span class="header-section-number">31.2.2</span> Three Strategies</h3>
<p>There are exactly three coherent responses to <a href="#eq-oversmooth" class="quarto-xref">Equation&nbsp;<span>31.2</span></a>, and every system built since 2019 is one of them or a mixture <span class="citation" data-cites="ren2022oversmooth">(<a href="../../references.html#ref-ren2022oversmooth" role="doc-biblioref">Ren et al. 2022</a>)</span>.</p>
<ol type="1">
<li><strong>Reduce the entropy of the conditional by conditioning on more.</strong> If <span class="math inline">\(p(\mathbf{M} \mid \mathbf{y})\)</span> is high-entropy, condition additionally on the variables that explain the variation — duration, pitch, energy, speaker, style, or a reference recording — so that <span class="math inline">\(p(\mathbf{M} \mid \mathbf{y}, \text{extras})\)</span> is nearly unimodal and a simple loss becomes a less-wrong model of it. Predict the extras separately. <em>This is FastSpeech 2’s variance adaptor, and, in a generalised form, every prompt-based zero-shot system.</em></li>
<li><strong>Use a model class that can represent multi-modality.</strong> Categorical softmaxes, GANs, VAEs, normalising flows, diffusion, flow matching, and discrete-token language models all can. <em>This is WaveNet, HiFi-GAN, VITS, Grad-TTS, Voicebox, and VALL-E.</em></li>
<li><strong>Model the unexplained residual as an explicit latent.</strong> Push whatever text does not determine into a latent variable inferred at training time and sampled at inference. <em>This is Parallel Tacotron’s VAE and VITS’s posterior.</em></li>
</ol>
<p>A useful way to hold the generative families together: each is a different answer to <em>where the stochasticity lives</em>. In a GAN it is in the input noise, judged by a critic. In diffusion and flow matching it is in a sampled trajectory. In a VAE it is in a latent. In a discrete LM it is in the per-step categorical sample. Once you see that, the apparent zoo of architectures becomes a small set of choices.</p>
</section>
</section>
<section id="sec-tts-history" class="level2" data-number="31.3">
<h2 data-number="31.3" class="anchored" data-anchor-id="sec-tts-history"><span class="header-section-number">31.3</span> Historical Overview</h2>
<div id="tbl-tts-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tts-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.2: Paradigms in speech synthesis.
</figcaption>
<div aria-describedby="tbl-tts-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Period</th>
<th style="text-align: left;">Paradigm</th>
<th style="text-align: left;">Representative work</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1990s–2000s</td>
<td style="text-align: left;">Concatenative unit selection</td>
<td style="text-align: left;">Hunt &amp; Black</td>
</tr>
<tr class="even">
<td style="text-align: left;">2000s–2013</td>
<td style="text-align: left;">Statistical parametric (HMM/HTS) + source-filter vocoder</td>
<td style="text-align: left;">HTS <span class="citation" data-cites="zen2009spss">(<a href="../../references.html#ref-zen2009spss" role="doc-biblioref">Zen et al. 2009</a>)</span>, STRAIGHT, WORLD <span class="citation" data-cites="morise2016world">(<a href="../../references.html#ref-morise2016world" role="doc-biblioref">Morise et al. 2016</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Neural vocoder</td>
<td style="text-align: left;">WaveNet <span class="citation" data-cites="oord2016wavenet">(<a href="../../references.html#ref-oord2016wavenet" role="doc-biblioref">Oord et al. 2016</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">2017–2018</td>
<td style="text-align: left;">Autoregressive attention seq2seq + neural vocoder</td>
<td style="text-align: left;">Tacotron <span class="citation" data-cites="wang2017tacotron">(<a href="../../references.html#ref-wang2017tacotron" role="doc-biblioref">Wang et al. 2017</a>)</span>, Tacotron 2 <span class="citation" data-cites="shen2018tacotron2">(<a href="../../references.html#ref-shen2018tacotron2" role="doc-biblioref">Shen et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2019–2020</td>
<td style="text-align: left;">Non-autoregressive with explicit duration</td>
<td style="text-align: left;">FastSpeech <span class="citation" data-cites="ren2019fastspeech ren2021fastspeech2">(<a href="../../references.html#ref-ren2019fastspeech" role="doc-biblioref">Ren et al. 2019</a>, <a href="../../references.html#ref-ren2021fastspeech2" role="doc-biblioref">2021</a>)</span>, Glow-TTS <span class="citation" data-cites="kim2020glowtts">(<a href="../../references.html#ref-kim2020glowtts" role="doc-biblioref">Kim et al. 2020</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">2019–2021</td>
<td style="text-align: left;">GAN vocoders make waveform generation free</td>
<td style="text-align: left;">MelGAN <span class="citation" data-cites="kumar2019melgan">(<a href="../../references.html#ref-kumar2019melgan" role="doc-biblioref">Kumar et al. 2019</a>)</span>, HiFi-GAN <span class="citation" data-cites="kong2020hifigan">(<a href="../../references.html#ref-kong2020hifigan" role="doc-biblioref">Kong et al. 2020</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021</td>
<td style="text-align: left;">Single-stage end-to-end</td>
<td style="text-align: left;">VITS <span class="citation" data-cites="kim2021vits">(<a href="../../references.html#ref-kim2021vits" role="doc-biblioref">Kim et al. 2021</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">2021–2024</td>
<td style="text-align: left;">Diffusion, then flow matching</td>
<td style="text-align: left;">Grad-TTS <span class="citation" data-cites="popov2021gradtts">(<a href="../../references.html#ref-popov2021gradtts" role="doc-biblioref">Popov et al. 2021</a>)</span>, Voicebox <span class="citation" data-cites="le2023voicebox">(<a href="../../references.html#ref-le2023voicebox" role="doc-biblioref">Le et al. 2023</a>)</span>, F5-TTS <span class="citation" data-cites="chen2024f5tts">(<a href="../../references.html#ref-chen2024f5tts" role="doc-biblioref">Y. Chen et al. 2024</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022–2023</td>
<td style="text-align: left;">Codec tokens and in-context voice cloning</td>
<td style="text-align: left;">AudioLM <span class="citation" data-cites="borsos2023audiolm">(<a href="../../references.html#ref-borsos2023audiolm" role="doc-biblioref">Borsos et al. 2023</a>)</span>, VALL-E <span class="citation" data-cites="wang2023valle">(<a href="../../references.html#ref-wang2023valle" role="doc-biblioref">Wang et al. 2023</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">2024–2026</td>
<td style="text-align: left;">LLM backbones, streaming duplex speech, scaling</td>
<td style="text-align: left;">CosyVoice <span class="citation" data-cites="du2024cosyvoice2">(<a href="../../references.html#ref-du2024cosyvoice2" role="doc-biblioref">Du, Wang, et al. 2024</a>)</span>, Moshi <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span>, Llasa <span class="citation" data-cites="ye2025llasa">(<a href="../../references.html#ref-ye2025llasa" role="doc-biblioref">Ye et al. 2025</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-tts-classical" class="level2" data-number="31.4">
<h2 data-number="31.4" class="anchored" data-anchor-id="sec-tts-classical"><span class="header-section-number">31.4</span> Before Deep Learning</h2>
<p>Two paradigms competed, and the trade-off between them is still recognisable in modern systems.</p>
<p><strong>Unit selection</strong> concatenates fragments of recorded speech, chosen from a large single-speaker database by minimising a target cost (how well each unit matches the desired context) plus a join cost (how smoothly consecutive units splice). Because the output <em>is</em> recorded speech, local segmental quality can be excellent. But the voice cannot be changed without re-recording, prosody is limited to what the database contains, and joins produce audible glitches.</p>
<p><strong>Statistical parametric synthesis</strong> <span class="citation" data-cites="zen2009spss">(<a href="../../references.html#ref-zen2009spss" role="doc-biblioref">Zen et al. 2009</a>)</span>, in practice HMM-based synthesis (HTS), models the <em>trajectory</em> of acoustic parameters — mel-cepstra, log <span class="math inline">\(F_0\)</span>, band aperiodicity — with context-dependent HMMs and decision-tree state tying, then reconstructs the waveform with a source-filter vocoder such as STRAIGHT or WORLD <span class="citation" data-cites="morise2016world">(<a href="../../references.html#ref-morise2016world" role="doc-biblioref">Morise et al. 2016</a>)</span>. This bought flexibility: speaker adaptation, style control, and a footprint measured in megabytes rather than gigabytes. It cost quality, and it is where over-smoothing was first diagnosed.</p>
<p>The 2009 review <span class="citation" data-cites="zen2009spss">(<a href="../../references.html#ref-zen2009spss" role="doc-biblioref">Zen et al. 2009</a>)</span> attributes the quality gap to exactly three causes, and the sequence in which deep learning attacked them organises the rest of this chapter:</p>
<div id="tbl-three-causes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-three-causes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.3: The three causes of quality loss in parametric synthesis.
</figcaption>
<div aria-describedby="tbl-three-causes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 50%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cause</th>
<th style="text-align: left;">Attacked by</th>
<th style="text-align: left;">When</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Vocoder quality</td>
<td style="text-align: left;">Neural vocoders (<a href="#sec-vocoders" class="quarto-xref"><span>Section 31.5</span></a>)</td>
<td style="text-align: left;">2016</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inadequate acoustic modelling</td>
<td style="text-align: left;">Neural sequence models (<a href="#sec-tts-ar" class="quarto-xref"><span>Section 31.6</span></a>)</td>
<td style="text-align: left;">2017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Over-smoothing</td>
<td style="text-align: left;">Generative rather than regression objectives</td>
<td style="text-align: left;">2019–</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Diagnosed in 2009, resolved in that order over the following decade. Few subfields have a roadmap laid out so cleanly in advance.</p>
</section>
<section id="sec-vocoders" class="level2" data-number="31.5">
<h2 data-number="31.5" class="anchored" data-anchor-id="sec-vocoders"><span class="header-section-number">31.5</span> Neural Vocoders</h2>
<section id="sec-wavenet" class="level3" data-number="31.5.1">
<h3 data-number="31.5.1" class="anchored" data-anchor-id="sec-wavenet"><span class="header-section-number">31.5.1</span> WaveNet and the Sequential Bottleneck</h3>
<p>WaveNet <span class="citation" data-cites="oord2016wavenet">(<a href="../../references.html#ref-oord2016wavenet" role="doc-biblioref">Oord et al. 2016</a>)</span> models the waveform autoregressively at the sample level,</p>
<p><span id="eq-wavenet"><span class="math display">\[
p(\mathbf{x} \mid \mathbf{c}) = \prod_{t=1}^{T} p\big(x_t \mid x_{&lt;t}, \mathbf{c}\big)
\tag{31.3}\]</span></span></p>
<p>using stacked <strong>dilated causal convolutions</strong> whose dilation doubles with depth (<span class="math inline">\(1, 2, 4, \ldots, 512\)</span>, repeated), so the receptive field grows exponentially while depth grows linearly. Each layer applies a gated activation <span class="math inline">\(\mathbf{z} = \tanh(\mathbf{W}_f * \mathbf{x}) \odot \sigma(\mathbf{W}_g * \mathbf{x})\)</span> with residual and skip connections, and conditioning <span class="math inline">\(\mathbf{c}\)</span> (linguistic features, or mel) is injected through learned upsampling.</p>
<p>The decisive detail is the output distribution: a <strong>256-way categorical softmax over <span class="math inline">\(\mu\)</span>-law-companded 8-bit samples</strong>. A categorical distribution can represent an arbitrary multi-modal <span class="math inline">\(p(x_t \mid x_{&lt;t})\)</span>; a Gaussian cannot. This is strategy 2 of <a href="#sec-tts-strategies" class="quarto-xref"><span>Section 31.2.2</span></a> applied at the sample level, and it is why WaveNet escaped the over-smoothing trap that had bounded parametric synthesis for a decade. The quality difference was not incremental — it was the first time synthetic speech stopped sounding synthetic.</p>
<p>The cost is <a href="#eq-wavenet" class="quarto-xref">Equation&nbsp;<span>31.3</span></a> itself. At 24 kHz, one second of audio requires 24,000 <strong>sequential</strong> forward passes. This is not a FLOPs problem that a larger GPU solves; it is a serialisation problem, immune to parallelism. Original implementations ran orders of magnitude slower than real time.</p>
<p>Every subsequent vocoder is an answer to <em>how do I keep WaveNet’s quality without its sequential depth?</em>, and there are only four answers.</p>
<div id="tbl-vocoders" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-vocoders-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.4: Four escapes from the autoregressive sampling bottleneck.
</figcaption>
<div aria-describedby="tbl-vocoders-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 34%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Strategy</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Exemplars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Make the AR model cheap</td>
<td style="text-align: left;">Sparse recurrent core, sample folding, DSP structure</td>
<td style="text-align: left;">WaveRNN <span class="citation" data-cites="kalchbrenner2018wavernn">(<a href="../../references.html#ref-kalchbrenner2018wavernn" role="doc-biblioref">Kalchbrenner et al. 2018</a>)</span>, LPCNet <span class="citation" data-cites="valin2019lpcnet">(<a href="../../references.html#ref-valin2019lpcnet" role="doc-biblioref">Valin and Skoglund 2019</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Distil into a parallel model</td>
<td style="text-align: left;">Probability density distillation into an inverse autoregressive flow</td>
<td style="text-align: left;">Parallel WaveNet <span class="citation" data-cites="oord2018parallelwavenet">(<a href="../../references.html#ref-oord2018parallelwavenet" role="doc-biblioref"><span class="nocase">Oord et al.</span> 2018</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Use a natively parallel likelihood model</td>
<td style="text-align: left;">Normalising flows; diffusion</td>
<td style="text-align: left;">WaveGlow <span class="citation" data-cites="prenger2019waveglow">(<a href="../../references.html#ref-prenger2019waveglow" role="doc-biblioref">Prenger et al. 2019</a>)</span>, DiffWave <span class="citation" data-cites="kong2021diffwave">(<a href="../../references.html#ref-kong2021diffwave" role="doc-biblioref">Kong et al. 2021</a>)</span>, WaveGrad <span class="citation" data-cites="chen2021wavegrad">(<a href="../../references.html#ref-chen2021wavegrad" role="doc-biblioref">Chen et al. 2021</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Abandon likelihood; use adversarial and spectral losses</strong></td>
<td style="text-align: left;">Single forward pass, discriminator as learned perceptual loss</td>
<td style="text-align: left;">MelGAN <span class="citation" data-cites="kumar2019melgan">(<a href="../../references.html#ref-kumar2019melgan" role="doc-biblioref">Kumar et al. 2019</a>)</span>, HiFi-GAN <span class="citation" data-cites="kong2020hifigan">(<a href="../../references.html#ref-kong2020hifigan" role="doc-biblioref">Kong et al. 2020</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The fourth won. It is worth understanding why: mel-to-waveform is <em>nearly</em> deterministic — the conditioning is so strong that little remains to be modelled beyond realistic high-frequency detail and phase. The risk of mode collapse, the usual objection to GANs, is correspondingly small, while the benefit of a single forward pass is large.</p>
</section>
<section id="sec-hifigan" class="level3" data-number="31.5.2">
<h3 data-number="31.5.2" class="anchored" data-anchor-id="sec-hifigan"><span class="header-section-number">31.5.2</span> HiFi-GAN</h3>
<p>HiFi-GAN <span class="citation" data-cites="kong2020hifigan">(<a href="../../references.html#ref-kong2020hifigan" role="doc-biblioref">Kong et al. 2020</a>)</span> is the load-bearing paper of this era, and its design is a good example of inductive bias chosen from signal structure rather than from architectural fashion. Two ideas:</p>
<p><strong>Multi-Receptive Field Fusion</strong> in the generator: parallel residual blocks with different kernel sizes and dilation rates, summed, so each upsampling stage observes several time scales at once.</p>
<p><strong>Multi-Period Discriminator</strong>: reshape the 1-D waveform into 2-D by taking every <span class="math inline">\(p\)</span>-th sample for <span class="math inline">\(p \in \{2, 3, 5, 7, 11\}\)</span> — co-prime, to avoid overlapping periodicities — and discriminate each reshaped view. Voiced speech is quasi-periodic at the fundamental frequency, so a discriminator that explicitly examines periodic subsequences is directly sensitive to pitch structure, which is exactly what earlier vocoders got wrong. This runs alongside MelGAN’s multi-scale discriminator on progressively average-pooled audio.</p>
<p>The generator objective, in least-squares GAN form, is</p>
<p><span id="eq-hifigan"><span class="math display">\[
\mathcal{L}_G = \sum_{k} \mathcal{L}_{\text{adv}}(G; D_k)
\;+\; \lambda_{\text{fm}} \, \mathcal{L}_{\text{FM}}
\;+\; \lambda_{\text{mel}} \big\| \phi(\mathbf{x}) - \phi(G(\mathbf{s})) \big\|_1
\tag{31.4}\]</span></span></p>
<p>where <span class="math inline">\(\phi\)</span> is the mel transform and <span class="math inline">\(\mathcal{L}_{\text{FM}}\)</span> is a <strong>feature-matching</strong> loss: the <span class="math inline">\(L_1\)</span> distance between the discriminators’ intermediate activations on real and generated audio. The mel term deserves comment given <a href="#sec-oversmoothing" class="quarto-xref"><span>Section 31.2.1</span></a> — an <span class="math inline">\(L_1\)</span> reconstruction loss is exactly what we argued causes over-smoothing. It is safe here only because the adversarial term dominates perceptually and the conditioning is nearly deterministic; the <span class="math inline">\(L_1\)</span> term acts as a stabiliser and a coarse spectral anchor rather than as the objective.</p>
<p>HiFi-GAN reached WaveNet-level quality at hundreds of times real time on GPU, and faster than real time on CPU. Its practical effect was to <strong>end waveform generation as a research bottleneck</strong>: after 2020, TTS papers stopped reporting vocoder quality and simply used HiFi-GAN.</p>
<p><strong>Successors.</strong> BigVGAN <span class="citation" data-cites="lee2023bigvgan">(<a href="../../references.html#ref-lee2023bigvgan" role="doc-biblioref">Lee et al. 2023</a>)</span> pursues universality — any speaker, language, or non-speech audio, unseen in training — by giving the generator a periodic inductive bias through the <strong>Snake</strong> activation <span class="math inline">\(f(x) = x + \frac{1}{\alpha}\sin^2(\alpha x)\)</span>, and surrounding it with low-pass-filtered up/downsampling to suppress the aliasing that any pointwise nonlinearity introduces. Vocos <span class="citation" data-cites="siuzdak2024vocos">(<a href="../../references.html#ref-siuzdak2024vocos" role="doc-biblioref">Siuzdak 2024</a>)</span> takes the opposite route: predict <strong>Fourier coefficients</strong> at the STFT frame rate with a ConvNeXt backbone and apply a single inverse STFT, eliminating transposed convolutions and the deep upsampling stack entirely. Both are now more common in new systems than HiFi-GAN itself, and Vocos’s “iSTFT head” is the default fast decoder.</p>
</section>
</section>
<section id="sec-tts-ar" class="level2" data-number="31.6">
<h2 data-number="31.6" class="anchored" data-anchor-id="sec-tts-ar"><span class="header-section-number">31.6</span> Autoregressive Acoustic Models</h2>
<section id="sec-tacotron" class="level3" data-number="31.6.1">
<h3 data-number="31.6.1" class="anchored" data-anchor-id="sec-tacotron"><span class="header-section-number">31.6.1</span> Tacotron and Tacotron 2</h3>
<p>Tacotron <span class="citation" data-cites="wang2017tacotron">(<a href="../../references.html#ref-wang2017tacotron" role="doc-biblioref">Wang et al. 2017</a>)</span> replaced the entire classical pipeline — text analysis, duration model, <span class="math inline">\(F_0\)</span> model — with a single attentional encoder-decoder mapping characters to spectrogram frames, trained on <span class="math inline">\(\langle \text{text}, \text{audio}\rangle\)</span> pairs alone. No phoneme durations, no forced alignment, no linguistic feature engineering. In 2017 this was a genuinely surprising result.</p>
<p>Tacotron 2 <span class="citation" data-cites="shen2018tacotron2">(<a href="../../references.html#ref-shen2018tacotron2" role="doc-biblioref">Shen et al. 2018</a>)</span> made it production-grade with three changes: predict <strong>80-band log-mel</strong> rather than a linear spectrogram and hand it to a modified WaveNet vocoder, establishing the two-stage mel interface that would dominate for six years; use <strong>location-sensitive attention</strong>, in which the attention energy is computed from cumulative attention weights of previous decoder steps as well as content, giving the model an implicit sense of how far through the text it has progressed; and add a <strong>stop-token</strong> predictor so the model chooses its own output length. It remains the most-cited acoustic model ever published.</p>
<p>Note that the attention mechanism here is doing the job that CTC and RNN-T do in recognition (<a href="22-automatic-speech-recognition.html#sec-e2e" class="quarto-xref"><span>Section 28.6</span></a>): establishing correspondence between two sequences of different lengths. But where an ASR decoder is constrained by the structure of the loss to consume its input monotonically, Tacotron’s attention has no such constraint, and that difference proved expensive.</p>
</section>
<section id="sec-attention-failures" class="level3" data-number="31.6.2">
<h3 data-number="31.6.2" class="anchored" data-anchor-id="sec-attention-failures"><span class="header-section-number">31.6.2</span> The Attention Failure Modes</h3>
<p>This is the most important negative result in TTS, and it is worth stating carefully because the field re-learned it a second time in <a href="#sec-valle" class="quarto-xref"><span>Section 31.9.3</span></a>.</p>
<p>A soft content-based attention over text, driven autoregressively by the model’s own generated audio, is a <strong>free-running feedback loop with no monotonicity constraint</strong>. Nothing in the architecture or the loss requires the model to consume each input token exactly once, in order. The observed pathologies:</p>
<div id="tbl-attention-failures" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-attention-failures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.5: Attention failure modes in autoregressive TTS.
</figcaption>
<div aria-describedby="tbl-attention-failures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 28%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Failure</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Perceptual result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Skipping</strong></td>
<td style="text-align: left;">Attention jumps forward past one or more tokens</td>
<td style="text-align: left;">Words vanish</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Repeating</strong></td>
<td style="text-align: left;">Attention fails to advance, or moves backwards</td>
<td style="text-align: left;">Words or syllables re-emitted, sometimes in a loop</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Babbling</strong></td>
<td style="text-align: left;">Attention becomes diffuse; decoder receives a blurred average of embeddings</td>
<td style="text-align: left;">Fluent-sounding gibberish</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Early / late stopping</strong></td>
<td style="text-align: left;">Stop token fires prematurely, or never</td>
<td style="text-align: left;">Truncated utterance, or trailing noise to the length cap</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Why these were fatal in production, rather than merely annoying:</p>
<ul>
<li><strong>The degradation is catastrophic, not graceful.</strong> You do not get slightly worse prosody; you get a missing word. Dropping “not” from a sentence, or a digit from an address, is a correctness bug.</li>
<li><strong>They are invisible to the training loss.</strong> Teacher forcing never exposes the model to its own drifting attention. This is exposure bias, and it means the failure cannot be detected by watching the loss curve.</li>
<li><strong>They are input-dependent and survive held-out evaluation.</strong> Long inputs, repeated words, numerals, acronyms, and unusual punctuation trigger them, so a clean test-set score coexists with regular failures on real user text.</li>
<li><strong>The cost is unbounded.</strong> A per-utterance failure rate in the low single digits is intolerable when synthesising millions of utterances a day.</li>
</ul>
<p>Everything in the next section is a response to this table.</p>
</section>
</section>
<section id="sec-duration" class="level2" data-number="31.7">
<h2 data-number="31.7" class="anchored" data-anchor-id="sec-duration"><span class="header-section-number">31.7</span> Explicit Duration and Non-Autoregressive TTS</h2>
<section id="sec-fastspeech" class="level3" data-number="31.7.1">
<h3 data-number="31.7.1" class="anchored" data-anchor-id="sec-fastspeech"><span class="header-section-number">31.7.1</span> FastSpeech: Robustness by Construction</h3>
<p>FastSpeech <span class="citation" data-cites="ren2019fastspeech">(<a href="../../references.html#ref-ren2019fastspeech" role="doc-biblioref">Ren et al. 2019</a>)</span> removes attention from the decoder entirely. Given phoneme hidden states <span class="math inline">\(\mathbf{h}_{1:N}\)</span> and integer durations <span class="math inline">\(\mathbf{d}_{1:N}\)</span>, a <strong>length regulator</strong> simply repeats each state according to its duration,</p>
<p><span id="eq-length-reg"><span class="math display">\[
\tilde{\mathbf{h}} = \operatorname{LR}(\mathbf{h}, \mathbf{d})
= \big[\underbrace{\mathbf{h}_1, \ldots, \mathbf{h}_1}_{d_1},
\underbrace{\mathbf{h}_2, \ldots, \mathbf{h}_2}_{d_2}, \ldots\big],
\qquad \big|\tilde{\mathbf{h}}\big| = \sum_{i=1}^{N} d_i
\tag{31.5}\]</span></span></p>
<p>and a feed-forward Transformer predicts all mel frames in parallel. Durations are obtained from a teacher autoregressive model’s attention matrix, and a duration predictor is trained in the log domain with squared error.</p>
<p>The headline was a roughly <span class="math inline">\(270\times\)</span> speedup in mel generation, but the substance is elsewhere. Because <a href="#eq-length-reg" class="quarto-xref">Equation&nbsp;<span>31.5</span></a> constructs the output by expansion, the alignment is <strong>monotonic, surjective, and complete by construction</strong>: every input token is consumed, exactly once, in order. Skipping, repeating, and babbling are not reduced in frequency — they are <em>structurally impossible</em>. And the same mechanism yields free controllability: scale all <span class="math inline">\(d_i\)</span> by <span class="math inline">\(\alpha\)</span> to change speaking rate, or edit individual <span class="math inline">\(d_i\)</span> to lengthen a particular phoneme.</p>
<p>Compare <a href="22-automatic-speech-recognition.html#sec-ctc" class="quarto-xref"><span>Section 28.6.1</span></a>: CTC also enforces monotonicity structurally, by constraining the set of alignments the loss marginalises over. The same insight, applied in the opposite direction.</p>
</section>
<section id="sec-variance-adaptor" class="level3" data-number="31.7.2">
<h3 data-number="31.7.2" class="anchored" data-anchor-id="sec-variance-adaptor"><span class="header-section-number">31.7.2</span> FastSpeech 2 and the Variance Adaptor</h3>
<p>FastSpeech 2 <span class="citation" data-cites="ren2021fastspeech2">(<a href="../../references.html#ref-ren2021fastspeech2" role="doc-biblioref">Ren et al. 2021</a>)</span> drops the teacher — durations come from the Montreal Forced Aligner and targets are real rather than distilled mels — and contributes the canonical implementation of strategy 1 from <a href="#sec-tts-strategies" class="quarto-xref"><span>Section 31.2.2</span></a>.</p>
<p>The <strong>variance adaptor</strong> extracts ground-truth <strong>duration</strong>, <strong>pitch</strong>, and <strong>energy</strong> at training time, embeds them, and feeds them to the decoder as additional conditioning, while training separate predictors for each. At inference the predictors supply the values. The mechanism is exactly <a href="#sec-oversmoothing" class="quarto-xref"><span>Section 31.2.1</span></a> in reverse: by conditioning on the variables that explain most of the variation in <span class="math inline">\(p(\mathbf{M} \mid \mathbf{p})\)</span>, the residual conditional becomes closer to unimodal, and a regression loss becomes a less inappropriate model of it.</p>
<p>The pattern — <em>predict the explanatory factors, then condition on them</em> — turned out to be extraordinarily general. Every controllable TTS system has a variance-adaptor-shaped component, and one can read modern prompt-based zero-shot synthesis as a variance adaptor whose conditioning variable is an entire audio recording.</p>
</section>
<section id="sec-mas" class="level3" data-number="31.7.3">
<h3 data-number="31.7.3" class="anchored" data-anchor-id="sec-mas"><span class="header-section-number">31.7.3</span> Monotonic Alignment Search</h3>
<p>FastSpeech 2 still needs an external aligner. Glow-TTS <span class="citation" data-cites="kim2020glowtts">(<a href="../../references.html#ref-kim2020glowtts" role="doc-biblioref">Kim et al. 2020</a>)</span> removes that dependency by learning the alignment <em>inside</em> a likelihood model, and the resulting algorithm is the one modern systems use.</p>
<p>A text encoder produces per-token prior statistics <span class="math inline">\((\mu_i, \sigma_i)\)</span>. A flow-based decoder <span class="math inline">\(f\)</span> maps a mel spectrogram <span class="math inline">\(\mathbf{M}\)</span> to a latent <span class="math inline">\(\mathbf{z} = f^{-1}(\mathbf{M})\)</span>. For a monotonic surjective alignment <span class="math inline">\(A\)</span> mapping mel frame <span class="math inline">\(j\)</span> to text position <span class="math inline">\(A(j)\)</span>, the exact log-likelihood is available because <span class="math inline">\(f\)</span> is invertible:</p>
<p><span id="eq-glowtts"><span class="math display">\[
\log p(\mathbf{M} \mid \mathbf{p}, A)
= \sum_{j} \log \mathcal{N}\big(\mathbf{z}_j; \, \mu_{A(j)}, \sigma_{A(j)}\big)
+ \log \left| \det \frac{\partial f^{-1}}{\partial \mathbf{M}} \right|
\tag{31.6}\]</span></span></p>
<p>The alignment maximising this is found by dynamic programming over the monotonic lattice — a Viterbi recursion in which each frame either stays on the current token or advances to the next:</p>
<p><span id="eq-mas"><span class="math display">\[
Q_{i,j} = \max\big(Q_{i-1,\,j-1}, \; Q_{i,\,j-1}\big)
+ \log \mathcal{N}\big(\mathbf{z}_j; \, \mu_i, \sigma_i\big)
\tag{31.7}\]</span></span></p>
<p>Training alternates: run <strong>Monotonic Alignment Search</strong> with gradients detached to get <span class="math inline">\(A^{\star}\)</span>, update the likelihood given <span class="math inline">\(A^{\star}\)</span>, and train a duration predictor on <span class="math inline">\(d_i = |\{j : A^{\star}(j) = i\}|\)</span> for use at inference.</p>
<p>MAS delivers the robustness of explicit duration with the self-sufficiency of end-to-end training, and it is the piece that VITS, Grad-TTS, and Matcha-TTS all adopt unchanged. Readers who found <a href="22-automatic-speech-recognition.html#eq-ctc-forward" class="quarto-xref">Equation&nbsp;<span>28.8</span></a> familiar will recognise the shape of <a href="#eq-mas" class="quarto-xref">Equation&nbsp;<span>31.7</span></a>: both are dynamic programs over monotonic alignment lattices, differing in whether they marginalise or maximise.</p>
</section>
<section id="sec-vits" class="level3" data-number="31.7.4">
<h3 data-number="31.7.4" class="anchored" data-anchor-id="sec-vits"><span class="header-section-number">31.7.4</span> VITS: One Model, One Objective</h3>
<p>VITS <span class="citation" data-cites="kim2021vits">(<a href="../../references.html#ref-kim2021vits" role="doc-biblioref">Kim et al. 2021</a>)</span> is the most elegant architecture in TTS and repays being read in full. It composes four ideas into a single trainable system.</p>
<p>A <strong>conditional VAE</strong> whose posterior encoder <span class="math inline">\(q_\phi(\mathbf{z} \mid \mathbf{x}_{\text{lin}})\)</span> reads the linear spectrogram — more information than mel — and produces a frame-level latent <span class="math inline">\(\mathbf{z}\)</span>; a HiFi-GAN-style decoder maps <span class="math inline">\(\mathbf{z}\)</span> directly to the waveform, so there is <strong>no mel bottleneck and no separate vocoder</strong>. A <strong>normalising-flow prior</strong>, which transforms a text-conditioned Gaussian into a more expressive distribution so the KL term does not force <span class="math inline">\(\mathbf{z}\)</span> to be simple. <strong>MAS</strong>, run in the flow-transformed space, supplying alignment. And <strong>adversarial training</strong>, since the reconstruction is now at the waveform level where likelihood is the wrong objective. The bound is</p>
<p><span id="eq-vits"><span class="math display">\[
\log p_\theta(\mathbf{x} \mid \mathbf{p}) \;\geq\;
\mathbb{E}_{q_\phi(\mathbf{z} \mid \mathbf{x})}\Big[
\log p_\theta(\mathbf{x} \mid \mathbf{z})
- \log \tfrac{q_\phi(\mathbf{z} \mid \mathbf{x})}{p_\theta(\mathbf{z} \mid \mathbf{p}, A)}
\Big]
\tag{31.8}\]</span></span></p>
<p>trained in practice as <span class="math inline">\(\mathcal{L} = \mathcal{L}_{\text{mel}} + \mathcal{L}_{\text{KL}} + \mathcal{L}_{\text{dur}} + \mathcal{L}_{\text{adv}} + \mathcal{L}_{\text{fm}}\)</span>.</p>
<p>One further component is easy to overlook and conceptually important: the <strong>stochastic duration predictor</strong>, a flow-based model of <span class="math inline">\(p(\mathbf{d} \mid \mathbf{p})\)</span>. Because duration is <em>sampled</em> rather than predicted, repeated synthesis of the same sentence yields different rhythms — restoring a dimension of natural variability that deterministic duration prediction removes. It is strategy 3 applied to timing.</p>
<p>VITS was the first single-stage parallel system to beat the two-stage Tacotron 2 + HiFi-GAN cascade on naturalness while being faster, and it is the ancestor of most open-source “just works” TTS. Its real pedagogical value is as a demonstration that VAEs, flows, adversarial training, and dynamic-programming alignment are <strong>complementary rather than competing</strong> tools.</p>
</section>
</section>
<section id="sec-flow" class="level2" data-number="31.8">
<h2 data-number="31.8" class="anchored" data-anchor-id="sec-flow"><span class="header-section-number">31.8</span> Diffusion and Flow Matching</h2>
<section id="sec-diffusion-tts" class="level3" data-number="31.8.1">
<h3 data-number="31.8.1" class="anchored" data-anchor-id="sec-diffusion-tts"><span class="header-section-number">31.8.1</span> From Diffusion to Straight Paths</h3>
<p>Diffusion arrived in audio through the vocoder: DiffWave <span class="citation" data-cites="kong2021diffwave">(<a href="../../references.html#ref-kong2021diffwave" role="doc-biblioref">Kong et al. 2021</a>)</span> and WaveGrad <span class="citation" data-cites="chen2021wavegrad">(<a href="../../references.html#ref-chen2021wavegrad" role="doc-biblioref">Chen et al. 2021</a>)</span>, independently and near-simultaneously, applied denoising diffusion <span class="citation" data-cites="ho2020ddpm">(<a href="../../references.html#ref-ho2020ddpm" role="doc-biblioref">Ho et al. 2020</a>)</span> to raw waveform generation. WaveGrad’s conditioning on the <strong>continuous noise level</strong> rather than a discrete step index was the important detail, since it allows the number of sampling steps to be chosen at inference — the first indication that audio tolerates aggressive step reduction better than images do.</p>
<p>Grad-TTS <span class="citation" data-cites="popov2021gradtts">(<a href="../../references.html#ref-popov2021gradtts" role="doc-biblioref">Popov et al. 2021</a>)</span> moved diffusion to the acoustic level with an idea that recurs throughout this section: rather than diffusing toward <span class="math inline">\(\mathcal{N}(\mathbf{0}, \mathbf{I})\)</span>, diffuse toward <span class="math inline">\(\mathcal{N}(\boldsymbol{\mu}_{\text{enc}}, \mathbf{I})\)</span>, where <span class="math inline">\(\boldsymbol{\mu}_{\text{enc}}\)</span> is the text encoder’s frame-aligned mean (alignment by MAS). Starting the generative process from something already text-aligned means far fewer steps are needed to reach the data.</p>
<p><strong>Flow matching</strong> <span class="citation" data-cites="lipman2023flowmatching">(<a href="../../references.html#ref-lipman2023flowmatching" role="doc-biblioref">Lipman et al. 2023</a>)</span> then largely displaced diffusion. Rather than learning to reverse a stochastic corruption, regress a <strong>vector field</strong> along a straight path between noise <span class="math inline">\(\mathbf{x}_0 \sim \mathcal{N}(0, I)\)</span> and data <span class="math inline">\(\mathbf{x}_1\)</span>:</p>
<p><span class="math display">\[
\mathbf{x}_t = \big(1 - (1-\sigma_{\min})t\big)\mathbf{x}_0 + t\,\mathbf{x}_1,
\qquad
\mathbf{u}_t = \mathbf{x}_1 - (1-\sigma_{\min})\mathbf{x}_0
\]</span></p>
<p><span id="eq-cfm"><span class="math display">\[
\mathcal{L}_{\text{CFM}} = \mathbb{E}_{t, \mathbf{x}_0, \mathbf{x}_1}
\big\| v_\theta(\mathbf{x}_t, t, \mathbf{c}) - \mathbf{u}_t \big\|^2
\tag{31.9}\]</span></span></p>
<p>Training is as simple as diffusion — a regression against a known target — but the probability paths are far straighter, so an ODE solver <span class="math inline">\(\dot{\mathbf{x}} = v_\theta\)</span> needs dozens of steps rather than hundreds, and single digits after distillation. Since <a href="#eq-cfm" class="quarto-xref">Equation&nbsp;<span>31.9</span></a> is a regression loss, it is worth being explicit about why <a href="#sec-oversmoothing" class="quarto-xref"><span>Section 31.2.1</span></a> does not apply: the model regresses a <em>vector field</em>, not the data, and the multi-modality of <span class="math inline">\(p(\mathbf{x} \mid \mathbf{c})\)</span> is carried by the sampled starting point and the trajectory rather than by the per-step target.</p>
<p><strong>Classifier-free guidance</strong> <span class="citation" data-cites="ho2021cfg">(<a href="../../references.html#ref-ho2021cfg" role="doc-biblioref">Ho and Salimans 2021</a>)</span> is used almost universally. Train with the conditioning dropped some fraction of the time, then extrapolate at inference:</p>
<p><span id="eq-tts-cfg"><span class="math display">\[
\tilde{v} = v_\theta(\mathbf{x}_t, t, \varnothing)
+ \alpha \big( v_\theta(\mathbf{x}_t, t, \mathbf{c}) - v_\theta(\mathbf{x}_t, t, \varnothing) \big)
\tag{31.10}\]</span></span></p>
<p>It sharpens intelligibility and prompt adherence at the cost of <strong>reduced diversity and doubled inference cost</strong> — a trade-off worth remembering, since a recurring theme of recent work is buying the benefit back through distillation.</p>
</section>
<section id="sec-voicebox" class="level3" data-number="31.8.2">
<h3 data-number="31.8.2" class="anchored" data-anchor-id="sec-voicebox"><span class="header-section-number">31.8.2</span> Voicebox: Synthesis as Infilling</h3>
<p>Voicebox <span class="citation" data-cites="le2023voicebox">(<a href="../../references.html#ref-le2023voicebox" role="doc-biblioref">Le et al. 2023</a>)</span> reframes the task in a way that turned out to matter more than the specific model. Rather than “generate speech from text”, the training task is <strong>text-guided speech infilling</strong>: given a masked mel <span class="math inline">\(\mathbf{m} \odot \mathbf{x}\)</span>, the frame-aligned phoneme sequence, and the mask <span class="math inline">\(\mathbf{m}\)</span>, fill in the missing frames, trained with <a href="#eq-cfm" class="quarto-xref">Equation&nbsp;<span>31.9</span></a>.</p>
<p>Three consequences follow.</p>
<p>First, infilling <strong>unifies tasks that were previously separate</strong>. Zero-shot voice cloning is infilling where the unmasked region is a reference recording. Speech editing is infilling where the unmasked region is the surrounding context. Noise removal, continuation, and diverse resampling are all the same model under different masks.</p>
<p>Second, flow matching gives diffusion-level quality at a fraction of the NFE.</p>
<p>Third — and this is the structural point — Voicebox was the first strong demonstration that a <strong>non-autoregressive</strong> model could match autoregressive codec language models at in-context voice cloning while being roughly an order of magnitude faster <em>and</em> structurally incapable of the failure modes in <a href="#tbl-attention-failures" class="quarto-xref">Table&nbsp;<span>31.5</span></a>. Because the output length is fixed in advance by a separate duration model, there is no feedback loop to run away.</p>
<p>Matcha-TTS <span class="citation" data-cites="mehta2024matchatts">(<a href="../../references.html#ref-mehta2024matchatts" role="doc-biblioref">Mehta et al. 2024</a>)</span> is the compact statement of the same idea — encoder plus MAS-derived durations for an informative prior, a 1-D U-Net decoder, optimal-transport conditional flow matching — and is the cleanest minimal implementation to read.</p>
</section>
<section id="sec-implicit-align" class="level3" data-number="31.8.3">
<h3 data-number="31.8.3" class="anchored" data-anchor-id="sec-implicit-align"><span class="header-section-number">31.8.3</span> Implicit Alignment: E2 TTS and F5-TTS</h3>
<p>E2 TTS <span class="citation" data-cites="eskimez2024e2tts">(<a href="../../references.html#ref-eskimez2024e2tts" role="doc-biblioref">Eskimez et al. 2024</a>)</span> then deleted almost everything this chapter has built up. No phonemiser, no aligner, no duration model, no grapheme-to-phoneme step. The input is the raw character sequence, right-padded with filler tokens until its length equals the target mel length; the model is a vanilla flow-matching Transformer performing mel infilling. Alignment is learned implicitly by attention, the only structural hint being that the two sequences have equal length.</p>
<p>That this matches Voicebox is a genuinely surprising negative result, and it appears to reverse the lesson of <a href="#sec-fastspeech" class="quarto-xref"><span>Section 31.7.1</span></a>. It does not, and the reason is worth stating precisely: <strong>E2 TTS is non-autoregressive</strong>. Removing explicit alignment from a model whose output length is fixed in advance does not reintroduce a feedback loop; it merely makes alignment a soft learned quantity. The Era-3 catastrophe required autoregression <em>and</em> unconstrained attention together.</p>
<p>F5-TTS <span class="citation" data-cites="chen2024f5tts">(<a href="../../references.html#ref-chen2024f5tts" role="doc-biblioref">Y. Chen et al. 2024</a>)</span> fixes E2 TTS’s slow convergence with a Diffusion Transformer backbone and ConvNeXt blocks that refine the text representation before it meets the audio stream, and adds <strong>Sway Sampling</strong>, a non-uniform schedule for the flow time <span class="math inline">\(t\)</span> that concentrates function evaluations where the trajectory is most informative — improving quality at fixed NFE with <strong>no retraining</strong>. Trained on 95k hours of Emilia <span class="citation" data-cites="he2024emilia">(<a href="../../references.html#ref-he2024emilia" role="doc-biblioref">He et al. 2024</a>)</span> and released openly with a hackable codebase, it became the default research baseline of 2025.</p>
<div id="tbl-alignment" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.6: Five regimes of alignment in TTS.
</figcaption>
<div aria-describedby="tbl-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 24%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Regime</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Robustness</th>
<th style="text-align: left;">Duration control</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Soft attention (AR)</td>
<td style="text-align: left;">Free-running cross-attention</td>
<td style="text-align: left;"><strong>Poor</strong></td>
<td style="text-align: left;">None</td>
</tr>
<tr class="even">
<td style="text-align: left;">External forced alignment</td>
<td style="text-align: left;">MFA durations, hard expansion</td>
<td style="text-align: left;">Excellent</td>
<td style="text-align: left;">Excellent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monotonic alignment search</td>
<td style="text-align: left;">DP inside a likelihood model</td>
<td style="text-align: left;">Excellent</td>
<td style="text-align: left;">Excellent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Soft / differentiable duration</td>
<td style="text-align: left;">Learned Gaussian upsampling, gradients flow through timing</td>
<td style="text-align: left;">Very good</td>
<td style="text-align: left;">Good</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Implicit (infilling)</td>
<td style="text-align: left;">Padding to output length; attention discovers alignment</td>
<td style="text-align: left;">Good, <em>because</em> non-AR</td>
<td style="text-align: left;">Weak — total length only</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-codec-lm" class="level2" data-number="31.9">
<h2 data-number="31.9" class="anchored" data-anchor-id="sec-codec-lm"><span class="header-section-number">31.9</span> Codec Tokens and Speech Language Models</h2>
<section id="sec-tokens" class="level3" data-number="31.9.1">
<h3 data-number="31.9.1" class="anchored" data-anchor-id="sec-tokens"><span class="header-section-number">31.9.1</span> Speech as a Sequence of Integers</h3>
<p><a href="21-speech-representation-learning.html#sec-discrete-units" class="quarto-xref"><span>Section 27.8.2</span></a> observed that clustering a self-supervised encoder yields discrete <strong>semantic tokens</strong>. Neural audio codecs supply the complementary piece. A codec encodes audio to a low-rate latent, quantises it with a first codebook, quantises the <em>residual</em> with a second, and so on for <span class="math inline">\(N_q\)</span> levels — <strong>residual vector quantisation</strong>, introduced for audio by SoundStream <span class="citation" data-cites="zeghidour2022soundstream">(<a href="../../references.html#ref-zeghidour2022soundstream" role="doc-biblioref">Zeghidour et al. 2022</a>)</span> and popularised by EnCodec <span class="citation" data-cites="defossez2023encodec">(<a href="../../references.html#ref-defossez2023encodec" role="doc-biblioref">Défossez et al. 2023</a>)</span> and DAC <span class="citation" data-cites="kumar2023dac">(<a href="../../references.html#ref-kumar2023dac" role="doc-biblioref">Kumar et al. 2023</a>)</span>. The result is a grid <span class="math inline">\(\mathbf{C} \in \{1..V\}^{T_c \times N_q}\)</span> of integers: codebook 1 carries most of the content, later codebooks progressively finer acoustic detail.</p>
<p>Once speech is a sequence of integers from a finite vocabulary, the entire language-modelling toolkit applies unchanged — pretrained weights, scaling laws, KV caching, streaming, sampling, and preference optimisation. That is the whole argument for this paradigm, and it is a strong one.</p>
<p>Two costs come with it. The grid is <strong>two-dimensional</strong>, and a language model emits one token at a time, so the time <span class="math inline">\(\times\)</span> depth structure must be serialised somehow; the resulting design space (flattening, delay patterns, depth transformers, parallel heads) is the subject of <a href="24-neural-audio-codecs.html#sec-serialisation" class="quarto-xref"><span>Section 30.8</span></a>. And quantisation imposes a <strong>fidelity ceiling</strong> that no amount of modelling recovers.</p>
</section>
<section id="sec-audiolm" class="level3" data-number="31.9.2">
<h3 data-number="31.9.2" class="anchored" data-anchor-id="sec-audiolm"><span class="header-section-number">31.9.2</span> AudioLM and the Semantic/Acoustic Split</h3>
<p>AudioLM <span class="citation" data-cites="borsos2023audiolm">(<a href="../../references.html#ref-borsos2023audiolm" role="doc-biblioref">Borsos et al. 2023</a>)</span> identified the failure mode of naive codec language modelling and the fix. A flat LM over acoustic tokens must spend its capacity predicting reverb, microphone noise, and fine spectral texture, and consequently never learns long-range linguistic structure — it produces locally plausible, globally incoherent audio.</p>
<p>The solution is a hierarchy along the <strong>information</strong> axis rather than the time axis: first model <strong>semantic tokens</strong> (from a self-supervised encoder, capturing phonetic content while discarding speaker and channel), then generate <strong>acoustic tokens</strong> conditioned on them, coarse levels before fine. Predicting meaning first makes next-token prediction a linguistic act rather than an acoustic one.</p>
<p>SPEAR-TTS <span class="citation" data-cites="kharitonov2023speartts">(<a href="../../references.html#ref-kharitonov2023speartts" role="doc-biblioref">Kharitonov et al. 2023</a>)</span> showed the split buys something beyond coherence. Splitting synthesis into “reading” (text <span class="math inline">\(\to\)</span> semantic) and “speaking” (semantic <span class="math inline">\(\to\)</span> acoustic) <strong>decouples the data requirements</strong>: speaking needs no transcripts at all, and reading needs very little paired data because its target is a compact semantic sequence. They obtained high-quality synthesis from <strong>fifteen minutes</strong> of transcribed speech. For low-resource languages this is the central mechanism.</p>
<p>Later codecs collapse the two-tokeniser design into one by distilling a self-supervised model into the first RVQ level, so codebook 1 is semantic and the rest acoustic — SpeechTokenizer <span class="citation" data-cites="zhang2024speechtokenizer">(<a href="../../references.html#ref-zhang2024speechtokenizer" role="doc-biblioref">Zhang et al. 2024</a>)</span> and Moshi’s Mimi <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span> both do this.</p>
</section>
<section id="sec-valle" class="level3" data-number="31.9.3">
<h3 data-number="31.9.3" class="anchored" data-anchor-id="sec-valle"><span class="header-section-number">31.9.3</span> VALL-E and In-Context Voice Cloning</h3>
<p>VALL-E <span class="citation" data-cites="wang2023valle">(<a href="../../references.html#ref-wang2023valle" role="doc-biblioref">Wang et al. 2023</a>)</span> cast TTS as conditional codec language modelling and trained on 60k hours — roughly a thousand times more than contemporary TTS corpora. Over EnCodec’s eight-codebook grid it uses two models: an <strong>autoregressive</strong> Transformer for codebook 1, and a <strong>non-autoregressive</strong> Transformer for codebooks 2–8, each conditioned on all shallower levels:</p>
<p><span id="eq-valle"><span class="math display">\[
p(\mathbf{C} \mid \mathbf{y}, \tilde{\mathbf{C}}) =
\underbrace{\prod_{t} p\big(c_{t,1} \mid c_{&lt;t,1}, \tilde{\mathbf{C}}, \mathbf{y}\big)}_{\text{autoregressive over time}}
\;\cdot\;
\underbrace{\prod_{j=2}^{N_q} p\big(c_{:,j} \mid c_{:,&lt;j}, \tilde{\mathbf{C}}, \mathbf{y}\big)}_{\text{parallel over depth}}
\tag{31.11}\]</span></span></p>
<p>Zero-shot voice cloning then requires no architectural mechanism at all: prepend the tokens of a three-second enrolment clip <span class="math inline">\(\tilde{\mathbf{C}}\)</span> and its transcript, and let the model continue. Because it is literally continuing that recording, it preserves not only timbre but emotion, speaking style, and acoustic environment — things a speaker embedding cannot carry.</p>
<p><strong>And it reintroduced every failure mode in <a href="#tbl-attention-failures" class="quarto-xref">Table&nbsp;<span>31.5</span></a>.</strong> An autoregressive model over a token grid has no monotonicity constraint with respect to text, so word repetition, skipping, and — a new variant — <strong>infinite silence loops</strong> under low-temperature sampling all returned. The silence loop is instructive: greedy or low-<span class="math inline">\(p\)</span> decoding finds that silence is the highest-probability continuation, and the model never escapes.</p>
<p>The field’s response reproduces, in compressed form, the history of <a href="#sec-duration" class="quarto-xref"><span>Section 31.7</span></a>. VALL-E 2 <span class="citation" data-cites="chen2024valle2">(<a href="../../references.html#ref-chen2024valle2" role="doc-biblioref">S. Chen et al. 2024</a>)</span> adds <strong>repetition-aware sampling</strong>, switching adaptively between nucleus and random sampling when repetition is detected, plus grouped code modelling to shorten the sequence. Others reintroduce explicit monotonic constraints at inference or predict phoneme position alongside audio. This is the same lesson being learned twice, and pointing that out is the single most useful thing a textbook can do with this material.</p>
</section>
<section id="sec-cosyvoice" class="level3" data-number="31.9.4">
<h3 data-number="31.9.4" class="anchored" data-anchor-id="sec-cosyvoice"><span class="header-section-number">31.9.4</span> The CosyVoice Template</h3>
<p>The dominant industrial architecture of 2024–2026 is a hybrid that takes the best of both halves of this chapter: an <strong>autoregressive LM over semantic tokens</strong>, followed by <strong>non-autoregressive flow matching</strong> to mel, followed by a vocoder <span class="citation" data-cites="du2024cosyvoice du2024cosyvoice2">(<a href="../../references.html#ref-du2024cosyvoice" role="doc-biblioref">Du, Chen, et al. 2024</a>; <a href="../../references.html#ref-du2024cosyvoice2" role="doc-biblioref">Du, Wang, et al. 2024</a>)</span>.</p>
<p>The reasoning is that the two stages have different requirements. Long-range linguistic and prosodic structure benefits from autoregression and from inheriting a pretrained text LLM; acoustic detail benefits from parallel generation and does not need to be sampled sequentially. Placing the AR/NAR boundary at the semantic/acoustic boundary lets each do what it is good at.</p>
<p>Two details from CosyVoice 2 are worth carrying forward. Its speech tokeniser is derived from an <strong>ASR encoder</strong>, so tokens are <em>supervised</em> to be semantic rather than emerging from unsupervised clustering — you get to choose what “semantic” means. And it replaces RVQ with <strong>finite scalar quantisation</strong>, which bounds and rounds each latent dimension independently so that every code is reachable by construction, eliminating the codebook collapse that <a href="21-speech-representation-learning.html#eq-diversity" class="quarto-xref">Equation&nbsp;<span>27.4</span></a> was invented to prevent. CosyVoice 3 <span class="citation" data-cites="du2025cosyvoice3">(<a href="../../references.html#ref-du2025cosyvoice3" role="doc-biblioref">Du et al. 2025</a>)</span> scales the recipe to a million hours.</p>
</section>
<section id="sec-continuous-ar" class="level3" data-number="31.9.5">
<h3 data-number="31.9.5" class="anchored" data-anchor-id="sec-continuous-ar"><span class="header-section-number">31.9.5</span> The Continuous Counter-Current</h3>
<p>It is worth resisting the conclusion that discretisation is necessary. MELLE <span class="citation" data-cites="meng2024melle">(<a href="../../references.html#ref-meng2024melle" role="doc-biblioref">Meng et al. 2024</a>)</span> performs <strong>autoregressive synthesis of continuous mel frames</strong>, with no vector quantisation anywhere. Cross-entropy being unavailable, it combines a regression loss with a <strong>variational</strong> sampling module — so the model samples rather than predicting a conditional mean, addressing <a href="#eq-oversmooth" class="quarto-xref">Equation&nbsp;<span>31.2</span></a> directly — and a <strong>spectrogram flux loss</strong> that penalises small frame-to-frame variation, explicitly punishing the degenerate static output a regression loss invites.</p>
<p>The result is single-stage, free of the quantisation ceiling, and <em>more</em> robust than VALL-E. That last point is the reason to teach it: it isolates which of VALL-E’s problems come from autoregression (few) and which from discrete-token sampling (most). By 2026 this “continuous autoregression with a small generative head” family is a credible alternative rather than a curiosity, and the question of discrete versus continuous representations remains genuinely open — as it does on the representation-learning side (<a href="21-speech-representation-learning.html#sec-ssl-open" class="quarto-xref"><span>Section 27.9</span></a>).</p>
</section>
<section id="sec-tts-streaming" class="level3" data-number="31.9.6">
<h3 data-number="31.9.6" class="anchored" data-anchor-id="sec-tts-streaming"><span class="header-section-number">31.9.6</span> Streaming and Duplex Speech</h3>
<p>Conversational systems are latency-bound in a way that offline synthesis is not, and the relevant metric is not the real-time factor but the <strong>time to first audio</strong>.</p>
<p>Moshi <span class="citation" data-cites="defossez2024moshi">(<a href="../../references.html#ref-defossez2024moshi" role="doc-biblioref">Défossez et al. 2024</a>)</span> contributed several mechanisms now standard. Its <strong>Mimi</strong> codec runs at 12.5 Hz with a semantic first codebook. Its <strong>RQ-Transformer</strong> pairs a large temporal backbone with a small <strong>depth transformer</strong> that autoregresses over codebook levels within a frame — the standard answer to serialising the token grid. Its <strong>inner monologue</strong> predicts time-aligned text tokens as a per-frame prefix to the audio tokens, extending AudioLM’s hierarchy up one more level and substantially improving linguistic quality; reversing the sign of the text-audio delay converts the same model between streaming ASR and streaming TTS. And <strong>multi-stream</strong> modelling of both participants’ audio makes overlap, interruption, and backchannels representable without a turn-taking state machine.</p>
<p>CosyVoice 2 achieves streaming differently, through <strong>chunk-aware causal flow matching</strong> — attention masks that let a single set of weights serve streaming and offline synthesis by training over a mixture of chunk sizes.</p>
<div id="tbl-ar-nar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ar-nar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.7: Autoregressive and non-autoregressive synthesis compared.
</figcaption>
<div aria-describedby="tbl-ar-nar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"><strong>Autoregressive</strong> (token LM)</th>
<th style="text-align: left;"><strong>Non-autoregressive</strong> (flow, masked)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prosody and long-range structure</td>
<td style="text-align: left;">Often better; sampled sequentially</td>
<td style="text-align: left;">Historically flatter; largely closed by 2025</td>
</tr>
<tr class="even">
<td style="text-align: left;">Robustness</td>
<td style="text-align: left;"><strong>Worse</strong> — repetition, skipping, silence loops</td>
<td style="text-align: left;"><strong>Better</strong> — length fixed in advance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Time to first audio</td>
<td style="text-align: left;"><strong>Excellent</strong> — emit while generating</td>
<td style="text-align: left;">Needs chunking or causal masking to stream</td>
</tr>
<tr class="even">
<td style="text-align: left;">Duration control</td>
<td style="text-align: left;">Weak</td>
<td style="text-align: left;">Strong</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diversity</td>
<td style="text-align: left;">Native, via sampling</td>
<td style="text-align: left;">Needs care; guidance reduces it</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ecosystem</td>
<td style="text-align: left;">Inherits the entire LLM stack</td>
<td style="text-align: left;">Bespoke tooling</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 2026 position is that this dichotomy is mostly historical. Frontier systems hybridise: an AR backbone with a small per-token diffusion head, block-wise AR with parallel denoising inside each block, or the AR-semantic/NAR-acoustic split of <a href="#sec-cosyvoice" class="quarto-xref"><span>Section 31.9.4</span></a>.</p>
</section>
</section>
<section id="sec-cloning" class="level2" data-number="31.10">
<h2 data-number="31.10" class="anchored" data-anchor-id="sec-cloning"><span class="header-section-number">31.10</span> Zero-Shot Voice Cloning</h2>
<p>Cloning a voice from seconds of audio, with no fine-tuning, went from research goal to commodity in about three years. The mechanism changed four times, and the progression is a good summary of the chapter.</p>
<div id="tbl-cloning" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cloning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.8: Four generations of zero-shot voice cloning.
</figcaption>
<div aria-describedby="tbl-cloning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 22%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Generation</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Captures</th>
<th style="text-align: left;">Limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Speaker embedding</strong> (2018)</td>
<td style="text-align: left;">Condition on a <span class="math inline">\(d\)</span>-vector or x-vector from a verification network (<a href="23-speaker-diarization.html#sec-features" class="quarto-xref"><span>Section 29.1.1</span></a>)</td>
<td style="text-align: left;">Timbre</td>
<td style="text-align: left;">Loses prosody, accent, channel</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>AR prompting</strong> (VALL-E, 2023)</td>
<td style="text-align: left;">Prepend reference tokens and transcript; let the LM continue</td>
<td style="text-align: left;">Timbre, emotion, style, room</td>
<td style="text-align: left;">Needs the reference transcript; AR failure modes</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Masked infilling</strong> (Voicebox, E2, F5)</td>
<td style="text-align: left;">Reference audio is the unmasked region; target text is appended</td>
<td style="text-align: left;">As above</td>
<td style="text-align: left;">Weaker fine-grained control</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Factorised / described</strong> (2024–2026)</td>
<td style="text-align: left;">Separate timbre channel <span class="citation" data-cites="ju2024naturalspeech3 wang2025sparktts">(<a href="../../references.html#ref-ju2024naturalspeech3" role="doc-biblioref">Ju et al. 2024</a>; <a href="../../references.html#ref-wang2025sparktts" role="doc-biblioref">X. Wang et al. 2025</a>)</span>, or a natural-language voice description</td>
<td style="text-align: left;">Independent control of timbre, prosody, style</td>
<td style="text-align: left;">Instruction following is still unreliable</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The trajectory is from <em>conditioning on a vector</em> to <em>conditioning on an example</em> to <em>conditioning on a description</em>, which mirrors the corresponding shift in text and image generation almost exactly.</p>
<p>The safety consequences are not incidental to the technology, and a chapter that described the capability without them would be incomplete. Three-second cloning from open-weight models is now routine. Countermeasures exist — audio watermarking with localised detection, and provenance manifests — but their limits are real and acknowledged by their authors: watermarking is voluntary, there is no interoperable standard, marks are removable and forgeable, and robustness degrades as an attacker gains knowledge of the algorithm or access to the detector. Passive detection of unwatermarked synthetic speech remains substantially unsolved.</p>
</section>
<section id="sec-tts-opensource" class="level2" data-number="31.11">
<h2 data-number="31.11" class="anchored" data-anchor-id="sec-tts-opensource"><span class="header-section-number">31.11</span> The Open-Source Landscape</h2>
<div id="tbl-tts-toolkits" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tts-toolkits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.9: Open-source speech synthesis projects.
</figcaption>
<div aria-describedby="tbl-tts-toolkits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Project</th>
<th style="text-align: left;">Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>F5-TTS</strong></td>
<td style="text-align: left;">Flow-matching zero-shot TTS; the default open research baseline (<a href="https://github.com/SWivid/F5-TTS">SWivid/F5-TTS</a>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>CosyVoice</strong></td>
<td style="text-align: left;">LM + flow matching; streaming, multilingual, instruction control (<a href="https://github.com/FunAudioLLM/CosyVoice">FunAudioLLM/CosyVoice</a>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Coqui TTS</strong></td>
<td style="text-align: left;">VITS/XTTS lineage <span class="citation" data-cites="casanova2024xtts">(<a href="../../references.html#ref-casanova2024xtts" role="doc-biblioref">Casanova et al. 2024</a>)</span>; broad recipe collection (<a href="https://github.com/coqui-ai/TTS">coqui-ai/TTS</a>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>ESPnet</strong></td>
<td style="text-align: left;">Research recipes spanning Tacotron 2, FastSpeech 2, VITS, Matcha (<a href="https://github.com/espnet/espnet">espnet/espnet</a>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Matcha-TTS</strong></td>
<td style="text-align: left;">Minimal, readable flow-matching implementation (<a href="https://github.com/shivammehta25/Matcha-TTS">shivammehta25/Matcha-TTS</a>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Amphion</strong></td>
<td style="text-align: left;">Toolkit behind MaskGCT and related generative audio work (<a href="https://github.com/open-mmlab/Amphion">open-mmlab/Amphion</a>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Moshi / Mimi</strong></td>
<td style="text-align: left;">Full-duplex speech-text model and its streaming codec (<a href="https://github.com/kyutai-labs/moshi">kyutai-labs/moshi</a>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>BigVGAN / Vocos</strong></td>
<td style="text-align: left;">Current default vocoders</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Transformers</strong></td>
<td style="text-align: left;">Inference for many of the above under one API</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Zero-shot synthesis with a flow-matching model is a few lines:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> f5_tts.api <span class="im">import</span> F5TTS</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>tts <span class="op">=</span> F5TTS()                     <span class="co"># DiT backbone + Vocos vocoder</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>wav, sr, _ <span class="op">=</span> tts.infer(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    ref_file<span class="op">=</span><span class="st">"reference.wav"</span>,     <span class="co"># ~5–10 s of the target voice</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    ref_text<span class="op">=</span><span class="st">"Text spoken in the reference clip."</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    gen_text<span class="op">=</span><span class="st">"Text to synthesise in that voice."</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    nfe_step<span class="op">=</span><span class="dv">32</span>,                  <span class="co"># ODE steps: quality/latency knob</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    cfg_strength<span class="op">=</span><span class="fl">2.0</span>,             <span class="co"># classifier-free guidance weight</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The two arguments worth experimenting with are <code>nfe_step</code> and <code>cfg_strength</code>, since they expose <a href="#eq-cfm" class="quarto-xref">Equation&nbsp;<span>31.9</span></a> and <a href="#eq-tts-cfg" class="quarto-xref">Equation&nbsp;<span>31.10</span></a> directly: fewer steps trade quality for latency, and stronger guidance trades diversity for intelligibility.</p>
</section>
<section id="sec-tts-eval" class="level2" data-number="31.12">
<h2 data-number="31.12" class="anchored" data-anchor-id="sec-tts-eval"><span class="header-section-number">31.12</span> Evaluation</h2>
<p>In recognition, evaluation is contested at the margins — text normalisation, test-set selection — but the metric itself is sound, because a unique correct answer exists. In synthesis there is no correct answer, so evaluation is a research problem in its own right, and one that the field currently considers to be in a poor state.</p>
<section id="sec-mos" class="level3" data-number="31.12.1">
<h3 data-number="31.12.1" class="anchored" data-anchor-id="sec-mos"><span class="header-section-number">31.12.1</span> Subjective Evaluation and the Limits of MOS</h3>
<p><strong>MOS</strong> (Mean Opinion Score) presents stimuli one at a time for rating on a 1–5 scale and averages. <strong>CMOS</strong> presents pairs for a preference judgement on a <span class="math inline">\(-3 \ldots +3\)</span> scale. <strong>SMOS</strong> rates similarity to a reference speaker.</p>
<p>MOS has been the field’s primary metric for thirty years, and the case against it is now well documented and broadly accepted. The central finding <span class="citation" data-cites="lemaguer2024moslimits">(<a href="../../references.html#ref-lemaguer2024moslimits" role="doc-biblioref">Maguer et al. 2024</a>)</span> is that <strong>MOS, despite presenting itself as an absolute category rating, behaves as a relative measure</strong>. Re-running listening tests on <em>identical stimuli</em> with different accompanying systems shifts scores by up to a full point, and moves system pairs across the threshold of statistical significance. Listeners construct their anchors from whatever they have already heard, so the composition of the test set determines the numbers.</p>
<p>The practical consequence is stark and worth stating without hedging:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>MOS values from different papers cannot be compared
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is the explicit conclusion of the community guidelines <span class="citation" data-cites="cooper2025goodpractices">(<a href="../../references.html#ref-cooper2025goodpractices" role="doc-biblioref">Cooper et al. 2025</a>)</span>, and it invalidates a large fraction of the comparison tables in the TTS literature. If you want to compare against a system, you must synthesise with it and include it in <strong>your own</strong> listening test.</p>
</div>
</div>
<p>Those guidelines, an output of a Dagstuhl seminar and written partly as instructions for reviewers, are the closest thing to an official position. Their other recommendations:</p>
<ul>
<li><strong>Naturalness MOS is saturated.</strong> Modern systems cluster at the ceiling, so the paradigm cannot resolve them. Prefer more discriminative designs: AB/ABX pairwise, best-worst scaling, or MUSHRA-like tests — while noting that a true MUSHRA test is impossible for TTS, since there are no anchors.</li>
<li><strong>Report the protocol</strong>: number of listeners, samples per system, ratings per sample, the exact question asked, the scale, and the statistical test.</li>
<li><strong>Use appropriate statistics.</strong> MOS data are ordinal, so non-parametric tests (Wilcoxon, Mann-Whitney) are appropriate.</li>
<li><strong>Control the confounds</strong>: loudness-normalise stimuli, and be aware that listeners’ preference for a particular <em>voice</em> confounds naturalness ratings when systems use different speakers.</li>
<li><strong>Never call a predicted score “MOS.”</strong> Call it predicted MOS.</li>
</ul>
</section>
<section id="sec-tts-objective" class="level3" data-number="31.12.2">
<h3 data-number="31.12.2" class="anchored" data-anchor-id="sec-tts-objective"><span class="header-section-number">31.12.2</span> Objective Metrics</h3>
<div id="tbl-tts-metrics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tts-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.10: Objective metrics for speech synthesis.
</figcaption>
<div aria-describedby="tbl-tts-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 51%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">What it measures</th>
<th style="text-align: left;">Caveats</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>WER / CER</strong></td>
<td style="text-align: left;">Intelligibility, via an ASR model transcribing the output</td>
<td style="text-align: left;">Inherits the ASR system’s own errors and biases; measures <em>ASR-friendliness</em></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SIM-o / SIM-r</strong></td>
<td style="text-align: left;">Speaker similarity: cosine between speaker embeddings</td>
<td style="text-align: left;">SIM-r compares against codec-resynthesised reference and is <strong>not comparable</strong> to SIM-o</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>UTMOS / UTMOSv2</strong></td>
<td style="text-align: left;">Predicted naturalness <span class="citation" data-cites="saeki2022utmos">(<a href="../../references.html#ref-saeki2022utmos" role="doc-biblioref">Saeki et al. 2022</a>)</span></td>
<td style="text-align: left;">Saturates on modern systems; weak correlation with human ratings at the top</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>DNSMOS</strong> <span class="citation" data-cites="reddy2021dnsmos">(<a href="../../references.html#ref-reddy2021dnsmos" role="doc-biblioref">Reddy et al. 2021</a>)</span>, <strong>NISQA</strong> <span class="citation" data-cites="mittag2021nisqa">(<a href="../../references.html#ref-mittag2021nisqa" role="doc-biblioref">Mittag et al. 2021</a>)</span></td>
<td style="text-align: left;">Perceptual quality</td>
<td style="text-align: left;">Trained for noise suppression and transmission quality; applying them to TTS is a documented domain misuse</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>FAD</strong> <span class="citation" data-cites="kilgour2019fad">(<a href="../../references.html#ref-kilgour2019fad" role="doc-biblioref">Kilgour et al. 2019</a>)</span></td>
<td style="text-align: left;">Distributional distance in an embedding space</td>
<td style="text-align: left;">Gaussian assumption is wrong; biased by sample size; encoder choice dominates the result</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>TTSDS2</strong> <span class="citation" data-cites="minixhofer2025ttsds2">(<a href="../../references.html#ref-minixhofer2025ttsds2" role="doc-biblioref">Minixhofer et al. 2025</a>)</span></td>
<td style="text-align: left;">Distributional distance across factorised perceptual dimensions</td>
<td style="text-align: left;">The only metric validated to correlate with human judgement across domains</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Two entries deserve elaboration.</p>
<p><strong>WER as an intelligibility proxy has a revealing pathology</strong>: human recordings frequently score <em>worse</em> than good synthetic speech. That should immediately tell you it is measuring how easy the audio is for an ASR model to transcribe, not how intelligible it is to a person. It remains useful — it catches the catastrophic failures of <a href="#tbl-attention-failures" class="quarto-xref">Table&nbsp;<span>31.5</span></a> reliably — but it should be read as a robustness check rather than a quality measure. Reporting under two different ASR families guards against a system being flattered by sharing a lineage with its evaluator.</p>
<p><strong>FAD is manipulable.</strong> Its finite-sample covariance estimate biases the score by <span class="math inline">\(O(1/N)\)</span>, which means <strong>you can improve your reported FAD simply by generating more samples</strong>. That is an improvement obtainable with no change to the model.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Optimising these metrics directly backfires
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using WER as a reinforcement-learning reward measurably improves the metric while collapsing prosody toward monotone delivery. It is a clean instance of reward hacking outside the text modality: the reward captures intelligibility and is silent about everything else that makes speech worth listening to.</p>
</div>
</div>
</section>
<section id="sec-tts-datasets" class="level3" data-number="31.12.3">
<h3 data-number="31.12.3" class="anchored" data-anchor-id="sec-tts-datasets"><span class="header-section-number">31.12.3</span> Datasets and Protocols</h3>
<div id="tbl-tts-datasets" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tts-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;31.11: Datasets and benchmarks for speech synthesis.
</figcaption>
<div aria-describedby="tbl-tts-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 31%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset</th>
<th style="text-align: left;">Scale</th>
<th style="text-align: left;">Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>LJSpeech</strong></td>
<td style="text-align: left;">~24 h, 1 speaker</td>
<td style="text-align: left;">Single-speaker sanity check; largely superseded</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>VCTK</strong></td>
<td style="text-align: left;">~44 h, 109 speakers</td>
<td style="text-align: left;">Multi-speaker and accent studies</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>LibriTTS</strong></td>
<td style="text-align: left;">~585 h, 2,456 speakers</td>
<td style="text-align: left;">The standard multi-speaker training corpus</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LibriSpeech</strong> <code>test-clean</code> <span class="citation" data-cites="panayotov2015librispeech">(<a href="../../references.html#ref-panayotov2015librispeech" role="doc-biblioref">Panayotov et al. 2015</a>)</span></td>
<td style="text-align: left;">~5.4 h</td>
<td style="text-align: left;">The conventional zero-shot evaluation set</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Libri-Light / Libriheavy</strong> <span class="citation" data-cites="kahn2020librilight kang2024libriheavy">(<a href="../../references.html#ref-kahn2020librilight" role="doc-biblioref">Kahn et al. 2020</a>; <a href="../../references.html#ref-kang2024libriheavy" role="doc-biblioref">Kang et al. 2024</a>)</span></td>
<td style="text-align: left;">60k / 50k h</td>
<td style="text-align: left;">Pre-training corpora of the codec-LM era</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Emilia</strong> <span class="citation" data-cites="he2024emilia">(<a href="../../references.html#ref-he2024emilia" role="doc-biblioref">He et al. 2024</a>)</span></td>
<td style="text-align: left;">~101k h, in-the-wild, multilingual</td>
<td style="text-align: left;">The standard large-scale in-the-wild corpus</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>seed-tts-eval</strong> <span class="citation" data-cites="anastassiou2024seedtts">(<a href="../../references.html#ref-anastassiou2024seedtts" role="doc-biblioref"><span class="nocase">Anastassiou et al.</span> 2024</a>)</span></td>
<td style="text-align: left;">1k English + 2k Mandarin + a hard split</td>
<td style="text-align: left;">The <em>de facto</em> zero-shot benchmark since 2024</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The <strong>seed-tts-eval</strong> protocol — reference clip, prompt transcript, target text; report WER and speaker similarity — is what most 2025–2026 papers quote. Its hard split is the most honest number in the field: frontier character error rates there run around 6–8%, roughly an order of magnitude worse than on the easy splits.</p>
<p>A newer generation of benchmarks targets what single-sentence naturalness cannot measure: complex prosody and expressiveness <span class="citation" data-cites="guan2025emergentttseval">(<a href="../../references.html#ref-guan2025emergentttseval" role="doc-biblioref">Manku et al. 2025</a>)</span> and natural-language instruction following <span class="citation" data-cites="huang2025instructttseval">(<a href="../../references.html#ref-huang2025instructttseval" role="doc-biblioref">Huang et al. 2025</a>)</span>, both typically judged by a large audio-language model rather than by human raters — a practice that is spreading quickly and has itself received almost no meta-evaluation.</p>
</section>
<section id="sec-tts-comparability" class="level3" data-number="31.12.4">
<h3 data-number="31.12.4" class="anchored" data-anchor-id="sec-tts-comparability"><span class="header-section-number">31.12.4</span> The Comparability Problem</h3>
<p>A 2025 position paper <span class="citation" data-cites="wang2025responsibletts">(<a href="../../references.html#ref-wang2025responsibletts" role="doc-biblioref">C. Wang et al. 2025</a>)</span> documents that the standard reporting set — WER, similarity, MOS, and real-time factor — is failing simultaneously, and its most concrete finding deserves quoting directly. Papers reporting “WER on LibriSpeech <code>test-clean</code>” have used <strong>1,234 samples</strong>, <strong>40 samples</strong>, and <strong>1,127 samples with punctuation preserved</strong>, among other choices. These are not the same measurement. A 40-sample evaluation has enormous variance and is not comparable to a 1,234-sample one, yet both appear in tables as a single number under a single column heading.</p>
<p>Similar problems affect the rest of the set. Similarity protocols differ on whether the prompt segment is included and on which speaker encoder is used, and saturate above a threshold beyond which further gains are imperceptible. Real-time factors are reported without batch size, hardware, vocoder, or streaming status. And test-set contamination is a live concern, since LibriSpeech is both the primary TTS benchmark and plausibly present in the pre-training corpora of the text LLMs that modern systems are built on <span class="citation" data-cites="tseng2025contamination">(<a href="../../references.html#ref-tseng2025contamination" role="doc-biblioref">Tseng et al. 2025</a>)</span>.</p>
<p>The defensible practice in 2026 is therefore: run your own listening test with all baselines included; pin a public protocol for objective numbers; add a distributional metric with validated human correlation; and treat any cross-paper comparison you did not run yourself as unreliable.</p>
</section>
</section>
<section id="sec-tts-open" class="level2" data-number="31.13">
<h2 data-number="31.13" class="anchored" data-anchor-id="sec-tts-open"><span class="header-section-number">31.13</span> Open Problems</h2>
<ol type="1">
<li><strong>Long-form consistency.</strong> Single-sentence quality is essentially solved; multi-minute coherence is not. Speaker drift, prosodic discontinuity at sentence boundaries, and the loss of discourse-level structure — given/new information, contrastive stress, paragraph pacing — all persist. There is no accepted metric for prosodic coherence over minutes, which is part of why there is little progress.</li>
<li><strong>Controllable expressivity.</strong> <em>Producing</em> expressive speech is largely solved by prompting and scale. <em>Specifying</em> it is not. Compositional control (happy <strong>and</strong> whispered <strong>and</strong> emphasising this word) and context-inferred delivery, where correct prosody must be deduced from surrounding text rather than stated, both remain weak.</li>
<li><strong>Robustness in autoregressive models.</strong> The <a href="#tbl-attention-failures" class="quarto-xref">Table&nbsp;<span>31.5</span></a> catalogue is reduced but not eliminated, and no method offers a guarantee — only a lower rate. The hard splits of current benchmarks are where this shows.</li>
<li><strong>Evaluation.</strong> Arguably the rate-limiting problem for the whole field. Open: a subjective protocol with resolution above the human-parity ceiling; objective metrics validated on <em>modern</em> systems; contamination-free refreshed benchmarks; and meta-evaluation of the audio-LLM judges now being adopted quickly and uncritically.</li>
<li><strong>Latency versus quality in duplex systems.</strong> First-packet latencies below 100 ms are achievable, but full-duplex conversation exposes a frontier where low latency buys spurious interruptions and conservative endpointing buys sluggishness. No system is simultaneously fast, non-interrupting, and reliably yielding.</li>
<li><strong>Code-switching and the long tail.</strong> Massively multilingual synthesis has advanced quickly, but intra-sentential code-switching with native-like pronunciation in both languages, accent leakage from the reference voice, and grapheme-to-phoneme conversion for languages without a phonemiser all remain open — as does <em>evaluating</em> any of it, since recruiting native listeners for long-tail languages is often impossible.</li>
<li><strong>Safety and provenance.</strong> Standardised, interoperable, adversarially robust watermarking; attribution of <em>which</em> model produced a sample rather than merely that it is synthetic; and passive detection of unwatermarked output.</li>
<li><strong>What makes a representation learnable?</strong> Discrete tokens, VAE latents, mel, and waveform latents are all in current use, and there is evidence that better reconstruction fidelity in a learned representation does <strong>not</strong> predict better synthesis quality from it. Nobody has a principled account of what makes a speech representation good to <em>generate into</em>, as opposed to merely invertible. This strikes me as the most interesting open scientific question in the area.</li>
<li><strong>Scaling laws are unmapped.</strong> There is no compute-optimal frontier for speech generation analogous to those established for text, no clear picture of how quality trades off between hours, parameters, and token rate. This is not independent of problem 4: you cannot fit a scaling law to a quantity you cannot measure reliably.</li>
</ol>
</section>
<section id="summary" class="level2" data-number="31.14">
<h2 data-number="31.14" class="anchored" data-anchor-id="summary"><span class="header-section-number">31.14</span> Summary</h2>
<p>Speech synthesis is organised by one fact: the mapping from text to speech is one-to-many, so there is no correct output to regress toward. Minimising squared error returns the conditional mean of a multi-modal distribution, which corresponds to no real utterance and sounds muffled and lifeless. This diagnosis was made in 2009 for parametric synthesis and has driven every subsequent architectural decision.</p>
<p>Three strategies answer it, and the field’s history is their interleaving. WaveNet applied a categorical output distribution at the sample level and demonstrated that generative modelling, not better regression, was the missing ingredient — at a sequential cost that GAN vocoders later removed entirely. Tacotron showed a single attentional model could learn text-to-acoustics alignment unsupervised, and then showed why unconstrained attention driven by autoregression is catastrophic in production. FastSpeech made monotonic alignment structural rather than learned, and FastSpeech 2 made the one-to-many problem explicit by conditioning on the variables that explain the variance. Glow-TTS learned that alignment inside a likelihood model with monotonic alignment search, and VITS composed VAE, flow, adversarial training, and MAS into a single objective. Flow matching then made non-autoregressive generation cheap enough to dominate, and Voicebox’s reframing of synthesis as <em>infilling</em> unified voice cloning, editing, and continuation into one training task. Codec tokens made speech a language-modelling problem, which bought in-context voice cloning and the whole LLM toolchain — and which promptly reintroduced the autoregressive failure modes the field had spent 2019 to 2021 eliminating.</p>
<p>Two threads are worth carrying into the following chapters. The token grid that <a href="#sec-codec-lm" class="quarto-xref"><span>Section 31.9</span></a> treats as given is the subject of <a href="24-neural-audio-codecs.html" class="quarto-xref"><span>Chapter 30</span></a>, where residual quantisation, codebook collapse, frame rate, and the serialisation of a two-dimensional grid into a one-dimensional sequence get the treatment they deserve. And the streaming, duplex, text-and-audio-interleaved models sketched in <a href="#sec-tts-streaming" class="quarto-xref"><span>Section 31.9.6</span></a> are the architecture of the speech language models of <a href="26-speech-language-models.html" class="quarto-xref"><span>Chapter 32</span></a>, which close this part of the book.</p>
<p>The honest summary of the current state is that synthesis quality on short, clean, single-sentence inputs is at or near the ceiling of what listening tests can resolve — and that this is as much a statement about the tests as about the models.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-anastassiou2024seedtts" class="csl-entry" role="listitem">
<span class="nocase">Anastassiou, Philip, Jiawei Chen, Jitong Chen, et al.</span> 2024. <span>“<span>Seed-TTS</span>: A Family of High-Quality Versatile Speech Generation Models.”</span> <em>arXiv Preprint arXiv:2406.02430</em>.
</div>
<div id="ref-borsos2023audiolm" class="csl-entry" role="listitem">
Borsos, Zalán, Raphaël Marinier, Damien Vincent, et al. 2023. <span>“<span>AudioLM</span>: A Language Modeling Approach to Audio Generation.”</span> <em>IEEE/ACM Transactions on Audio, Speech, and Language Processing</em> 31.
</div>
<div id="ref-casanova2024xtts" class="csl-entry" role="listitem">
Casanova, Edresson, Kelly Davis, Eren Gölge, et al. 2024. <span>“<span>XTTS</span>: A Massively Multilingual Zero-Shot Text-to-Speech Model.”</span> <em>Interspeech</em>.
</div>
<div id="ref-chen2021wavegrad" class="csl-entry" role="listitem">
Chen, Nanxin, Yu Zhang, Heiga Zen, Ron J. Weiss, Mohammad Norouzi, and William Chan. 2021. <span>“<span>WaveGrad</span>: Estimating Gradients for Waveform Generation.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-chen2024valle2" class="csl-entry" role="listitem">
Chen, Sanyuan, Shujie Liu, Long Zhou, et al. 2024. <span>“<span>VALL-E 2</span>: Neural Codec Language Models Are Human Parity Zero-Shot Text to Speech Synthesizers.”</span> <em>arXiv Preprint arXiv:2406.05370</em>.
</div>
<div id="ref-chen2024f5tts" class="csl-entry" role="listitem">
Chen, Yushen, Zhikang Niu, Ziyang Ma, et al. 2024. <span>“<span>F5-TTS</span>: A Fairytaler That Fakes Fluent and Faithful Speech with Flow Matching.”</span> <em>arXiv Preprint arXiv:2410.06885</em>.
</div>
<div id="ref-cooper2025goodpractices" class="csl-entry" role="listitem">
Cooper, Erica, Sébastien Le Maguer, Esther Klabbers, and Junichi Yamagishi. 2025. <span>“Good Practices for Evaluation of Synthesized Speech.”</span> <em>arXiv Preprint arXiv:2503.03250</em>.
</div>
<div id="ref-defossez2023encodec" class="csl-entry" role="listitem">
Défossez, Alexandre, Jade Copet, Gabriel Synnaeve, and Yossi Adi. 2023. <span>“High Fidelity Neural Audio Compression.”</span> <em>Transactions on Machine Learning Research (TMLR)</em>.
</div>
<div id="ref-defossez2024moshi" class="csl-entry" role="listitem">
Défossez, Alexandre, Laurent Mazaré, Manu Orsini, et al. 2024. <span>“<span>Moshi</span>: A Speech-Text Foundation Model for Real-Time Dialogue.”</span> <em>arXiv Preprint arXiv:2410.00037</em>.
</div>
<div id="ref-du2024cosyvoice" class="csl-entry" role="listitem">
Du, Zhihao, Qian Chen, Shiliang Zhang, et al. 2024. <span>“<span>CosyVoice</span>: A Scalable Multilingual Zero-Shot Text-to-Speech Synthesizer Based on Supervised Semantic Tokens.”</span> <em>arXiv Preprint arXiv:2407.05407</em>.
</div>
<div id="ref-du2025cosyvoice3" class="csl-entry" role="listitem">
Du, Zhihao, Changfeng Gao, Yuxuan Wang, et al. 2025. <span>“<span>CosyVoice 3</span>: Towards in-the-Wild Speech Generation via Scaling-up and Post-Training.”</span> <em>arXiv Preprint arXiv:2505.17589</em>.
</div>
<div id="ref-du2024cosyvoice2" class="csl-entry" role="listitem">
Du, Zhihao, Yuxuan Wang, Qian Chen, et al. 2024. <span>“<span>CosyVoice 2</span>: Scalable Streaming Speech Synthesis with Large Language Models.”</span> <em>arXiv Preprint arXiv:2412.10117</em>.
</div>
<div id="ref-eskimez2024e2tts" class="csl-entry" role="listitem">
Eskimez, Sefik Emre, Xiaofei Wang, Manthan Thakker, et al. 2024. <span>“<span>E2 TTS</span>: Embarrassingly Easy Fully Non-Autoregressive Zero-Shot <span>TTS</span>.”</span> <em>IEEE Spoken Language Technology Workshop (SLT)</em>.
</div>
<div id="ref-he2024emilia" class="csl-entry" role="listitem">
He, Haorui, Zengqiang Shang, Chaoren Wang, et al. 2024. <span>“<span>Emilia</span>: An Extensive, Multilingual, and Diverse Speech Dataset for Large-Scale Speech Generation.”</span> <em>IEEE Spoken Language Technology Workshop (SLT)</em>.
</div>
<div id="ref-ho2020ddpm" class="csl-entry" role="listitem">
Ho, Jonathan, Ajay Jain, and Pieter Abbeel. 2020. <span>“Denoising Diffusion Probabilistic Models.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-ho2021cfg" class="csl-entry" role="listitem">
Ho, Jonathan, and Tim Salimans. 2021. <span>“Classifier-Free Diffusion Guidance.”</span> <em>NeurIPS Workshop on Deep Generative Models</em>.
</div>
<div id="ref-huang2025instructttseval" class="csl-entry" role="listitem">
Huang, Kexin, Qian Tu, Liwei Fan, et al. 2025. <span>“<span>InstructTTSEval</span>: Benchmarking Complex Natural-Language Instruction Following in Text-to-Speech Systems.”</span> <em>arXiv Preprint arXiv:2506.16381</em>.
</div>
<div id="ref-ju2024naturalspeech3" class="csl-entry" role="listitem">
Ju, Zeqian, Yuancheng Wang, Kai Shen, et al. 2024. <span>“<span>NaturalSpeech 3</span>: Zero-Shot Speech Synthesis with Factorized Codec and Diffusion Models.”</span> <em>International Conference on Machine Learning (ICML)</em>.
</div>
<div id="ref-kahn2020librilight" class="csl-entry" role="listitem">
Kahn, Jacob, Morgane Rivière, Weiyi Zheng, et al. 2020. <span>“Libri-Light: A Benchmark for <span>ASR</span> with Limited or No Supervision.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>, 7669–73.
</div>
<div id="ref-kalchbrenner2018wavernn" class="csl-entry" role="listitem">
Kalchbrenner, Nal, Erich Elsen, Karen Simonyan, et al. 2018. <span>“Efficient Neural Audio Synthesis.”</span> <em>International Conference on Machine Learning (ICML)</em>.
</div>
<div id="ref-kang2024libriheavy" class="csl-entry" role="listitem">
Kang, Wei, Xiaoyu Yang, Zengwei Yao, et al. 2024. <span>“Libriheavy: A 50,000 Hours <span>ASR</span> Corpus with Punctuation Casing and Context.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>.
</div>
<div id="ref-kharitonov2023speartts" class="csl-entry" role="listitem">
Kharitonov, Eugene, Damien Vincent, Zalán Borsos, et al. 2023. <span>“Speak, Read and Prompt: High-Fidelity Text-to-Speech with Minimal Supervision.”</span> <em>Transactions of the Association for Computational Linguistics (TACL)</em> 11.
</div>
<div id="ref-kilgour2019fad" class="csl-entry" role="listitem">
Kilgour, Kevin, Mauricio Zuluaga, Dominik Roblek, and Matthew Sharifi. 2019. <span>“Fr<span>é</span>chet Audio Distance: A Reference-Free Metric for Evaluating Music Enhancement Algorithms.”</span> <em>Interspeech</em>.
</div>
<div id="ref-kim2020glowtts" class="csl-entry" role="listitem">
Kim, Jaehyeon, Sungwon Kim, Jungil Kong, and Sungroh Yoon. 2020. <span>“<span>Glow-TTS</span>: A Generative Flow for Text-to-Speech via Monotonic Alignment Search.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-kim2021vits" class="csl-entry" role="listitem">
Kim, Jaehyeon, Jungil Kong, and Juhee Son. 2021. <span>“Conditional Variational Autoencoder with Adversarial Learning for End-to-End Text-to-Speech.”</span> <em>International Conference on Machine Learning (ICML)</em>.
</div>
<div id="ref-kong2020hifigan" class="csl-entry" role="listitem">
Kong, Jungil, Jaehyeon Kim, and Jaekyoung Bae. 2020. <span>“<span>HiFi-GAN</span>: Generative Adversarial Networks for Efficient and High Fidelity Speech Synthesis.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-kong2021diffwave" class="csl-entry" role="listitem">
Kong, Zhifeng, Wei Ping, Jiaji Huang, Kexin Zhao, and Bryan Catanzaro. 2021. <span>“<span>DiffWave</span>: A Versatile Diffusion Model for Audio Synthesis.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-kumar2019melgan" class="csl-entry" role="listitem">
Kumar, Kundan, Rithesh Kumar, Thibault de Boissiere, et al. 2019. <span>“<span>MelGAN</span>: Generative Adversarial Networks for Conditional Waveform Synthesis.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-kumar2023dac" class="csl-entry" role="listitem">
Kumar, Rithesh, Prem Seetharaman, Alejandro Luebs, Ishaan Kumar, and Kundan Kumar. 2023. <span>“High-Fidelity Audio Compression with Improved <span>RVQGAN</span>.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-le2023voicebox" class="csl-entry" role="listitem">
Le, Matthew, Apoorv Vyas, Bowen Shi, et al. 2023. <span>“<span>Voicebox</span>: Text-Guided Multilingual Universal Speech Generation at Scale.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-lee2023bigvgan" class="csl-entry" role="listitem">
Lee, Sang-gil, Wei Ping, Boris Ginsburg, Bryan Catanzaro, and Sungroh Yoon. 2023. <span>“<span>BigVGAN</span>: A Universal Neural Vocoder with Large-Scale Training.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-lipman2023flowmatching" class="csl-entry" role="listitem">
Lipman, Yaron, Ricky T. Q. Chen, Heli Ben-Hamu, Maximilian Nickel, and Matt Le. 2023. <span>“Flow Matching for Generative Modeling.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-lemaguer2024moslimits" class="csl-entry" role="listitem">
Maguer, Sébastien Le, Simon King, and Naomi Harte. 2024. <span>“The Limits of the Mean Opinion Score for Speech Synthesis Evaluation.”</span> <em>Computer Speech &amp; Language</em> 84: 101577.
</div>
<div id="ref-guan2025emergentttseval" class="csl-entry" role="listitem">
Manku, Ruskin Raj, Yuzhi Tang, Xingjian Shi, Mu Li, and Alex Smola. 2025. <span>“<span>EmergentTTS-Eval</span>: Evaluating <span>TTS</span> Models on Complex Prosodic, Expressiveness, and Linguistic Challenges Using Model-as-a-Judge.”</span> <em>arXiv Preprint arXiv:2505.23009</em>.
</div>
<div id="ref-mehta2024matchatts" class="csl-entry" role="listitem">
Mehta, Shivam, Ruibo Tu, Jonas Beskow, Éva Székely, and Gustav Eje Henter. 2024. <span>“<span>Matcha-TTS</span>: A Fast <span>TTS</span> Architecture with Conditional Flow Matching.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>.
</div>
<div id="ref-meng2024melle" class="csl-entry" role="listitem">
Meng, Lingwei, Long Zhou, Shujie Liu, et al. 2024. <span>“Autoregressive Speech Synthesis Without Vector Quantization.”</span> <em>arXiv Preprint arXiv:2407.08551</em>.
</div>
<div id="ref-minixhofer2025ttsds2" class="csl-entry" role="listitem">
Minixhofer, Christoph, Ondřej Klejch, and Peter Bell. 2025. <span>“<span>TTSDS2</span>: Resources and Benchmark for Evaluating Human-Quality Text to Speech Systems.”</span> <em>ISCA Speech Synthesis Workshop (SSW)</em>.
</div>
<div id="ref-mittag2021nisqa" class="csl-entry" role="listitem">
Mittag, Gabriel, Babak Naderi, Assmaa Chehadi, and Sebastian Möller. 2021. <span>“<span>NISQA</span>: A Deep <span>CNN</span>-Self-Attention Model for Multidimensional Speech Quality Prediction with Crowdsourced Datasets.”</span> <em>Interspeech</em>.
</div>
<div id="ref-morise2016world" class="csl-entry" role="listitem">
Morise, Masanori, Fumiya Yokomori, and Kenji Ozawa. 2016. <span>“<span>WORLD</span>: A Vocoder-Based High-Quality Speech Synthesis System for Real-Time Applications.”</span> <em>IEICE Transactions on Information and Systems</em> E99-D (7): 1877–84.
</div>
<div id="ref-oord2016wavenet" class="csl-entry" role="listitem">
Oord, Aäron van den, Sander Dieleman, Heiga Zen, et al. 2016. <span>“<span>WaveNet</span>: A Generative Model for Raw Audio.”</span> <em>ISCA Speech Synthesis Workshop (SSW)</em>.
</div>
<div id="ref-oord2018parallelwavenet" class="csl-entry" role="listitem">
<span class="nocase">Oord, Aäron van den, Yazhe Li, Igor Babuschkin, et al.</span> 2018. <span>“Parallel <span>WaveNet</span>: Fast High-Fidelity Speech Synthesis.”</span> <em>International Conference on Machine Learning (ICML)</em>.
</div>
<div id="ref-panayotov2015librispeech" class="csl-entry" role="listitem">
Panayotov, Vassil, Guoguo Chen, Daniel Povey, and Sanjeev Khudanpur. 2015. <span>“<span>LibriSpeech</span>: An <span>ASR</span> Corpus Based on Public Domain Audio Books.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>, 5206–10.
</div>
<div id="ref-popov2021gradtts" class="csl-entry" role="listitem">
Popov, Vadim, Ivan Vovk, Vladimir Gogoryan, Tasnima Sadekova, and Mikhail Kudinov. 2021. <span>“<span>Grad-TTS</span>: A Diffusion Probabilistic Model for Text-to-Speech.”</span> <em>International Conference on Machine Learning (ICML)</em>.
</div>
<div id="ref-prenger2019waveglow" class="csl-entry" role="listitem">
Prenger, Ryan, Rafael Valle, and Bryan Catanzaro. 2019. <span>“<span>WaveGlow</span>: A Flow-Based Generative Network for Speech Synthesis.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>.
</div>
<div id="ref-reddy2021dnsmos" class="csl-entry" role="listitem">
Reddy, Chandan K. A., Vishak Gopal, and Ross Cutler. 2021. <span>“<span>DNSMOS</span>: A Non-Intrusive Perceptual Objective Speech Quality Metric to Evaluate Noise Suppressors.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>.
</div>
<div id="ref-ren2021fastspeech2" class="csl-entry" role="listitem">
Ren, Yi, Chenxu Hu, Xu Tan, et al. 2021. <span>“<span>FastSpeech 2</span>: Fast and High-Quality End-to-End Text to Speech.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-ren2019fastspeech" class="csl-entry" role="listitem">
Ren, Yi, Yangjun Ruan, Xu Tan, et al. 2019. <span>“<span>FastSpeech</span>: Fast, Robust and Controllable Text to Speech.”</span> <em>Advances in Neural Information Processing Systems (NeurIPS)</em>.
</div>
<div id="ref-ren2022oversmooth" class="csl-entry" role="listitem">
Ren, Yi, Xu Tan, Tao Qin, Zhou Zhao, and Tie-Yan Liu. 2022. <span>“Revisiting over-Smoothness in Text to Speech.”</span> <em>Annual Meeting of the Association for Computational Linguistics (ACL)</em>.
</div>
<div id="ref-saeki2022utmos" class="csl-entry" role="listitem">
Saeki, Takaaki, Detai Xin, Wataru Nakata, Tomoki Koriyama, Shinnosuke Takamichi, and Hiroshi Saruwatari. 2022. <span>“<span>UTMOS</span>: <span>UTokyo-SaruLab</span> System for <span>VoiceMOS</span> Challenge 2022.”</span> <em>Interspeech</em>.
</div>
<div id="ref-shen2018tacotron2" class="csl-entry" role="listitem">
Shen, Jonathan, Ruoming Pang, Ron J. Weiss, et al. 2018. <span>“Natural <span>TTS</span> Synthesis by Conditioning <span>WaveNet</span> on Mel Spectrogram Predictions.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>.
</div>
<div id="ref-siuzdak2024vocos" class="csl-entry" role="listitem">
Siuzdak, Hubert. 2024. <span>“<span>Vocos</span>: Closing the Gap Between Time-Domain and Fourier-Based Neural Vocoders for High-Quality Audio Synthesis.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
<div id="ref-tseng2025contamination" class="csl-entry" role="listitem">
Tseng, Yuan, Titouan Parcollet, Rogier van Dalen, Shucong Zhang, and Sourav Bhattacharya. 2025. <span>“Evaluation of <span>LLMs</span> in Speech Is Often Flawed: Test Set Contamination in Large Language Models for Speech Recognition.”</span> <em>IEEE Automatic Speech Recognition and Understanding Workshop (ASRU)</em>.
</div>
<div id="ref-valin2019lpcnet" class="csl-entry" role="listitem">
Valin, Jean-Marc, and Jan Skoglund. 2019. <span>“<span>LPCNet</span>: Improving Neural Speech Synthesis Through Linear Prediction.”</span> <em>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</em>.
</div>
<div id="ref-wang2023valle" class="csl-entry" role="listitem">
Wang, Chengyi, Sanyuan Chen, Yu Wu, et al. 2023. <span>“Neural Codec Language Models Are Zero-Shot Text to Speech Synthesizers.”</span> <em>arXiv Preprint arXiv:2301.02111</em>.
</div>
<div id="ref-wang2025responsibletts" class="csl-entry" role="listitem">
Wang, Chenxu, Zhihao Du, Yuxuan Wang, et al. 2025. <span>“Position: Towards Responsible Evaluation for Text-to-Speech.”</span> <em>arXiv Preprint arXiv:2510.06927</em>.
</div>
<div id="ref-wang2025sparktts" class="csl-entry" role="listitem">
Wang, Xinsheng, Mingqi Jiang, Ziyang Ma, et al. 2025. <span>“<span>Spark-TTS</span>: An Efficient LLM-Based Text-to-Speech Model with Single-Stream Decoupled Speech Tokens.”</span> <em>arXiv Preprint arXiv:2503.01710</em>.
</div>
<div id="ref-wang2017tacotron" class="csl-entry" role="listitem">
Wang, Yuxuan, R. J. Skerry-Ryan, Daisy Stanton, et al. 2017. <span>“<span>Tacotron</span>: Towards End-to-End Speech Synthesis.”</span> <em>Interspeech</em>.
</div>
<div id="ref-ye2025llasa" class="csl-entry" role="listitem">
Ye, Zhen, Xinfa Zhu, Chi-Min Chan, et al. 2025. <span>“<span>Llasa</span>: Scaling Train-Time and Inference-Time Compute for Llama-Based Speech Synthesis.”</span> <em>arXiv Preprint arXiv:2502.04128</em>.
</div>
<div id="ref-zeghidour2022soundstream" class="csl-entry" role="listitem">
Zeghidour, Neil, Alejandro Luebs, Ahmed Omran, Jan Skoglund, and Marco Tagliasacchi. 2022. <span>“<span>SoundStream</span>: An End-to-End Neural Audio Codec.”</span> <em>IEEE/ACM Transactions on Audio, Speech, and Language Processing</em> 30.
</div>
<div id="ref-zen2009spss" class="csl-entry" role="listitem">
Zen, Heiga, Keiichi Tokuda, and Alan W. Black. 2009. <span>“Statistical Parametric Speech Synthesis.”</span> <em>Speech Communication</em> 51 (11): 1039–64.
</div>
<div id="ref-zhang2024speechtokenizer" class="csl-entry" role="listitem">
Zhang, Xin, Dong Zhang, Shimin Li, Yaqian Zhou, and Xipeng Qiu. 2024. <span>“<span>SpeechTokenizer</span>: Unified Speech Tokenizer for Speech Large Language Models.”</span> <em>International Conference on Learning Representations (ICLR)</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const callouts = document.querySelectorAll('.callout-tip');
    callouts.forEach(function(callout) {
      callout.style.borderLeftColor = '#2196f3'; //#616161; //'#4caf50';
      callout.style.color = 'ffffff'; // Dark purple-gray text
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/audio/24-neural-audio-codecs.html" class="pagination-link" aria-label="Neural Audio Codecs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Neural Audio Codecs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/audio/26-speech-language-models.html" class="pagination-link" aria-label="Speech and Audio Language Models">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Speech and Audio Language Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>